### PR TITLE
Closes #2194 + Closes #2163 + Closes #2167

### LINKED ISSUE #2163: Dashboard: only show group history if it exists
### Problem

Immediately when a group is created, the dashboard "support %" and "todo %" tabs both show 0% for periods before distribution starts because the group, unsurprisingly, did nothing before the first distribution started. Showing 0% success is demoralizing, and not at all a good way to introduce users to the app.

This group was newly created, with first distribution period starting on July 30.  
Support history shows both a period before distribution starts (Jun 30 - Jul 30) and period in the future (Jul 30 - Aug 29). 
demoralizingSupportHistory

TODO history shows a period before distribution starts (Jun 30 - Jul 30).
demoralizingTODOpercent

Members cannot even mark payments as sent before the first distribution starts because the "Payments" screen simply shows "The distribution period begins on: $date" 

(Different new group, with distribution period starting August 1)
demoralizingPayments

### Solution

Only show history when history exists. Likewise, do not show future periods.
If there is no history to be shown, then show a similar message as is shown for proposals: "No periods have been completed yet." or the same message as is shown on Payments: "The distribution period begins on: $date"

### LINKED ISSUE #2167: Invalid Date in support graphs
### Problem

In the GIG group, which is running contracts version `0.3.0` and GI_VERSION `GI_VERSION: 0.0.1@2024-07-01T20:11:59.326Z` (that seems wrong, as it implies the frontend code is from 7 days ago, which is definitely not true), we see "Invalid Date" on the graphs:

Screenshot 2024-07-08 at 9 01 41 AM
Screenshot 2024-07-08 at 9 01 48 AM

### Solution

Figure out why this is happening. @SebinSong I've assigned this to you and will also have DM'd you the data from the server so that you can reproduce locally with `GI_PERSIST=sqlite grunt dev`.

### LINKED ISSUE #2194: DOMException: The quota has been exceeded.
### Problem

Screenshot 2024-07-14 at 12 46 19 PM

During development, old log entries build up because the entries for the old identityContractIDs never get cleared, causing this exception:

```
DOMException: The quota has been exceeded.
```

### Solution

Clear the old entries for the old contract ID.

### PR DESCRIPTION
**Pull request by taoeffect**
+ #2167 - Fixes invalid date in support graphs
+ #2163 - Show group history graphs only if it exists
+ #2194 - Prevent 'DOMException: The quota has been exceeded' error

> [!IMPORTANT]
> For fixing the `DOMException: The quota has been exceeded`, if you see it you should delete your local storage contents and re-run the app. But from then on this PR should prevent it from showing up again.

### CODE REVIEW

File: frontend/model/contracts/shared/time.js [hunk 1]
```diff
@@ -30,19 +33,27 @@ export function periodStampsForDate (
...
       current = periodStampGivenDate({ recentDate: timestamp, periodStart: latest, periodLength })
       next = plusOnePeriodLength(current, periodLength)
       previous = current > latest
         ? minusOnePeriodLength(current, periodLength)
         : knownSortedStamps[knownSortedStamps.length - 2]
+    } else if (guess && timestamp < earliest) {
+      // handle dates earlier than all known stamps
+      current = periodStampGivenDate({ recentDate: timestamp, periodStart: earliest, periodLength })
+      next = plusOnePeriodLength(current, periodLength)
+      previous = minusOnePeriodLength(current, periodLength)
```
Comment (taoeffect) [inline frontend/model/contracts/shared/time.js:47]: Note: this ended up not being needed to close the issue, but I left it because it seems potentially useful to be able to return guessed period stamps based on the period length instead of `undefined`

File: frontend/views/containers/payments/PaymentsMixin.js [hunk 2]
```diff
@@ -173,8 +180,8 @@ const PaymentsMixin: Object = {
       return this.groupPeriodPayments[period] ?? (await this.getHistoricalPeriodPayments())[period] ?? {}
     },
     // Returns a human-readable description of the time interval identified by a given period stamp.
-    getPeriodFromStartToDueDate (period) {
-      const dueDate = this.dueDateForPeriod(period)
+    getPeriodFromStartToDueDate (period, knownPeriods) {
+      const dueDate = this.dueDateForPeriod(period, knownPeriods)
```
Comment (taoeffect) [inline frontend/views/containers/payments/PaymentsMixin.js:184]: This was the real fix for #2167

File: frontend/views/containers/contributions/TodoHistory.vue [hunk 3]
```diff
@@ -38,45 +37,42 @@ export default ({
...
+        }
+      }))
     }
   },
   watch: {
     currentPaymentPeriod () {
       this.updateHistory()
+    },
+    thisPeriodPaymentInfo () {
+      this.updateHistory()
```
Comment (taoeffect) [inline frontend/views/containers/contributions/TodoHistory.vue]: Before the graphs wouldn't update when a payment was made, now they do because of this code

File: frontend/views/containers/contributions/SupportHistory.vue [hunk 4]
```diff
@@ -41,22 +42,24 @@ export default ({
...
+      const allPeriods = await this.getAllSortedPeriodKeys()
+      const periods = allPeriods.slice(-MAX_HISTORY_PERIODS)
+      this.history = await Promise.all(periods.map(async (period) => {
         const totalTodo = await this.getTotalTodoAmountForPeriod(period)
         const totalDone = await this.getTotalPledgesDoneForPeriod(period)
 
         return {
-          total: totalDone === 0 ? 0 : totalDone / totalTodo,
-          title: this.getPeriodFromStartToDueDate(period),
+          total: totalDone === 0 || totalTodo === 0 ? 0 : totalDone / totalTodo,
```
Comment (SebinSong) [inline frontend/views/containers/contributions/SupportHistory.vue:61]: Nice one here.(I remember fixing `NaN` being displayed somewhere else by adding this there)

**Review by SebinSong — APPROVED** [review]
I haven't found anything wrong from my first review so giving an approval now.
(Will come back again for more thorough reviews later this week when I have time)

File: test/cypress/integration/group-paying.spec.js [hunk 5]
```diff
@@ -61,7 +61,7 @@ function openNotificationCard ({
   cy.getByDT('notificationBell').click()
   cy.getByDT('notificationCard').should('be.visible')
 
-  cy.getByDT('notificationCard').within(() => {
+  return cy.getByDT('notificationCard').within(() => {
```
Comment (Silver-IT) [inline test/cypress/integration/group-paying.spec.js:64]: Why is this `return` needed?

File: frontend/model/contracts/group.js [hunk 6]
```diff
@@ -501,6 +502,8 @@ sbp('chelonia/defineContract', {
           state[key] = initialState[key]
         }
         initFetchPeriodPayments({ contractID, meta, state, getters })
+        // remember the waiting period so tha we can skip archiving it (hack for hiding it in the Support History)
```
Comment (Silver-IT) [inline frontend/model/contracts/group.js:505]: Small typo; `so tha`. I think it should be `so that`

**Review by Silver-IT — APPROVED** [review]
Nice work, @taoeffect! LGTM!
A small typo (this can be fixed in another PR too) and one curious question below.

File: test/cypress/integration/group-paying.spec.js (hunk 5 above)
Comment (taoeffect) [reply test/cypress/integration/group-paying.spec.js:64]: Just in case the caller wants to be able to continue chaining anything off of this call
