### PR TITLE
Fix the bug in GroupsList

### LINKED ISSUE #615: Bugs in GroupsList (group switcher)
### Problem

- Upon switching to another group, the group icon isn't updated
- Upon switching to another group, it doesn't seem to let you switch back to the first group

Also, possibly unrelated, there is log spam along these lines:

```
[Vue tip]: Prop "itemid" is passed to component <Anonymous>, but the declared prop name is "itemId". Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "item-id" instead of "itemId". vue.common.dev.js:636:14
[Vue tip]: Prop "hasdivider" is passed to component <Anonymous>, but the declared prop name is "hasDivider". Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "has-divider" instead of "hasDivider". vue.common.dev.js:636:14
[Vue tip]: Prop "disableradius" is passed to component <Anonymous>, but the declared prop name is "disableRadius". Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "disable-radius" instead of "disableRadius". vue.common.dev.js:636:14
[Vue tip]: Prop "isactive" is passed to component <Anonymous>, but the declared prop name is "isActive". Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "is-active" instead of "isActive".
```

### Solution

Fix

### PR DESCRIPTION
**Pull request by SebinSong**
closes #615 .

simply changing the prop names to the camel-case versions fixes the bug as well(and personally think looks neater) but chose to use kebab-case because [Vue-documentation](https://vuejs.org/v2/guide/components-props.html#Prop-Casing-camelCase-vs-kebab-case) tells to do so.

### CODE REVIEW

File: frontend/views/components/Menu/MenuItem.vue [hunk 1]
```diff
@@ -16,7 +16,7 @@ export default {
   inheritAttrs: false,
   methods: {
     handleSelect () {
-      this.Menu.handleSelect(this.$attrs.itemId) // Use $attrs to access passed props
+      this.Menu.handleSelect(this.$attrs['item-id']) // Use $attrs to access passed props
```
Comment (pieer) [inline frontend/views/components/Menu/MenuItem.vue:19]: Something weird here.
Normally we don't inject an object with functions from the parent to be executed in the child.
We get the click from child then pass to the parent the event to execute the function.
Child:
list-item(@click="$emit('handle-select', $attrs['item-id])")
Parent:
MenuItem(:handle-select=”something”)

File: frontend/views/components/Avatar.vue [hunk 2]
```diff
@@ -39,9 +39,11 @@ export default {
       this.$refs.img.onload = function () { URL.revokeObjectURL(this.src) }
       this.objectURL = URL.createObjectURL(blob)
     },
-    async setBlobURL (newBlobURL) {
-      const oldBlobURL = this.blobURL
-      if (!newBlobURL) return // don't do anything if newBlobURL is blank
+    async setBlobURL (newBlobURL, oldBlobURL) {
```
Comment (pieer) [inline frontend/views/components/Avatar.vue]: I'm not sure why we pass 'oldBlobURL' variable into the function if this is a variable already available in the component as this.blobURL (assuming that blobURL was working before)

File: frontend/views/components/Avatar.vue [hunk 3]
```diff
@@ -77,8 +79,8 @@ export default {
   },
   watch: {
     blobURL (newBlobURL, oldBlobURL) {
-      console.debug(`Avatar blobURL watcher: ${oldBlobURL} => ${newBlobURL}`)
-      this.setBlobURL(newBlobURL)
+      console.log(`Avatar blobURL watcher: ${oldBlobURL} => ${newBlobURL}`)
+      this.setBlobURL(newBlobURL, oldBlobURL)
```
Comment (taoeffect) [inline frontend/views/components/Avatar.vue]: Yeah, agreed with @pieer, not sure why this code is being modified. The old code worked fine I think (in terms of getting `oldBlobURL`). Also, why change `.debug` to `.log`? Unless there is a reason for it, please keep it as `.debug` since it is just debug output and nothing important.

File: frontend/views/components/Avatar.vue [hunk 4]
```diff
@@ -39,9 +39,11 @@ export default {
       this.$refs.img.onload = function () { URL.revokeObjectURL(this.src) }
       this.objectURL = URL.createObjectURL(blob)
     },
-    async setBlobURL (newBlobURL) {
-      const oldBlobURL = this.blobURL
-      if (!newBlobURL) return // don't do anything if newBlobURL is blank
+    async setBlobURL (newBlobURL, oldBlobURL) {
+      if (!newBlobURL) {
+        this.objectURL = ''
```
Comment (taoeffect) [inline frontend/views/components/Avatar.vue:45]: I'm not sure if this change is needed but this seems OK to keep here.

**Review by taoeffect — CHANGES_REQUESTED** [review]
Sebin great job on fixing the issue! 😄 👍 

I only request a minor change, same thing that @pieer observed regarding the passing in of `oldBlobURL` being unnecessary. Also one question/issue about converting `.log` to `.debug`. I think we should keep it as `.debug`, especially as that might be helpful later on when we improving our logging code.

**Review by taoeffect — APPROVED** [review]
Great job @SebinSong! 🙌
