### PR TITLE
Key rotation robustness

### LINKED ISSUE #2988: Unable to join chatrooms or create new ones
### Problem

In production, I'm unable to join the `#random` channel and also unable to create a new chatroom, or otherwise interact with the group.

<figure>
Image
<figcaption>Unable to create a chatroom</figcaption>
</figure>

<figure>
Image
<figcaption>Unable to create a proposal</figcaption>
</figure>

<figure>
Image
<figcaption>Unable to join an existing chatroom</figcaption>
</figure>

This is likely the result of a key rotation having gone wrong, resulting in missing keys.

### Solution

Identify the issue and apply a fix to prevent it from happening in the future, as well as, if possible, fix it for existing users that may be affected.

### PR DESCRIPTION
**Pull request by corrideat**
Closes #2988

---

<a href="https://app.devin.ai/review/okturtles/group-income/pull/3058" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

**Comment by corrideat** [comment]
In order to test this PR, one could apply the following patch:

```patch
diff --git a/frontend/controller/actions/chatroom.js b/frontend/controller/actions/chatroom.js
index 6ef219e85..d32470e06 100644
--- a/frontend/controller/actions/chatroom.js
+++ b/frontend/controller/actions/chatroom.js
@@ -347,6 +347,7 @@ export default (sbp('sbp/selectors/register', {
 
     const activeMemberIds = sbp('state/vuex/getters').chatRoomActiveMemberIdsForChatRoom(state)
     return Promise.all(activeMemberIds.map(async (pContractID) => {
+      if (pContractID !== sbp('chelonia/rootState').loggedIn.identityContractID) return // TODO TEST REMOVE
       const retained = await sbp('chelonia/contract/retain', pContractID, { ephemeral: true }).then(() => [true], (e) => [false, e])
       if (!retained[0]) {
         const e = retained[1]
diff --git a/frontend/controller/actions/group.js b/frontend/controller/actions/group.js
index be3962695..3aa98ace6 100644
--- a/frontend/controller/actions/group.js
+++ b/frontend/controller/actions/group.js
@@ -744,6 +744,7 @@ export default (sbp('sbp/selectors/register', {
       Object.entries(state.profiles)
         .filter(([_, p]) => (p: any).status === PROFILE_STATUS.ACTIVE)
         .map(async ([pContractID]) => {
+          if (pContractID !== sbp('chelonia/rootState').loggedIn.identityContractID) return // TODO TEST REMOVE
           const retained = await sbp('chelonia/contract/retain', pContractID, { ephemeral: true }).then(() => [true], (e) => [false, e])
           if (!retained[0]) {
             const e = retained[1]
```

This will disable sharing keys with others following a rotation. Then, the members missing keys will request missing keys, which should work. For example, do as follows (similar steps for a private chatroom).

1. User A creates a group
2. User B and User C join said group (important: ensure the service worker is _not_ running afterwards / that user B has no active sessions)
3. User A removes User C from the group (important: ensure the service worker is _not_ running afterwards / that user A has no active sessions).
4. (Optional) After removing User C, User A posts some things to a chatroom.
5. User B logs in. They should 'see' the group but interacting with it will fail (also, they won't see messages posted by User A after removing user C). They should now have sent a key request.
6. User A logs in. Now, they should respond to User B's key request.
7. User B is now able to interact with the group and see messages.

---

You can also do an 'all-in-one' test by testing the migrations and these changes simultataneously.

1. Start app with an existing DB
2. Add a user ('B') to a group you're admin of (and which has at least one other member) -- (important: ensure the service worker is _not_ running afterwards / that user B has no active sessions) 
3. You remove 'User C' (any other user except 'B') from the group (important: ensure the service worker is _not_ running afterwards / that you have no active sessions).
6. (Optional) After removing User C, you post some things to a chatroom.
7. User B logs in. They should 'see' the group but interacting with it will fail (also, they won't see messages posted by you after removing user C). They should now have sent a key request.
8. You log in. Now, you should respond to User B's key request.
9. User B is now able to interact with the group and see messages.

**Comment by taoeffect** [comment]
/crush_fast {{openrouter, openai/gpt-5.4, google/gemini-3-flash-preview}}

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23263948043)._

**Comment by taoeffect** [comment]
/crush_fast {{openrouter, google/gemini-3.1-pro-preview, google/gemini-3-flash-preview}}



---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23264037597)._

**Comment by taoeffect** [comment]
Testing with the database (following second set of steps) after applying [the patch in your comment](https://github.com/okTurtles/group-income/pull/3058#issuecomment-4085151360):

> 5. User B logs in. They should 'see' the group but interacting with it will fail (also, they won't see messages posted by you after removing user C). They should now have sent a key request.

You didn't say it, but as step 6 says:

> 6. You log in. Now, you should respond to User B's key request.

I assume you forgot to say that before Step 5, you are supposed to quit the browser that your user is using (after step 4). So that's what I did.

Upon doing Step 6, both browsers (my user and the one with `userb`) started kinda wigging out. It was as if both of them started reloading the group from scratch.

This is what `userb` looked like for a bit:

Screenshot_20260320_101604

UserB also had several of these errors in the console:

> Ignoring OP_KEY_REQUEST because it is signed by the wrong contract

And approaching 1 million debug messages. At which point it seems the browser cleared the console and started logging messages from scratch.

Meanwhile, my user was similarly reloading things (except slower, in Firefox):

Screenshot_20260320_101702

It had a few of these errors too (I'm guessing `rootState` is `undefined` in this getter - this needs to be fixed too, could you have a look? I think I saw `userb` had this error too at various points in the console):

Screenshot_20260320_102105 copy

I wasn't able to test Step 7 with `userb` because the Group Income UI in Brave froze completely and was unresponsive.

I quit Brave and re-opened it. It appeared to again load the group from scratch and had these console errors:

image

Eventually I was able to post a message as `userb`. So I guess that's a good sign that the key sharing worked. It just seems really janky. After that it again went back to the loading the chatroom from scratch:

image

**Comment by corrideat** [comment]
Thank you for posting the results. I'm going to test this, but some of the poor performance can likely be explained by having the console open (but 20 minutes seems excessive). What's strange here is that your own user seemed to start re-syncing the group, which it had no reason to (user B did have to reload the group).

> I assume you forgot to say that before Step 5, you are supposed to quit the browser that your user is using (after step 4). So that's what I did.

Yeah, that's one way of doing it. I added step 4 after writing step 3, which says `(important: ensure the service worker is not running afterwards / that you have no active sessions)`. You don't really need to close the browser, closing the tab and uninstalling the SW would do (or logging out), but it's correct to do what you did.

File: frontend/controller/actions/chatroom.js [hunk 1]
```diff
@@ -257,37 +327,120 @@ export default (sbp('sbp/selectors/register', {
...
+    //     contracts will continue to show the old behaviour. This check refuses
+    //     those key rotations even if an old contract version is used.
+    // eslint-disable-next-line no-lone-blocks
+    {
+      // Check that it's the CEK that we're rotating
+      if (state._volatile?.pendingKeyRevocations?.[mainCEKid]) {
+        // Check that it's also the CSK that we're rotating
+        const mainCSKid = await sbp('chelonia/contract/currentKeyIdByName', state, 'csk', true)
+        if (mainCSKid && state._volatile.pendingKeyRevocations[mainCSKid]) {
+          const height = Math.max(state._vm.authorizedKeys[mainCEKid]._notBeforeHeight, state._vm.authorizedKeys[mainCSKid]._notBeforeHeight) || 0
```
Comment (taoeffect) [inline frontend/controller/actions/chatroom.js]: Could you add a comment explaining what this `height` is for? (Will help to determine whether this should be Math.max or Math.min)

File: frontend/controller/actions/chatroom.js [hunk 2]
```diff
@@ -257,37 +327,120 @@ export default (sbp('sbp/selectors/register', {
...
+          const formerMemberIds = Object.keys(state.members).filter((id) => {
+            return state.members[id].hasLeft === true
+          })
+          const hasAnyoneLeftAfterLastRotation = Object.keys(state._vm.authorizedKeys).some((id) => {
+            const key = state._vm.authorizedKeys[id]
+            return key._notAfterHeight >= height && formerMemberIds.some((memberId) => {
+              return key.name.startsWith(memberId)
+            })
+          })
```
Comment (taoeffect) [inline frontend/controller/actions/chatroom.js:393]: Need a comment here as the way it's written has a few assumptions:

1. It supposedly looking for the CSK, but this might not be the CSK if in the future other keys are added
2. Even if it's the CSK the CSK might rotate for other reasons (e.g. password change) that don't indicate they've left after rotation

File: frontend/controller/actions/group.js [hunk 3]
```diff
@@ -645,40 +722,123 @@ export default (sbp('sbp/selectors/register', {
...
+    //     contracts will continue to show the old behaviour. This check refuses
+    //     those key rotations even if an old contract version is used.
+    // eslint-disable-next-line no-lone-blocks
+    {
+      // Check that it's the CEK that we're rotating
+      if (state._volatile?.pendingKeyRevocations?.[mainCEKid]) {
+        // Check that it's also the CSK that we're rotating
+        const mainCSKid = await sbp('chelonia/contract/currentKeyIdByName', state, 'csk', true)
+        if (mainCSKid && state._volatile.pendingKeyRevocations[mainCSKid]) {
+          const height = Math.max(state._vm.authorizedKeys[mainCEKid]._notBeforeHeight, state._vm.authorizedKeys[mainCSKid]._notBeforeHeight) || 0
```
Comment (taoeffect) [inline frontend/controller/actions/group.js]: Same RFC here for what this `height` is supposed to represent

**Comment by taoeffect** [comment]
/crush_fast {{openrouter, google/gemini-3.1-pro-preview, google/gemini-3-flash-preview}}

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23456772763)._

**Comment by taoeffect** [comment]
/crush_fast {{openrouter, anthropic/claude-opus-4.6, google/gemini-3-flash-preview}}



---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23457099216)._

**Comment by taoeffect** [comment]
/crush_fast {{openrouter, anthropic/claude-opus-4.6, google/gemini-3-flash-preview}}


---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23457679229)._

**Review by taoeffect — APPROVED** [review]
Amazing work @corrideat!

Congratulations on getting this working! 🥳 🎉  👏 👏 👏 👏 👏
