### PR TITLE
#2241 - Bug-fix in invited-by tooltip

### LINKED ISSUE #2241: Show which user is responsible for giving invite link to proposal-accepted members
### Problem

The tooltip for pending users does not show which member is responsible for giving invite link to proposal-accepted members. 

This is the user that opened the proposal, who's responsible for giving the link:

addMember--inviteLinkInviterBlank--Inviter

This is another user in the group:

addMember—inviteLinkInviterBlank

### Solution

Fix so correct user is shown, even if said user doesn't have a displayName set.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #2241

### CODE REVIEW

File: frontend/views/containers/dashboard/GroupMembersTooltipPending.vue [hunk 1]
```diff
@@ -17,17 +17,25 @@ export default ({
...
-      'groupMembersPending'
+      'groupMembersPending',
+      'globalProfile'
     ]),
     tooltipText () {
-      const invitedBy = (this.groupMembersPending[this.username] || {}).invitedBy
+      const invitedBy = this.getDisplayName(this.data?.invitedBy)
 
-      return this.contractID === this.ourIdentityContractId
+      return this.ourIdentityContractId === this.data?.invitedBy
```
Comment (SebinSong) [inline frontend/views/containers/dashboard/GroupMembersTooltipPending.vue:37]: The existing logic here is apparently based on the legacy logic, causing the bug. So needs to be updated accordingly.

**Comment by SebinSong** [comment]
This PR is ready besides the group-chat heisen-bug

**Review by taoeffect — APPROVED** [review]
LGTM!
