### PR TITLE
Fix infinite loop on NEW_CHATROOM_UNREAD_POSITION

### LINKED ISSUE #2472: NEW_CHATROOM_UNREAD_POSITION event is emitted infinitely
### Problem

https://github.com/user-attachments/assets/f1b4c7a7-7a12-4a62-9131-34778f60dc7c

Sebin writes:

> NEW_CHATROOM_UNREAD_POSITION event is infinitely emitted once we scroll-up in the chatroom.
Investigated this for a few hours and it seems like there is an infinite loop created in sw-primary.js between okTurtles.events/on ([here](https://github.com/okTurtles/group-income/blob/df255f8ca92d0b5e7ad91749d5b4b0eb9d73115b/frontend/controller/serviceworkers/sw-primary.js#L85-L109)) and okTurtles.events/emit ([here](https://github.com/okTurtles/group-income/blob/df255f8ca92d0b5e7ad91749d5b4b0eb9d73115b/frontend/controller/serviceworkers/sw-primary.js#L244-L246))

### Solution

Fix.

### PR DESCRIPTION
**Pull request by corrideat**
Close #2472

### CODE REVIEW

File: frontend/controller/service-worker.js [hunk 1]
```diff
@@ -211,12 +211,18 @@ sbp('sbp/selectors/register', {
...
 
 // Events that need to be relayed to the SW
-;[LOGIN_COMPLETE, NEW_CHATROOM_UNREAD_POSITION, SET_APP_LOGS_FILTER].forEach((event) =>
+;[LOGIN_COMPLETE, SET_APP_LOGS_FILTER].forEach((event) =>
   sbp('okTurtles.events/on', event, (...data) => {
     navigator.serviceWorker.controller?.postMessage({ type: 'event', subtype: event, data })
   })
 )
 
+sbp('okTurtles.events/on', NEW_CHATROOM_UNREAD_POSITION, (obj: Object) => {
```
Comment (taoeffect) [inline frontend/controller/service-worker.js:220]: Is this the only event for which we have this infinite loop situation?

Comment (corrideat) [reply frontend/controller/service-worker.js:220]: I think so. It'd be the overlap of line 214 in `service-worker.js` and ll. 86-93 in `sw-primary.js`

**Review by SebinSong — APPROVED** [review]

**Review by taoeffect — APPROVED** [review]
Brilliant sir!

Works well! 👍
