### PR TITLE
Improve chat service & fix some more issues

### LINKED ISSUE #1374: Chat: do not refetch messages if not needed
### Problem

Currently, switching back and forth between the dashboard and the chat will cause the chat messages to be refetched from the server each time.

### Solution

Don't refetch messages if it's not needed.

### LINKED ISSUE #1507: Some chat issues in production server
### Problem

1. It makes error when try to create direct message.
2. In `General` chatroom, we should see the `Joined General` message (which is created automatically when a new member is joined the group). But we can not see them.

@taoeffect, described issues in detail here in Slack.
https://okturtles.slack.com/archives/C0EH7P20Y/p1677716969380129

### Solution

I am not sure what the reason is at this moment. Need to debug.

### LINKED ISSUE #1511: Incorrect title when route is changed in the channel which is not joined
### Problem

If the route is changed in the channel which is not part of, the title is set `'Loading'`.
Steps to Reproduce:
1. UserA creates a channel ChannelA
2. UserB views the ChannelA. Not yet joined and just view.
3. Click `+ New` button to create a new channel or click `Settings` button, so that a new modal would be opened and the route would be changed.
4. Check the title. It will display `'Loading'` which is wrong.

### Solution

Seems like the `refreshTitle` function in `ChatroomMixin.js` didn't catch all the cases.

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of Changes

1. Closes #1374 
2. Closes #1507 
3. Closes #1511

### CODE REVIEW

**Review by Silver-IT — COMMENTED** [review]
All seems to be ready for your review, @taoeffect

**Review by taoeffect — CHANGES_REQUESTED** [review]
@Silver-IT could you remove your changes related to #1371 from this PR? Please see this comment for more details: https://github.com/okTurtles/group-income/issues/1371#issuecomment-1458993957

Also, to make it easier for us to coordinate around PR reviews in the future, please try submit separate PRs for separate issues, especially if the issues are very different. This is part of the [contributing guidelines](https://github.com/okTurtles/group-income/blob/master/CONTRIBUTING.md#pull-request-requirements-exclamation):

> 1. A PR SHOULD be a minimal and accurate answer to exactly one identified and agreed problem.

It helps to speed up PR reviewing and merging for both contributors and maintainers. :)

**Comment by Silver-IT** [comment]
> Also, to make it easier for us to coordinate around PR reviews in the future, please try submit separate PRs for separate issues, especially if the issues are very different.

Got it. Will do from the next time.

File: frontend/model/contracts/mailbox.js [hunk 1]
```diff
@@ -63,7 +63,7 @@ sbp('chelonia/defineContract', {
     },
     'gi.contracts/mailbox/setAttributes': {
       validate: (data, { state, meta }) => {
-        if (state.attributes.creator !== meta.username) {
+        if (state.attributes && state.attributes.creator !== meta.username) {
```
Comment (taoeffect) [inline frontend/model/contracts/mailbox.js:66]: I am realizing that if `state.attributes` is not defined, we are calling `'gi.actions/mailbox/setAttributes'`, but that assumes `state.attributes` is defined.

So something like this needs to be added to the `process`:

```js
      process ({ meta, data }, { state }) {
        // TODO: remove this hack before releasing version 1
        if (!state.attributes) {
          Vue.set(state, 'attributes', {})
        }
```

File: frontend/views/containers/chatroom/ChatMain.vue [hunk 2]
```diff
@@ -402,13 +411,15 @@ export default ({
...
+      // NOTE: this state is rendered using the chatroom contract functions
+      // so should be CAREFUL of updating the fields
+      this.messageState.contract = {
         settings: cloneDeep(this.chatRoomSettings),
         attributes: cloneDeep(this.chatRoomAttributes),
         users: cloneDeep(this.chatRoomUsers),
-        messages: initialize ? [] : this.messages,
-        onlyRenderMessage: true
+        messages: [],
+        onlyRenderMessage: true // NOTE: DO NOT CHANGE THIS, OR CHATROOM COULD BREAK
```
Comment (taoeffect) [inline frontend/views/containers/chatroom/ChatMain.vue]: Recommend `CHANGE` => `RENAME` to be more specific

File: frontend/views/containers/chatroom/ChatMain.vue [hunk 3]
```diff
@@ -642,13 +680,41 @@ export default ({
...
+        // this.currentChatRoomId could be wrong when the channels are switched very fast
+        // so it's good to initiate using input parameter chatRoomId
+        sbp('gi.db/archive/save', this.getArchiveKeyFromChatRoomId(chatRoomId), JSON.stringify(this.latestEvents))
+      }
+    },
+    getArchiveKeyFromChatRoomId (chatRoomId) {
+      const curChatRoomId = chatRoomId || this.currentChatRoomId
+      return `messages/${curChatRoomId}`
+    },
+    refreshContent: debounce(function (from, to) {
```
Comment (taoeffect) [inline frontend/views/containers/chatroom/ChatMain.vue:718]: Below this I see a call to `setMessageEventListener`, which seems to set a lot of event listeners. But I don't see a corresponding `'okTurtles.events/off'` call for all of these:

```js
      if (force) {
        sbp('okTurtles.events/on', `${CHATROOM_MESSAGE_ACTION}-${to || this.currentChatRoomId}`, this.listenChatRoomActions)
      } else if (this.isJoinedChatRoom(to)) {
        sbp('okTurtles.events/on', `${CHATROOM_MESSAGE_ACTION}-${to}`, this.listenChatRoomActions)
      }
```

This seems like something I didn't catch in a previous PR review.

File: frontend/model/contracts/mailbox.js (hunk 1 above)
Comment (Silver-IT) [reply frontend/model/contracts/mailbox.js:66]: That's a nice catch. Correct.

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 2 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue]: Got it.

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 3 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue:718]: I think we remove the event listeners in these two places by calling `sbp('okTurtles.events/off')`.
1. In `beforeDestroy` life cycle
2. in `setMessageEventListener` function

Comment (taoeffect) [reply frontend/views/containers/chatroom/ChatMain.vue:718]: Hmm, you're right. I didn't understand that `setMessageEventListener` properly handled this

File: frontend/controller/actions/identity.js [hunk 4]
```diff
@@ -228,7 +228,6 @@ export default (sbp('sbp/selectors/register', {
     } catch (e) {
       console.error('gi.actions/identity/login failed!', e)
       const humanErr = L('Failed to login: {reportError}', LError(e))
-      alert(humanErr)
```
Comment (taoeffect) [inline frontend/controller/actions/identity.js]: I think this should be added back. Seems related to changes to #1371

File: frontend/views/containers/chatroom/ChatMain.vue [hunk 5]
```diff
@@ -283,7 +292,7 @@ export default ({
           prepublish: (message) => {
             const msgValue = JSON.parse(message.opValue())
             const { meta, data } = msgValue
-            this.messages.push({
+            this.messageState.contract.messages.push({
```
Comment (taoeffect) [inline frontend/views/containers/chatroom/ChatMain.vue:294]: Regarding issue #1503 and the comment below, you could instead rename this handler from `prepublish` to `postpublish`. Then it would be safe to use `message.hash()` safely as the identifier.

Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue:294]: Yeah. It's a nice solution in terms of comparing GIMessages.
On the other hand, the pending could work a bit weird, if we add the pending message in `postpublish`.
Because the message won't be added immediately after users press `Enter`.

What do you recommend?
1. Keep it in `prepublish` and update later
2. Move it to `postpublish` and update later

File: frontend/controller/actions/identity.js (hunk 4 above)
Comment (Silver-IT) [reply frontend/controller/actions/identity.js]: Yeah, I know. But in my experience, this `alert` isn't needed. Because we log that `humanErr` in `main.js` exception handler.

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 5 above)
Comment (taoeffect) [reply frontend/views/containers/chatroom/ChatMain.vue:294]: I think we should for now put it in `postpublish`, because at least will avoid weird bugs that would be caused by the `messageId` being wrong

Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue:294]: Sometimes the `sbp('okTurtles.events/once', hash, () => {...})` is called before the `postpublish`. So one event can add two messages if we add pending message in `postpublish`.
I think we should keep it here in `prepublish` and fix the Issue #1503 and then update again.

Comment (taoeffect) [reply frontend/views/containers/chatroom/ChatMain.vue:294]: Oh, weird. OK 👍

Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue:294]: Thanks

File: frontend/views/containers/chatroom/ChatMain.vue [hunk 6]
```diff
@@ -531,9 +564,9 @@ export default ({
       }
 
       sbp('okTurtles.events/once', hash, async (contractID, message) => {
-        if (contractID === this.currentChatRoomId) {
-          const state = this.getSimulatedState(false)
-          await sbp('chelonia/private/in/processMessage', message, state)
+        // NOTE: while syncing the chatroom contract, we should ignore all the events
```
Comment (taoeffect) [inline frontend/views/containers/chatroom/ChatMain.vue:578]: I don't quite understand this `sbp('okTurtles.events/once', hash` event listener.

This function, `listenChatRoomActions`, will be called by `emitMessageEvent` in the `sideEffect`. `emitMessageEvent` could easily pass in `contractID` along with `hash`. I do not see a reason for immediately setting up an event listener here on `hash`, because it will simply be immediately called after the side effect in `handleEvent`: `sbp('okTurtles.events/emit', hash, contractID, message)`

What I'm saying is, I'm pretty sure you can remove `sbp('okTurtles.events/once', hash, async (contractID, message) => {`, and place the code inside of it into this function directly, right? (as long as you modify `emitMessageEvent` to pass along the `contractID` too)

File: frontend/views/containers/chatroom/ChatMain.vue [hunk 7]
```diff
@@ -642,13 +680,41 @@ export default ({
...
+      }
+      const unit = this.chatRoomSettings?.actionsPerPage || CHATROOM_ACTIONS_PER_PAGE
+      const from = this.latestEvents.length ? GIMessage.deserialize(this.latestEvents[0]).hash() : null
+      const to = this.latestEvents.length
+        ? GIMessage.deserialize(this.latestEvents[this.latestEvents.length - 1]).hash()
+        : null
+
+      // NOTE: save messages in the browser storage, but not more than 3 pages of events
+      if (this.latestEvents.length >= 3 * unit) {
+        sbp('gi.db/archive/delete', this.getArchiveKeyFromChatRoomId(chatRoomId))
```
Comment (taoeffect) [inline frontend/views/containers/chatroom/ChatMain.vue:707]: The way these messages are deleted doesn't make much sense to me.

Instead of keeping the number of stored events limited to `3 * unit`, this just deletes all of these events. But when then will it save the events again?

 This just doesn't seem right to me.

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 6 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue:578]: That's reasonable. The reasons why I made this way are because
1. I wanted to use `message` object in the function
2. As long as `listenChatRoomActions` is sync, there won't be any issues because `okTurtles.events/emit` is defined just like the following.
```
'okTurtles.events/emit': function (event: string, ...data: any) {
  for (const listener of sbp('okTurtles.data/get', listenKey(event)) || []) {
    listener(...data)
  }
}
```

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 7 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue:707]: 1. I need to define the constant value for the number 3. (Not sure 3 is the best choice. It could be 5 or any other)
2. Do you remember `MAX_ARCHIVED_PERIODS` which we use in group contract? We archive payments but no more than `MAX_ARCHIVED_PERIODS` periods of payments. Here, it works the same too. We are not going to save more than 3 pages of events for each channel. The events are always saved to the IndexedDB unless the loaded events are for more than 3 pages or user didn't load any events(old or new) after he opens the page.

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 6 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue:578]: If I remove that event handler `sbp('okTurtles.events/once', hash)`, I am not sure how I can get the `message` object in `listenChatRoomActions` function.

Comment (taoeffect) [reply frontend/views/containers/chatroom/ChatMain.vue:578]: Oh! Good point! Can you add this comment above line 569?

```js
// we use this listener here so that we can get access to the GIMessage
// it will be called immediately after this function is called
```

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 7 above)
Comment (taoeffect) [reply frontend/views/containers/chatroom/ChatMain.vue:707]: OK, I cannot follow everything you're doing here. However, there is an easy way to make sure everything works correctly: make it easy to detect bugs.

So, please for now set `CHATROOM_MAX_ARCHIVE_ACTION_PAGES` to `2`. This way, if there's a bug in the archiving code, we will catch it earlier. Then later we can set it back to `3` after we're sure that everything is working OK.

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 6 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue:578]: Sure. Can I make this comment a bit more informative like the following?

```
// we use this listener here so that we can get access to the GIMessage
// it will be called immediately after this function is called as long as listenChatRoomActions function is sync
```

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 7 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue:707]: Okay. I will set `CHATROOM_MAX_ARCHIVE_ACTION_PAGES` to `2` then.

**Review by taoeffect — CHANGES_REQUESTED** [review]
With even 1 user, when I switch between the Chat to the Dashboard and back, there are calls to `'chelonia/out/eventsBetween'` and `'chelonia/out/eventsBefore'`:


Screen Shot 2023-03-09 at 3 34 20 PM

Screen Shot 2023-03-09 at 3 34 30 PM

If this PR closed the issue, these calls shouldn't happen each time I switch between the Chat <-> Dashboard.

**Comment by Silver-IT** [comment]
Yeah. Nice catch. I will explain the reason why those two `sbp` calls are made.
**eventsBetween**: Every time we enter the chatroom, we should check if the locally stored messages are up-to-date. So we call `eventsBetween` between the `latestHash` and the `lastHash from the store`. But you pointed the important thing. Since they are same, it shouldn't be called in this situation. I think I handled this but there might be a mistake.
**eventsBefore**: We need to display at least one page of messages. I guess there were a few messages when you tested. So it tried to get more messages to fill the page (at least one page).

**Review by Silver-IT — COMMENTED** [review]
@taoeffect, It's ready for you to re-review.

**Review by Silver-IT — COMMENTED** [review]
It seems ready for the final review.

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 6 above)
Comment (taoeffect) [reply frontend/views/containers/chatroom/ChatMain.vue:578]: Yep! Of course, more informative is always better. :)

Although, that last part might have a typo:

>  as long as listenChatRoomActions function is sync

Did you mean "is syncing"? or "is synced"? Or what?

Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue:578]: `as long as listenChatRoomActions is sync function`. I will update the comment.

File: frontend/controller/actions/identity.js (hunk 4 above)
Comment (taoeffect) [reply frontend/controller/actions/identity.js]: @Silver-IT but I think we want the user to see the error in this case, because it's a serious problem that would need manual intervention to solve, and this way if anyone runs into it they'll be able to take a screenshot of the error and we'll know. Most normal users don't check the console.

Comment (Silver-IT) [reply frontend/controller/actions/identity.js]: Yeah, that's reasonable. Then, let's add it again.

File: frontend/model/contracts/chatroom.js [hunk 8]
```diff
@@ -224,10 +225,7 @@ sbp('chelonia/defineContract', {
       },
       sideEffect ({ contractID, hash, meta }) {
         emitMessageEvent({ contractID, hash })
-
-        if (sbp('chelonia/contract/isSyncing', contractID)) {
-          updateUnreadPosition({ contractID, hash, createdDate: meta.createdDate })
-        }
+        updateUnreadPosition({ contractID, hash, createdDate: meta.createdDate })
```
Comment (taoeffect) [inline frontend/model/contracts/chatroom.js:228]: So the logic here completely reversed. Before, if it was called from a contract sync, we would update the unread position. Now, it no longer does.

Is this change intentional?

(Same question for the line above on line 208)

Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js:228]: Nice catch. Actually, I didn't notice that it reverses the previous workflow.
But the problem is that I can't understand the previous workflow to set `UnreadPosition` while the chatroom contract is syncing.
It makes sense to set `UnreadPosition` after joining the chatroom. So no need to set `UnreadPosition` while syncing the contract and the current solution is correct.

**Review by Silver-IT — COMMENTED** [review]
Resolved your feedback.

**Review by taoeffect — APPROVED** [review]
Nice improvements @Silver-IT, well done!
