### PR TITLE
Fixed janky login issues (Closes #1267) + more

### LINKED ISSUE #1267: Login still a little janky
### Problem

In my tests, logging in in a private window to the server had two issues:

1. The "loading events" banner would stay there for too long for some reason. A page refresh would fix the issue.
2. The dashboard wasn't shown and the current group wouldn't be set. I'm fairly sure this is due to (1) not completing for whatever reason. However, there should still be some sanity check after the page refresh.

Screen Shot 2022-05-04 at 4 18 59 PM

### Solution

Identify and fix.

Likely also implement a limit for `eventsSince` and call it multiple times as needed.

### PR DESCRIPTION
**Pull request by taoeffect**
+ Fixed janky login issues (Closes #1267)
  + Modified the sideEffect for `'gi.contracts/identity/setLoginState'`, @corrideat have a look as it relates to stuff you've been working on
+ Added `'chelonia/queueInvocation'` (copy of `'okTurtles.eventQueue/queueEvent'`)

### CODE REVIEW

**Review by snowteamer — APPROVED** [review]
I didn't catch any problems. Approved.

File: frontend/model/contracts/group.js [hunk 1]
```diff
@@ -701,7 +701,7 @@ sbp('chelonia/defineContract', {
           // we were getting the same latestHash upon re-logging in for test "user2 rejoins groupA".
           // We add it to the same queue as '/remove' above gets run on so that it is run after
           // contractID is removed. See also comments in 'gi.actions/identity/login'.
-          sbp('okTurtles.eventQueue/queueEvent', contractID, ['gi.actions/identity/saveOurLoginState'])
+          sbp('chelonia/queueInvocation', contractID, ['gi.actions/identity/saveOurLoginState'])
```
Comment (corrideat) [inline frontend/model/contracts/group.js:704]: I've made this selector in my PR as well. Since this is likely going to be merged first, I can merge your changes into my branch once this goes through.

**Review by corrideat — APPROVED** [review]
