### PR TITLE
Fix manifest not found error upon contract file change

### LINKED ISSUE #1692: Manifest not found error upon contract file change in development
### Problem

A 404 Not Found error related to chelonia/private/loadManifest sometimes occurs after saving a contract file change in development, and the page is either blank or an alert saying "contract sync error" pops up.

#### Steps to reproduce:
- Run `grunt dev` without persistence enabled, i.e. `GI_PERSIST` should not be set
- Open the app in the browser
- Create an user account
- Save a change to e.g. `group.js`. The change must result in a new version of the file, and must not match any previous version of it, so that a new manifest is generated.
- When the app reloads, the page stays blank and the following error shows up:
image

Manually reloading a second time doesn't help, only rebuilding the app does.

### Solution

 `manifest.json` is automatically updated on contract file change, but maybe contracts are not re-deployed accordingly.

### PR DESCRIPTION
**Pull request by snowteamer**
Closes #1692

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -1,5 +1,7 @@
 'use strict'
 
+if (process.env.CI) process.exit(1)
+
```
Comment (taoeffect) [inline Gruntfile.js]: If this isn't a WIP this can be removed?

File: Gruntfile.js [hunk 2]
```diff
@@ -136,11 +138,38 @@ module.exports = (grunt) => {
...
   }
 
+  async function redeployAndUpdateMainSrc (manifestDir) {
+    if (development) {
+      const { API_URL, GI_PERSIST } = process.env
+      const { dirname, filename } = databaseOptionBags[GI_PERSIST] ?? {}
+      let dest = './data'
+      if (GI_PERSIST === 'sqlite') dest = path.join(dirname, filename)
+      if (GI_PERSIST === 'fs') dest = dirname
+      if (!GI_PERSIST) dest = API_URL
```
Comment (taoeffect) [inline Gruntfile.js]: AFAICT, this code can be simplified significantly.

1. We can start by setting `let dest = API_URL`. This eliminates the need for line 148
2. Next, since the variables `dirname` and `filename` are never used for anything except to set `dest`, we can further simplify by directly retrieving the full path from `databaseOptionBags` and having it there. This eliminates the need for lines 146 and 147

File: Gruntfile.js [hunk 3]
```diff
@@ -136,11 +138,38 @@ module.exports = (grunt) => {
...
+      grunt.log.writeln(chalk.underline(`Running 'chel deploy to ${dest}'`))
+      const { stdout } = await execWithErrMsg(`./node_modules/.bin/chel deploy ${dest} ${manifestDir}/*.manifest.json`, 'error redeploying contracts')
+      console.log(stdout)
+      const r = /contracts\/([^.]+)\.(?:x|[\d.]+)\.manifest.*\/(.*)/g
+      const manifests = Object.fromEntries(Array.from(stdout.replace(/\\/g, '/').matchAll(r), x => [`gi.contracts/${x[1]}`, x[2]]))
+      await writeFile(manifestJSON, JSON.stringify({ manifests }, null, 2) + '\n')
```
Comment (taoeffect) [inline Gruntfile.js]: This entire section appears to be repeated? If so then can you please place it in a function to DRY it with `deployAndUpdateMainSrc`? Or, alternatively (perhaps even better), merge the two functions into 1 function and pass in a parameter to distinguish behavior.

**Review by taoeffect — CHANGES_REQUESTED** [review]
Review ready!

File: Gruntfile.js (hunk 3 above)
Comment (snowteamer) [reply Gruntfile.js]: Yea, that's the code duplication I was talking about on Slack

**Review by taoeffect — APPROVED** [review]
Beautifully done @snowteamer! 👏
