### PR TITLE
Fix error in Joining group

### LINKED ISSUE #1575: Duplicate notifications when someone joins on both desktop and mobile
### Problem

When someone joins first on desktop, and then logs in on mobile, I got this duplicate notification.

Screen Shot 2023-05-04 at 9 19 18 PM

I also got the duplicate notification on my mobile device (where I was also logged in).

### Solution

Find and fix the problem.

### LINKED ISSUE #1579: Member loses their income details after logging in on mobile??
### Problem

A member logged into a group on desktop, entered their income details successfully and saved them.

They then logged in on the mobile device, and suddenly their income details were gone!

The messages this user sent to the database after updating their income details the first time included `'gi.contracts/group/inviteAccept'` (presumably from the mobile device), `'gi.contracts/group/joinChatRoom'` and `'gi.contracts/group/updateLastLoggedIn'`.

### Solution

Figure out why their income details got wiped. Keep in mind that during this time other users might have logged in as well and performed similar actions.

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of Changes

- Closes #1575 
- Closes #1579

### CODE REVIEW

File: frontend/model/contracts/group.js [hunk 1]
```diff
@@ -995,10 +995,14 @@ sbp('chelonia/defineContract', {
...
-        //       rejoin the group. All of their past posts will be re-associated with
-        //       them upon re-joining.
+        // NOTE: ensure `meta.username` is unique for the lifetime of the username
+        //       since we are making it possible for the same username to leave and rejoin the group.
+        //       All of their past posts will be re-associated with them upon re-joining.
+        const profile = state.profiles[meta.username]
+        if (profile && profile.status !== PROFILE_STATUS.REMOVED) {
+          console.error(`inviteAccept: ${meta.username} is currently active member in the group`)
+          throw new Errors.GIErrorIgnoreAndBan(`${meta.username} is already joined and active in the group`)
+        }
```
Comment (taoeffect) [inline frontend/model/contracts/group.js]: Nice job @Silver-IT considering this. However, I'm worried that this might get some members banned unintentionally if we make a mistake in the code...

For example, we could add additional statuses and forget to update other code, or they could be in `PENDING` status... or something else.

The thing is, once the `e2e-protocol` is implemented properly, that should take care of ensuring that all messages are sent by who they claim to be sent by. So do you think you can remove these updates?

Comment (taoeffect) [reply frontend/model/contracts/group.js]: OK, I see that this change is related to #1579. And indeed you are correct that calling `inviteAccept` twice is what resulted in the profile being reset (because the invite link was used twice).

I was able to track this down by using @snowteamer's `chel eventsSince` PR: https://github.com/okTurtles/chel/pull/9

For reference (for myself and others), this is the command on how to show all of the actions from the user `andrea` in the group:

```
chel eventsSince --limit 1000 groupincome.db 21XWnNWZzYYPfezAq9HN85b4by9TWt3o5GPUVzw9baSVjeQ49w 21XWnNWZzYYPfezAq9HN85b4by9TWt3o5GPUVzw9baSVjeQ49w | jq '.[] | select(.op[0] == "ae") | .op[1] | fromjson | select(.meta.username == "andrea")'
```

So, we still need to change this code because we don't want to ban Andrea for clicking the invite link twice. :P

Instead, if we are an existing user in the group, can we simply skip running the next line?

Comment (Silver-IT) [reply frontend/model/contracts/group.js]: @taoeffect, I have just removed that change in `group.js` contract file considering your opinion and one more reason that I think this can't be reached since it's prehandled in `Join.vue` page.

But to be honest, I am not 100% sure `it can't be reached` **at the moment**.
The meaning of **at the moment** is that I can say 100% only after we update the workflows of `Login`, `Join Group`, ... and resolve Issue #1334.

**Review by taoeffect — CHANGES_REQUESTED** [review]
@Silver-IT The way `Join.vue` is written, especially how `mounted` calls `initialize`, is very important, and changing it can cause Cypress tests to break or introduce heisenbugs.

So I investigated this more deeply and found out that fixing these issues can be done with a 1-line change.

Change:

```pug
        login-form(v-else :postSubmit='accept')
```

To:

```pug
        login-form(v-else :postSubmit='goHome')
```

Alternatively, you can create a `goDashboard` function to directly go to the `/dashboard` (this would be better IMO).

**Comment by Silver-IT** [comment]
@taoeffect, actually we can not set `postSubmit` of `Login` form to `goHome` as constant. That's because users should join the group after he logs in when he hasn't joined **this group**(the group that the invite link indicates to) yet. So after login,
- We should let users join the group if they have **not** already joined **this group**.
- We should let users go `Dashboard` page if they have already joined **this group**.

And `accept` action is not being called inside the `Login` or `SignUp` form. It's called by these codes.
```
if (!syncFinished) {
  this.pageStatus = 'SIGNING'
  sbp('okTurtles.events/once', LOGIN, () => this.accept())
} else {
  this.accept()
}
```
So, actually we don't need to take care of calling `accept` function in `postSubmit` of two forms.

The main reason I added `postSubmit` to the `Login` and `SignUp` forms is that it was weird when the spinner didn't spin even though `Submit` action was in progress. We used `ButtonSubmit` component in both forms and the spinner of `ButtonSubmit` component should spin and not disappear until the `Submit` action would be finished.
In `Login` and `SignUp` form inside `Join` page, the `Submit` action is not only `Login` or `SignUp` but also `Joining group`. So the spinner should spin until the user finishes joining the group.

**Review by taoeffect — CHANGES_REQUESTED** [review]
Ah, ok you're right that we should join the group after login if the user has not already joined the group.

So please send a minimal PR that does that. The only file that needs to be modified is `Join.vue`, and the only function that needs to be modified is `accept` - add a check to see if `groupId` already exists: `this.$store.state.contracts[groupId]`, and if so proceed to the dashboard instead of calling `'gi.actions/group/joinAndSwitch'`.

**Review by Silver-IT — COMMENTED** [review]
@taoeffect, I have reviewed this PR and no improvements needed I think.

File: frontend/views/pages/Join.vue [hunk 2]
```diff
@@ -97,23 +97,11 @@ export default ({
...
-      this.initialize()
-    } else {
-      sbp('okTurtles.events/once', LOGIN, () => this.initialize())
-    }
+    this.initialize()
   },
   methods: {
     async initialize () {
       try {
-        if (this.ourUsername) {
```
Comment (Silver-IT) [inline frontend/views/pages/Join.vue:109]: This doesn't mean `Login` is finished. We can not say he is part of the group (or not) before he finishes to login and completes to sync the contract.

File: frontend/views/pages/Join.vue [hunk 3]
```diff
@@ -97,23 +97,11 @@ export default ({
   mounted () {
     // For some reason in some Cypress tests it loses the route query when initialized is called
     this.ephemeral.query = this.$route.query
-    if (syncFinished || !this.ourUsername) {
```
Comment (Silver-IT) [inline frontend/views/pages/Join.vue]: Why should we take care of `this.ourUsername`? To say if he is logged in?
Even though `this.ourUsername` has its value and isn't **undefined**, the user could be in progress to log in and to sync contracts.

File: frontend/views/pages/Join.vue [hunk 4]
```diff
@@ -97,23 +97,11 @@ export default ({
...
-      this.initialize()
-    } else {
-      sbp('okTurtles.events/once', LOGIN, () => this.initialize())
-    }
```
Comment (Silver-IT) [inline frontend/views/pages/Join.vue]: We don't need to wait validating the invitation link until the user finishes login, since we always do validation no matter he has logged in or not. We can immediately validate if he opens this link.

File: frontend/views/pages/Join.vue [hunk 5]
```diff
@@ -97,23 +97,11 @@ export default ({
...
+    this.initialize()
   },
   methods: {
     async initialize () {
       try {
-        if (this.ourUsername) {
-          if (this.currentGroupId && this.$store.state.contracts[this.ephemeral.query.groupId]) {
-            this.$router.push({ path: '/dashboard' })
-          } else {
-            await this.accept()
```
Comment (Silver-IT) [inline frontend/views/pages/Join.vue:113]: We shouldn't call this `accept` function **here** for the following two reasons.

- The link is not yet validated
- At this time, we can not say the user is not part of this group. Because he could be in progress to log in and to sync contracts.

File: frontend/views/pages/Join.vue [hunk 6]
```diff
@@ -149,7 +137,13 @@ export default ({
...
           message
         }
-        this.pageStatus = 'SIGNING'
+
+        if (!syncFinished) {
+          this.pageStatus = 'SIGNING'
+          sbp('okTurtles.events/once', LOGIN, () => this.accept())
+        } else {
+          this.accept()
+        }
```
Comment (Silver-IT) [inline frontend/views/pages/Join.vue]: `accept` function should be called once only when the validation is passed and also the user finishes logging in.

File: frontend/views/pages/Join.vue [hunk 7]
```diff
@@ -149,7 +137,13 @@ export default ({
           creatorPicture,
           message
         }
-        this.pageStatus = 'SIGNING'
```
Comment (Silver-IT) [inline frontend/views/pages/Join.vue]: No need to set `this.pageStatus = 'SIGNING'`. We should only set this when the user is not logged in.
So replace this to the next line below inside the `if` statement.

File: frontend/views/pages/Join.vue [hunk 8]
```diff
@@ -163,10 +157,13 @@ export default ({
       this.$router.push({ path: '/' })
     },
     async accept () {
+      this.pageStatus = 'LOADING'
```
Comment (Silver-IT) [inline frontend/views/pages/Join.vue]: This line should be removed. I will remove this soon.

File: frontend/views/pages/Join.vue [hunk 9]
```diff
@@ -163,10 +157,13 @@ export default ({
...
       this.ephemeral.errorMsg = null
+      const { groupId, secret } = this.ephemeral.query
+      if (this.currentGroupId && this.$store.state.contracts[groupId]) {
+        return this.$router.push({ path: '/dashboard' })
+      }
```
Comment (Silver-IT) [inline frontend/views/pages/Join.vue]: This is for checking if the user is joined the group or not.

File: frontend/views/pages/Join.vue [hunk 10]
```diff
@@ -176,7 +173,14 @@ export default ({
...
         this.ephemeral.errorMsg = e.message
         this.pageStatus = 'INVALID'
+      } finally {
+        sbp('okTurtles.events/emit', JOIN_GROUP)
       }
+    },
+    acceptPostEffect () {
+      return new Promise(resolve => {
+        sbp('okTurtles.events/once', JOIN_GROUP, resolve)
+      })
```
Comment (Silver-IT) [inline frontend/views/pages/Join.vue]: `accpetPostEffect` is for waiting until the user finishes joining group.
If we use `accept` function in the `postSubmit`, the `accept` function would be called twice.

As we can see in `initialize` function, `accept` function is called after the user finishes logging in.
Users could log in by clicking `Sign Up` or `Login` button. So if we call `accept` function in `postSubmit` of those two forms, it will be called twice; once inside `initialize`, once in `postSubmit`.

**Review by Silver-IT — COMMENTED** [review]
@taoeffect, I have described what they do in detail. Need your replies. Thanks

File: frontend/views/pages/Join.vue (hunk 2 above)
Comment (taoeffect) [reply frontend/views/pages/Join.vue:109]: If `this.ourUsername` is defined it does mean login has finished.

That is what this code in `mounted` does:

```js
    if (syncFinished || !this.ourUsername) {
      this.initialize()
    } else {
      sbp('okTurtles.events/once', LOGIN, () => this.initialize())
    }
```

File: frontend/views/pages/Join.vue (hunk 3 above)
Comment (taoeffect) [reply frontend/views/pages/Join.vue]: This code from `main.js` is run before `mounted` gets called:

```js
await sbp('gi.actions/identity/login', { username })
```

So if `this.ourUsername` is not defined, it means the user is not logged in, and won't be logged in when `mounted` is called.

File: frontend/views/pages/Join.vue (hunk 2 above)
Comment (Silver-IT) [reply frontend/views/pages/Join.vue:109]: Yes. It's correct for the previous `mounted` code, but not for the new `mounted` code.

File: frontend/views/pages/Join.vue (hunk 3 above)
Comment (Silver-IT) [reply frontend/views/pages/Join.vue]: That's correct. However, the whole `if-else` state isn't needed I think.

File: frontend/views/pages/Join.vue (hunk 4 above)
Comment (taoeffect) [reply frontend/views/pages/Join.vue]: Then you can re-arrange the code so that it looks like this:

```js
    async initialize () {
      try {
        const state = await sbp('chelonia/latestContractState', this.ephemeral.query.groupId)
        const invite = state.invites[this.ephemeral.query.secret]
        if (!invite || invite.status !== INVITE_STATUS.VALID) {
          console.error('Join.vue error: Link is not valid.')
          this.ephemeral.errorMsg = L('You should ask for a new one. Sorry about that!')
          this.pageStatus = 'INVALID'
          return
        } else if (invite.expires < Date.now()) {
          console.log('Join.vue error: Link is already expired.')
          this.ephemeral.errorMsg = L('You should ask for a new one. Sorry about that!')
          this.pageStatus = 'EXPIRED'
          return
        }
        if (this.ourUsername) {
          if (this.currentGroupId && this.$store.state.contracts[this.ephemeral.query.groupId]) {
            this.$router.push({ path: '/dashboard' })
          } else {
            await this.accept()
          }
          return
        }
```

File: frontend/views/pages/Join.vue (hunk 5 above)
Comment (taoeffect) [reply frontend/views/pages/Join.vue:113]: See my comment above: https://github.com/okTurtles/group-income/pull/1603#discussion_r1206179653

File: frontend/views/pages/Join.vue (hunk 6 above)
Comment (taoeffect) [reply frontend/views/pages/Join.vue]: See my comment above: https://github.com/okTurtles/group-income/pull/1603#discussion_r1206179653

File: frontend/views/pages/Join.vue (hunk 7 above)
Comment (taoeffect) [reply frontend/views/pages/Join.vue]: With the code like this https://github.com/okTurtles/group-income/pull/1603#discussion_r1206179653

Then it makes sense to have this.

**Review by Silver-IT — COMMENTED** [review]
@taoeffect, ready for your FINAL review. :)

**Review by taoeffect — APPROVED** [review]
Approved! Nicely done @Silver-IT 👍
