### PR TITLE
#2201 - Incorrect poll expiration

### LINKED ISSUE #2201: Polls automatically close far too soon
### Problem

On the `testing` server, 1-_day_ polls are closing within approximately 1 _minute_.

pollClosed

It does not seem to make any difference what kind of poll is created or whether anyone votes. 

### Solution

Ensure polls are open for the correct duration.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #2201 

cc. @dotmacro

### CODE REVIEW

File: frontend/views/containers/chatroom/MessagePoll.vue [hunk 1]
```diff
@@ -116,7 +116,7 @@ export default ({
       }
 
       const checkAndSetTimer = () => {
-        if (Date.now() - this.pollData.expires_date_ms) {
+        if (Date.now() - this.pollData.expires_date_ms >= 0) {
```
Comment (SebinSong) [inline frontend/views/containers/chatroom/MessagePoll.vue:119]: When poll is not expired yet, this calculation evaluates to `-` value which is `truthy`. So adding `>= 0` for the bug-fix.

And this issue could only be observed for `1 Day` duration poll because, this periodic check only gets executed if the expiration happens in 24 hrs.

**Review by taoeffect — APPROVED** [review]
