### PR TITLE
Fix styling issue of more options menu

### LINKED ISSUE #2234: Ensure "more options" menu in chat is visible when opened
### Problem

If a chat message is too close to the top of the visible chat history, the "more options" menu in chat is hidden (in whole or in part) when the user clicks on it.

chatMoreOptionsHidden

### Solution

The "more options" menu should be visible when opened. If it won't be visible if opened above `⋯`, then it should be opened below `⋯` instead.

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of Changes

- Closes #2234

### CODE REVIEW

**Review by Silver-IT — COMMENTED** [review]
Ready for the review!

File: frontend/views/containers/chatroom/MessageActions.vue [hunk 1]
```diff
@@ -130,6 +133,27 @@ import { MenuParent, MenuTrigger, MenuContent, MenuItem } from '@components/menu
...
+  }, {
+    name: 'Unpin from channel',
+    conditionToShow: this.isAlreadyPinned
+  }, {
+    name: 'Delete message',
+    conditionToShow: this.isDeletable
+  }]
+
+  return moreOptions.filter(option => option.conditionToShow)
+}
```
Comment (taoeffect) [inline frontend/views/containers/chatroom/MessageActions.vue]: This is a cool idea 👍 

One thing though: remember all user-facing strings should be wrapped in either `L` function or `i18n`. Here the `L` function would be needed.

**Review by taoeffect — CHANGES_REQUESTED** [review]
Nice work @Silver-IT!

I'm not understanding why there is duplication of the menu items in the markup (HTML) and in the code (`getAvailableMoreOptions`).

Also found one issue.

**Comment by SebinSong** [comment]
Great fix @Silver-IT .

calculating available space is tall enough for menu is a good idea and seems to work well too.
One thing I observed is, depending on the viewport width, the height of each menu item becomes different. (e.g. in below layout, the menu is `54px` tall whereas the calculation is based on the assumption that it's always `36px`). Could you enhance the calculation to take this into account?

image

File: frontend/views/containers/chatroom/MessageActions.vue (hunk 1 above)
Comment (SebinSong) [reply frontend/views/containers/chatroom/MessageActions.vue]: @Silver-IT Agree this is a tidy solution. Since all `this.something` here look like the component props, I think this list can be stored as a computed prop instead, so that `conditionToShow` here are evaluated one time and cached.

Comment (Silver-IT) [reply frontend/views/containers/chatroom/MessageActions.vue]: The function `getAvailableMoreOptions` was not used in HTML, so I didn't wrapped name with `L`. 
But I will make computed value `moreOptions` (instead of `getAvailableMoreOptions`) and will wrap `name` with `L` and use it in HTML and `moreOptionsTriggered` function too.
That will fix the DRY too.

**Review by SebinSong — DISMISSED** [review]
Great work @Silver-IT

**Review by taoeffect — APPROVED** [review]
Nice job 👍
