### PR TITLE
#1632 Fix 'see original proposal' menu in Group-settings page

### LINKED ISSUE #1632: Non-functional "See original proposal" menu, also missing on mobile
### Problem

When a proposal to invite someone passes, for example for user "test", we see a "See Original Proposal" link on desktop in the invitation table in the group settings:

Screen Shot 2023-06-02 at 5 59 34 PM

However:

1. This menu doesn't work
2. And it's not visible on mobile:

Screen Shot 2023-06-02 at 5 59 25 PM

### Solution

Either make the menu work (by pulling up the archived proposals modal and scrolling to the specific row) and visible on mobile, or remove it. Better if you can get it to work though.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #1632

### CODE REVIEW

File: frontend/views/containers/group-settings/InvitationsTable.vue [hunk 1]
```diff
@@ -279,8 +287,21 @@ export default ({
...
-      console.log(inviteItem, 'TODO - See Original Proposal')
+    async handleSeeOriginal ({ invitee }) {
+      const key = `proposals/${this.ourUsername}/${this.currentGroupId}`
+      const archivedProposals = await sbp('gi.db/archive/load', key) || []
+      const proposalItemExists = archivedProposals.length > 0 || archivedProposals.some(entry => {
+        const { data } = entry[1]
+
+        return data.proposalType === PROPOSAL_INVITE_MEMBER &&
+          data.proposalData.member === invitee
+      })
```
Comment (Silver-IT) [inline frontend/views/containers/group-settings/InvitationsTable.vue]: Since there is no validation in invitee `Full name`, I think checking existence using `inviteSecret` is more reasonable.
You can just add to check `inviteSecret` in line #298.

**Review by Silver-IT — CHANGES_REQUESTED** [review]
@SebinSong, nice work. Just added one comment.

File: frontend/views/containers/group-settings/InvitationsTable.vue (hunk 1 above)
Comment (SebinSong) [reply frontend/views/containers/group-settings/InvitationsTable.vue]: @Silver-IT I'm not entirely sure what you meant by 'Since there is no validation in invitee Full name' but these lines check if the archived proposals of the app has the `PROPOSAL_INVITE_MEMBER` item **for a particular user.**
`inviteSecret` field exists even for `anyone` invite (as far as it seems) so I reckon checking the existence of that value is not useful in this case.

Comment (Silver-IT) [reply frontend/views/containers/group-settings/InvitationsTable.vue]: What I mean is that we can make two proposals to add two member `Alex Jin`. So I don't think the `invitee full name` shouldn't be used as one of the identifiers of the proposal.

Comment (SebinSong) [reply frontend/views/containers/group-settings/InvitationsTable.vue]: @Silver-IT Oh, now it's clear what you meant. yeah that's right and I think in that kind of case, additional check of whether the creator of the proposal is the current user would achieve our need here. what's your thought?

Comment (Silver-IT) [reply frontend/views/containers/group-settings/InvitationsTable.vue]: One creator can add two members with same name, can't him?

Comment (SebinSong) [reply frontend/views/containers/group-settings/InvitationsTable.vue]: @Silver-IT That's technically possible but why would anyone do that..? why does there has to be two different active invites for the same person?

Comment (Silver-IT) [reply frontend/views/containers/group-settings/InvitationsTable.vue]: @taoeffect, what do you think?

Comment (SebinSong) [reply frontend/views/containers/group-settings/InvitationsTable.vue]: @Silver-IT Btw, agreed  using `inviteSecret` is another good way to identify a proposal so made a change in the following commit here :)
https://github.com/okTurtles/group-income/pull/1649/commits/f8639e00a5a67e1ddff4813559d975c4608ae09a

**Review by Silver-IT — DISMISSED** [review]
Nice work, @SebinSong. I totally approve this PR.

File: frontend/views/containers/group-settings/InvitationsTable.vue (hunk 1 above)
Comment (Silver-IT) [reply frontend/views/containers/group-settings/InvitationsTable.vue]: Thank you, @SebinSong.

File: frontend/views/containers/group-settings/InvitationsTable.vue [hunk 2]
```diff
@@ -278,8 +287,21 @@ export default ({
...
+        const { data, payload } = entry[1]
+
+        return data.proposalType === PROPOSAL_INVITE_MEMBER &&
+          payload.inviteSecret === inviteSecret
+      })
+
+      if (proposalItemExists) {
+        sbp('okTurtles.events/emit', OPEN_MODAL, 'PropositionsAllModal')
+      } else {
+        alert('Unable to find the original proposal.')
```
Comment (taoeffect) [inline frontend/views/containers/group-settings/InvitationsTable.vue]: 1. All user-facing errors must be localized, so here we need the `L` function
2. What if the proposal is an existing open proposal? If it is, we should forward them to the proposals section on the dashboard instead of showing an error

**Review by taoeffect — CHANGES_REQUESTED** [review]
Great work @SebinSong! Review finished!

File: frontend/views/containers/group-settings/InvitationsTable.vue (hunk 2 above)
Comment (SebinSong) [reply frontend/views/containers/group-settings/InvitationsTable.vue]: @taoeffect 
I believe an invite for a member only created after the proposal has been passed, right? That's why I took that case out of consideration.

Comment (taoeffect) [reply frontend/views/containers/group-settings/InvitationsTable.vue]: @SebinSong oh, you're right 👍

**Review by taoeffect — APPROVED** [review]
Beautifully done @SebinSong! Tested & approved!
