### PR TITLE
#2935 - Fix some Chat UI bugs

### LINKED ISSUE #2935: UI bugs in `ChatMain.vue`
### Problem

**[1. The first item in the message-actions menu is pre-focused before user-interaction in Firefox]**

https://github.com/user-attachments/assets/e87642b7-9f4e-41fb-8d8f-a61445a96af8

**[2. The loader animation is hidden on mobile]**

<br><br>

**[3. Off centered title on the chatroom menu on mobile]**

### Solution
Fix

### PR DESCRIPTION
**Pull request by SebinSong**
closes #2935

### CODE REVIEW

File: frontend/views/containers/chatroom/ChatMain.vue [hunk 1]
```diff
@@ -601,13 +601,6 @@ export default ({
           sinceHeight = 0
         } else if (this.ephemeral.currentHighestHeight == null || !hasPreviousEvents) {
           const { height: latestHeight } = await sbp('chelonia/out/latestHEADInfo', chatRoomID)
-          /* .finally(() => {
-              if (this.ephemeral.loadingDown === instance) {
-                this.ephemeral.loadingDown = false
-              } else if (this.ephemeral.loadingUp === instance) {
-                this.ephemeral.loadingUp = false
-              }
-            }) */
```
Comment (SebinSong) [inline frontend/views/containers/chatroom/ChatMain.vue:610]: it seems this finally block has been moved down L622 below. So removed this comment.

File: frontend/views/pages/GroupChat.vue [hunk 2]
```diff
@@ -319,7 +319,7 @@ export default ({
   }
 }
 
-.c-header {
+.c-channel-header {
```
Comment (SebinSong) [inline frontend/views/pages/GroupChat.vue:322]: This is the fix for the No 3. of the issue:



`MenuHeader.vue` also has `.c-header` class on the root element so this block caused conflict in the styles applied to it.

File: frontend/views/containers/chatroom/ChatMain.vue [hunk 3]
```diff
@@ -1781,10 +1774,13 @@ export default ({
...
       this.$nextTick(this.resetObservers)
     },
-    'ephemeral.loadingDown' () {
+    'ephemeral.loadingDown' (newVal) {
       // If ephemeral.loadingDown changes, it means that we're dynamically
       // fetching from the server
       this.messageState.fetched = true
+      if (newVal) {
+        this.jumpToLatest('instant')
+      }
```
Comment (SebinSong) [inline frontend/views/containers/chatroom/ChatMain.vue:1783]: This (along with `.is-bottom` style added below) is the fix for No.2.

**Review by taoeffect — APPROVED** [review]
Approved! Great work @SebinSong!
