### PR TITLE
Fixing totally borked site when non-existent user is loaded

### LINKED ISSUE #294: Fix totally borked site when non-existent user is loaded
### Problem

When a user is created and logged in, initially everything is fine, but when we restart the server the created users are cleared on the backend during dev mode. When `localhost:8000/simple/` is visited, an error occurs in the console:

```

hapi.js:115 lookup name: john
client.js:802 GET http://localhost:3000/name/john 404 (Not Found)
Request._end @ client.js:802
Request.end @ client.js:706
(anonymous) @ request-base.js:194
then @ request-base.js:193
client.js:423 Uncaught (in promise) Error: Not Found
    at Request.<anonymous> (client.js:423)
    at Request.Emitter.emit (index.js:133)
    at XMLHttpRequest.xhr.onreadystatechange (client.js:735)
(anonymous) @ client.js:423
Emitter.emit @ index.js:133
xhr.onreadystatechange @ client.js:735
hapi.js:40 websocket connection opened!
```

Also, the entire frontend UI is not visible.

### Solution

Indicate the nature of the error and handle gracefully.

Problem seems to be in `main.js` => `loadLastUser`

Current workaround is to use incognito window or clear the application data. E.g. in Chrome open console > Application > Clear site data

### PR DESCRIPTION
**Pull request by hubudibu**
Fixes #294 

_'Indicate the nature of the error and handle gracefully.':_
As this seems to be an error that should only happen in development mode, I didn't take the time to come up with a nice UI for error messages that occur before the Vue instance is created. So what I did is:

When the local user seems to not exist on the server,
- provide information on the console
- log out
- clean up local user - this sounds a bit risky, can a situation happen when we shouldn't remove it?
- unbork site

screen shot 2018-01-11 at 12 39 30 am

**Ready for review**

### CODE REVIEW

File: frontend/simple/main.js [hunk 1]
```diff
@@ -10,9 +10,17 @@ import store from './js/state'
 async function loadLastUser () {
   let user = await db.loadCurrentUser()
   if (user) {
-    // TODO: handle error if we fail to find such a user
-    let identityContractId = await namespace.lookup(user)
-    await store.dispatch('login', {name: user, identityContractId})
+    let identityContractId = await namespace.lookup(user).catch((err) => {
```
Comment (taoeffect) [inline frontend/simple/main.js]: This await + catch is confusing, because it mixes Promise-style code with async/await-style code, making it unclear what the value of `identityContractId` will actually be.

So I recommend that, even if this works, convert to a try/catch block, which is what async/await should be paired with.

Comment (hubudibu) [reply frontend/simple/main.js]: you are right, this does look confusing! try/catch version coming up

**Comment by taoeffect** [comment]
Very nice.
