### PR TITLE
Rethrow uncaught Vue errors in dev mode or CI

### LINKED ISSUE #684: Make Cypress tests fail on any console error
### Problem

During PR reviews there are often console errors that go unnoticed in the Travis build, because they are Vue.js related errors that are somewhat minor and don't affect the overall outcome.

It would be nice if these could be noticed automatically as part of `grunt test` and cause Travis to fail.

### Solution

- Handle all uncaught exceptions using [`Vue.config.errorHandler`](https://vuejs.org/v2/api/#errorHandler) or [`window.onerror`](https://blog.sentry.io/2016/01/04/client-javascript-reporting-window-onerror), whichever one is better (justify your decision)
- Make sure Travis fails if there's ever a Promise that is rejected without being properly handled
- Make sure Travis fails if there's ever an uncaught exception thrown

### PR DESCRIPTION
**Pull request by snowteamer**
Closes #684

### CODE REVIEW

File: frontend/main.js [hunk 1]
```diff
@@ -47,6 +47,7 @@ console.info('NODE_ENV:', process.env.NODE_ENV)
 
 Vue.config.errorHandler = function (err, vm, info) {
   console.error(`uncaught Vue error in ${info}:`, err)
+  if (process.env.NODE_ENV === 'development' || process.env.CI) throw err
```
Comment (taoeffect) [inline frontend/main.js]: In development mode I don't think we need to rethrow as it will not accomplish anything but will cause duplicate messages in the console.

Also, could you add a comment above this line linking to the issue or this PR?

**Review by taoeffect — CHANGES_REQUESTED** [review]
Cool, thanks for the PR @snowteamer! One request

**Review by taoeffect — APPROVED** [review]
