### PR TITLE
Handle identity contract fork on login.

### LINKED ISSUE #2564: Failure to login/recover in Brave browser tab that had forked
### Problem

After the update to 1.2.2, I clicked the OK button but it did not recover.

I don't remember exactly what happened, but somehow I ended up logged out and with the red error banner.

Image

Attempts to log back in all fail, even after doing doing <kbd>command+shift+r</kbd>:

Image

SW logs meantime:

Image

### Solution

Find the bug and fix.

### PR DESCRIPTION
**Pull request by corrideat**
Closes #2564.

### CODE REVIEW

File: frontend/main.js [hunk 1]
```diff
@@ -109,17 +109,26 @@ async function startApp () {
     sbp('gi.ui/seriousErrorBanner', error)
     if (error?.name === 'ChelErrorForkedChain') {
       const rootState = sbp('state/vuex/state')
-      const type = rootState.contracts[contractID].type || '(unknown)'
+      if (!rootState.contracts[contractID]) {
+        console.error('Forked chain detected. However, there is no contract entry.', { contractID }, error)
+        return
+      }
+      const type = rootState.contracts[contractID] || '(unknown)'
```
Comment (taoeffect) [inline frontend/main.js]: Think this line should remain as it was..? `.type` missing...

File: frontend/main.js [hunk 2]
```diff
@@ -109,17 +109,26 @@ async function startApp () {
     sbp('gi.ui/seriousErrorBanner', error)
     if (error?.name === 'ChelErrorForkedChain') {
       const rootState = sbp('state/vuex/state')
-      const type = rootState.contracts[contractID].type || '(unknown)'
+      if (!rootState.contracts[contractID]) {
+        console.error('Forked chain detected. However, there is no contract entry.', { contractID }, error)
+        return
```
Comment (taoeffect) [inline frontend/main.js]: Can you add a comment explaining here why we don't proceed with recovery? Is it because in this situation we're no longer subscribed...? But then how did we get the error if we weren't subscribed...?

**Review by taoeffect — CHANGES_REQUESTED** [review]
Review ready!

**Review by taoeffect — APPROVED** [review]
Great work @corrideat !
