### PR TITLE
#1851 - Fix the broken VoterAvatars.vue component

### LINKED ISSUE #1851: VotersAvatar.vue in chat is broken
### Problem
image

The chat polls no longer display this avatar UIs for who has voted on which option. Also showing this console error.

### Solution
Figure out the cause of the bug and fix it.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #1851

### CODE REVIEW

File: frontend/views/components/modal/Prompt.vue [hunk 1]
```diff
@@ -45,11 +45,11 @@ export default ({
   methods: {
     closeModal () {
       sbp('okTurtles.events/emit', MODAL_RESPONSE, false)
-      this.$refs.modal.close()
+      this.$refs.modal.unload()
     },
     submit () {
       sbp('okTurtles.events/emit', MODAL_RESPONSE, true)
-      this.$refs.modal.close()
+      this.$refs.modal.unload()
```
Comment (SebinSong) [inline frontend/views/components/modal/Prompt.vue:52]: This is not related to the issue itself but it's a bug-fix for an issue I encountered where once the prompt modal is dismissed the entire page is frozen.

File: frontend/views/containers/chatroom/SendArea.vue [hunk 2]
```diff
@@ -387,7 +387,10 @@ export default ({
       const userArr = this.ephemeral.typingUsers
 
       if (userArr.length) {
-        const getDisplayName = (memberID) => (this.globalProfile(memberID).displayName || this.globalProfile(memberID).username || memberID)
+        const getDisplayName = (memberID) => {
+          const profile = this.globalProfile(memberID)
+          return profile?.displayName || profile?.username || memberID
+        }
```
Comment (SebinSong) [inline frontend/views/containers/chatroom/SendArea.vue:393]: just DRYing the `getDisplayname` method here.

**Review by taoeffect — APPROVED** [review]
Nice! 😄
