### PR TITLE
Attempt to fix errors related to timezone differences on proposal date display

### LINKED ISSUE #1293: Display proposal dates in the local timezone of the user
### Problem

Currently, the date a contract is created (and also likely the date it expires, when we implement showing that), displays the date in UTC timezone (I think), instead of the user's local timezone.

For example, here it shows "June 1, 2022" instead of "May 31, 2022":

Screen Shot 2022-05-31 at 5 26 30 PM

### Solution

Display the date in the local timezone of the client.

### PR DESCRIPTION
**Pull request by snowteamer**
Closes #1293

### CODE REVIEW

File: frontend/utils/time.js [hunk 1]
```diff
@@ -113,14 +113,20 @@ export function firstDayOfMonth (date: Date): Date {
...
-  return new Date(date).toLocaleDateString(locale, opts)
+  const locale = typeof navigator === 'undefined'
+    // Fallback for Mocha tests.
+    ? 'en-US'
+    // Flow considers `navigator.languages` to be of type `$ReadOnlyArray<string>`,
+    // which is not compatible with the `string[]` expected by `.toLocaleDateString()`.
+    // Casting to `string[]` through `any` as a workaround.
+    : ((navigator.languages: any): string[]) ?? navigator.language
+  // NOTE: `.toLocaleDateString()` automatically takes local timezone differences into account.
+  // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
```
Comment (taoeffect) [inline frontend/utils/time.js:128]: OK, essentially the same thing except we're allowing the full array to be passed in. That seems fine. However, why did you move this into this function instead of leaving it outside of it? Now this code will have to be run each time `humanDate` is called, and that seems unnecessary.

**Review by taoeffect — COMMENTED** [review]
Great PR @snowteamer, I think this should fix it. One doubt though, see comments.

File: frontend/utils/time.js (hunk 1 above)
Comment (snowteamer) [reply frontend/utils/time.js:128]: Mainly because other functions in this file don't need access to that variable.
I agree recomputing it is unnecessay most of the time, unless the user change their browser locale.

**Review by taoeffect — APPROVED** [review]
Approved!
