### PR TITLE
Improved SBP (Closes #389) + updated some dependencies + Flowtype fixes

### LINKED ISSUE #389: rewrite SBP to include full selectors + remove fn's from sbp fn
### Problem

1. The way selectors are currently registered allows them to be registered on any domain. This goes against the philosophy of SBP and will make filtering hard, etc.
2. The sbp function has other functions on it (e.g. `registerDomain`). This is also ugly and anti-SBP philosophy

### Solution

1. Refactor/rewrite all necessary code so that fully-qualified selectors are always created (including tests!)
2. Replace functions like `sbp.registerDomain` with internal selectors (e.g. `.domain/register`)

### LINKED ISSUE #403: Make it so that SBP domains register themselves
### Problem

Right now we have to do:

```js
import EVENTS from '../../shared/domains/okTurtles/events'
import DATA from '../../shared/domains/okTurtles/data'
import CONTRACTS from '../../shared/domains/groupIncome/contracts'

// ..

sbp('sbp/selectors/register', DATA)
sbp('sbp/selectors/register', EVENTS)
sbp('sbp/selectors/register', CONTRACTS)
```

Which is cumbersome, and also means that we have to call `'sbp/ready'` in places (e.g. in `hapi.js`) instead of making a direct call.

### Solution

We could make it so that in `main.js` you simply do, before anything else, at the top of the file:

```js
import '../../shared/domains/okTurtles/events'
import '../../shared/domains/okTurtles/data'
import '../../shared/domains/groupIncome/contracts'
```

Then it would be up to those domains themselves to call `'sbp/selectors/register'`.

This would also mean we could get rid of the whole `'sbp/ready'` and `pendingCalls` stuff. It also requires making it OK to register the same selector multiple times (requests to register already-registered selectors are ignored).

Note this depends on #402 being merged.

### PR DESCRIPTION
**Pull request by taoeffect**
+ SBP selectors must now have domain specified when being registered
+ `sbp.[fn]` moved into `sbp/` domain
+ Fixed `Map` API usage in `okTurtles.data` (thank `npm run flow`!)
+ Updated: `lodash`, `primus`, `uws`, `ws`, `babel-present-env`, `flow-bin`
+ Added type annotations for FlowType
+ Fixed a bug in `backend/database.js` that Flow caught

EDIT: now it also:

+ Make it so that SBP domains register themselves (Closes #403)

### CODE REVIEW

File: shared/sbp.js [hunk 1]
```diff
@@ -1,76 +1,57 @@
...
-}
-
-sbp.addDomainFilter = function (domain: string, filter: TypeFilter) {
-  domains[domain].domainFilters.push(filter)
-}
-
-sbp.setSelectorFilter = function (domain: string, selector: string, filter: TypeFilter) {
-  if (domains[domain].selectorFilters[selector]) {
-    throw new Error(`${domain}/${selector} filter exists`)
+const SBP_BASE_SELECTORS = {
```
Comment (hubudibu) [inline shared/sbp.js:28]: 👍 this is so much cleaner this way!

**Review by hubudibu — APPROVED** [review]
👍 sbp is getting nicer and nicer!

just a sidenote: it would make the review much easier and more focused (and thus faster :) ), if you could put separate tasks - eg. the dep updates and the actual sbp changes - in separate commits next time!

**Comment by hubudibu** [comment]
@taoeffect also, I know our take on test strategy can be quite different, but now the sbp domain seems like a nice candidate for some focused (unit-ish) testing :)
