### PR TITLE
Fix #2608

### LINKED ISSUE #2608: Cannot load the site at all now in one tab
### Problem

On Brave, w/1.2.5, I can no longer load the site at all.

It started out with me not being able to mark notifications as read #2605:

Image

Then I noticed this odd error in the logs:

Image

Apparently `date` was a function?!:

Image

Then I tried <kbd>command+shift+r</kbd> to force refresh the site, and now it's completely broken, even though I've cleared all the site data and unregistered the SW:

Image

Note that the other sites (staging, testing, and debug) seem to be working...

This manifest does exist...

```
$ curl "https://groupincome.app/file/z9brRu3VN9mM6vEkuwmLRsbqLSLvtqQNtQhnJswWUFe21vjXXSXD"
{"head":"{\"manifestVersion\":\"1.0.0\"}","body":"{\"name\":\"gi.contracts/identity\",\"version\":\"1.2.5\",\"contract\":{\"hash\":\"z9brRu3VLkz9YyewJVfkfDjaZgZDQG39fNdMaoZVaCD3Ma94cK1m\",\"file\":\"identity.js\"},\"signingKeys\":[\"[\\\"edwards25519sha512batch\\\",\\\"IjAFp6gIzHW2HOIXXS9b4A3EKf8t9NNa5nndHcROiDk=\\\",null]\"],\"contractSlim\":{\"file\":\"identity-slim.js\",\"hash\":\"z9brRu3VMtVDbdvarC491cmf7ZyEN6UpjP8W2KFqx74ZxyBiU9sP\"}}","signature":{"keyId":"z2DrjgbCDg34SaBhFjNEF45AVodCUu7QwcFBksz3BDgN4BekrdN","value":"pCvt8UZnac8l7l8PiktUjQUlGpkXVfjEQZfhjAeRUTNO5KWqSURNeCmSp+CXQZAPnv9SwWCXG4bAwNulWSI4Cw=="}}
```

For some reason it is loading it from disk cache:

Image

### Solution

- Figure out why it's loading the file from disk cache and prevent it from doing that.
- Figure out why `date` is a function in `periodStampsForDate` and fix it.

### PR DESCRIPTION
**Pull request by corrideat**

### CODE REVIEW

File: frontend/controller/serviceworkers/sw-primary.js [hunk 1]
```diff
@@ -251,9 +251,7 @@ sbp('sbp/selectors/register', {
         })))
         Object.defineProperty(computedGetters, 'currentPaymentPeriodForGroup', {
           get: function () {
-            return (state, getters) => {
-              return (state) => getters.periodStampGivenDateForGroup(state, new Date())
-            }
+            return (state) => getters.periodStampGivenDateForGroup(state, new Date())
```
Comment (taoeffect) [inline frontend/controller/serviceworkers/sw-primary.js]: I don't think you can do this. The `getters` object is just a POJO AFAICT.

Calling it like this won't work.

Note `periodStampGivenDateForGroup` takes `state, getters`:

```js
  periodStampGivenDateForGroup (state, getters) {
    return (state, date: string | Date, periods?: string[]): string | void => {
      return periodStampsForDate(date, {
        knownSortedStamps: periods || getters.groupSortedPeriodKeysForGroup(state),
        periodLength: getters.groupSettingsForGroup(state).distributionPeriodLength
      }).current
    }
  },
```

**Review by taoeffect — CHANGES_REQUESTED** [review]
Review ready!

File: frontend/controller/serviceworkers/sw-primary.js (hunk 1 above)
Comment (corrideat) [reply frontend/controller/serviceworkers/sw-primary.js]: ~~No, the getter takes a state and a date after being parsed.~~

**Review by taoeffect — APPROVED** [review]
Nice!
