### PR TITLE
Bug Fix #246

### LINKED ISSUE #246: Fix invite not working
### Problem

- In browser window 1, I create user **john**
- In private browser window 2, I create user **bob**
- In browser window 1, I go to create a group and click "create group". Nothing happens. I click "create group" a second time and it proceeds to the invite screen. (a bug in itself)
- I logout as **john**, and create user **greg** in browser window 1
- I create another group with the same name ("Turtles") and different attributes, then click "create group". This time it goes straight to the Invite screen.
- I add "bob" and "john" to the initial invites, and then click "Send Invites"

#### This is what I see in browser window 1's console:

screen shot 2017-04-23 at 5 48 37 pm

#### This is what I see in the terminal:

```
broadcasting to room 21XWnNPbGq6EnMHQfNRwwj29Whxm4PbPB3PFFAa8jKd1WMuCAG: { type: 'entry',
  data:
   { contractId: '21XWnNPbGq6EnMHQfNRwwj29Whxm4PbPB3PFFAa8jKd1WMuCAG',
     hash: '21XWnNKg7ZJrwwEa9ZCfFaF8tRYTXwTG6arfakrPnF2ZL2rMSk',
     entry:
      { version: 0,
        parentHash: '21XWnNPbGq6EnMHQfNRwwj29Whxm4PbPB3PFFAa8jKd1WMuCAG',
        data: [Object],
        type: 'RecordInvitation' } } }
{ Error
    at Object._callee3$ (group-income-simple/backend/database.js:129:11)
    at tryCatch (group-income-simple/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (group-income-simple/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (group-income-simple/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (group-income-simple/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at group-income-simple/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
  data: 'claimed hash: 21XWnNPbGq6EnMHQfNRwwj29Whxm4PbPB3PFFAa8jKd1WMuCAG, reality: 21XWnNKg7ZJrwwEa9ZCfFaF8tRYTXwTG6arfakrPnF2ZL2rMSk',
  statusCode: 400,
  message: '"claimed hash: 21XWnNPbGq6EnMHQfNRwwj29Whxm4PbPB3PFFAa8jKd1WMuCAG, reality: 21XWnNKg7ZJrwwEa9ZCfFaF8tRYTXwTG6arfakrPnF2ZL2rMSk"' }
Error
    at Object._callee3$ (group-income-simple/backend/database.js:129:11)
    at tryCatch (group-income-simple/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (group-income-simple/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (group-income-simple/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (group-income-simple/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at group-income-simple/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
Debug: handler, error
    {"msec":91.07457399368286,"error":"\"claimed hash: 21XWnNPbGq6EnMHQfNRwwj29Whxm4PbPB3PFFAa8jKd1WMuCAG, reality: 21XWnNKg7ZJrwwEa9ZCfFaF8tRYTXwTG6arfakrPnF2ZL2rMSk\"","data":{"data":"claimed hash: 21XWnNPbGq6EnMHQfNRwwj29Whxm4PbPB3PFFAa8jKd1WMuCAG, reality: 21XWnNKg7ZJrwwEa9ZCfFaF8tRYTXwTG6arfakrPnF2ZL2rMSk","statusCode":400,"message":"\"claimed hash: 21XWnNPbGq6EnMHQfNRwwj29Whxm4PbPB3PFFAa8jKd1WMuCAG, reality: 21XWnNKg7ZJrwwEa9ZCfFaF8tRYTXwTG6arfakrPnF2ZL2rMSk\"","isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}}}
Debug: internal, error
    Error
    at Object._callee3$ (group-income-simple/backend/database.js:129:11)
    at tryCatch (group-income-simple/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (group-income-simple/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (group-income-simple/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (group-income-simple/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at group-income-simple/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

Note there appears to be a hash miss match of some sort.

#### This is what I see in private window 2:

screen shot 2017-04-23 at 5 51 07 pm

Indeed in the mailbox there is an invite "From 21XWnNPbGq6EnMHQfNRwwj29Whxm4PbPB3PFFAa8jKd1WMuCAG".

### Solution

1. Figure out what's going on and fix it
2. Add tests to catch this and prevent it from happening again

### PR DESCRIPTION
**Pull request by vijayee**
This correct the invite behavior where all async calls are sent simultaneously breaking the order in which latest hashes are gathered.

### CODE REVIEW

File: frontend/simple/views/CreateGroup.vue [hunk 1]
```diff
@@ -217,11 +217,10 @@ export default {
         await backend.subscribe(hash)
         Vue.events.$once(hash, (contractId, entry) => {
           this.$store.commit('setCurrentGroupId', hash)
+          // Take them to the invite group members page.
+          this.$router.push({path: '/invite'})
```
Comment (taoeffect) [inline frontend/simple/views/CreateGroup.vue:221]: Nice catch.
