### PR TITLE
Handle subscription errors.

### LINKED ISSUE #2612: Registration failed - Push service error
### Problem

Image

A user was doing something (I think they were creating a group maybe on Android), and they got this error and the logs below:

📎 [gi_logs.json.txt.zip](https://github.com/user-attachments/files/18771257/gi_logs.json.txt.zip)

### Solution

1. The error message is useless and unhelpful, improve it both in the UI and in the logs with more details.
2. Then figure out why this happened and prevent it from happening again (if possible).
3. If it happens anyway, make sure that the app attempts to re-register

### PR DESCRIPTION
**Pull request by corrideat**
Closes #2612.

### CODE REVIEW

File: frontend/controller/service-worker.js [hunk 1]
```diff
@@ -194,13 +198,24 @@ sbp('sbp/selectors/register', {
           return subscription
         }).catch(e => {
           if (!(retryCount > 3) && e?.message === 'WebSocket connection is not open') {
-            sbp('okTurtles.events/once', ONLINE, () => {
-              setTimeout(() => sbp('service-worker/setup-push-subscription', (retryCount || 0) + 1), 200)
+            return new Promise((resolve) => {
+              sbp('okTurtles.events/once', ONLINE, () => {
+                setTimeout(() => resolve(sbp('service-worker/setup-push-subscription', (retryCount || 0) + 1)), 200)
+              })
```
Comment (taoeffect) [inline frontend/controller/service-worker.js]: The way this is written can cause the entire call to `'service-worker/setup-push-subscription'` to hang potentially indefinitely if this event never gets fired.

Can you add a timeout condition to call `reject` on the promise?

**Review by taoeffect — CHANGES_REQUESTED** [review]
Nice work @corrideat! One change request to avoid a "stuck" app that just spins forever.

File: frontend/controller/service-worker.js (hunk 1 above)
Comment (corrideat) [reply frontend/controller/service-worker.js]: I've added it as per your request, but the existing behaviour won't result in a ' "stuck" app that just spins forever', since no UI elements depend on this promise.

File: frontend/controller/service-worker.js [hunk 2]
```diff
@@ -194,13 +198,29 @@ sbp('sbp/selectors/register', {
           return subscription
         }).catch(e => {
           if (!(retryCount > 3) && e?.message === 'WebSocket connection is not open') {
-            sbp('okTurtles.events/once', ONLINE, () => {
-              setTimeout(() => sbp('service-worker/setup-push-subscription', (retryCount || 0) + 1), 200)
+            return new Promise((resolve, reject) => {
+              const errorTimeoutId = setTimeout(() => {
+                reject(new Error('Timed out waiting to come back online'))
+                cancel()
+              }, 600e3)
```
Comment (taoeffect) [inline frontend/controller/service-worker.js:205]: I don't think users are going to wait 10 minutes to use our app.

Could you please reduce this to 7 seconds?

**Review by taoeffect — CHANGES_REQUESTED** [review]
One last change request!

File: frontend/controller/service-worker.js (hunk 1 above)
Comment (taoeffect) [reply frontend/controller/service-worker.js]: Ah, I see................. maybe that fact should be a comment then.

**Review by taoeffect — APPROVED** [review]
Let's hope this is sufficient 👍
