### PR TITLE
Fix browser notifications not showing up on Android

### LINKED ISSUE #1944: sideEffect error on mobile related to DM notification
### Problem

Whenever someone sends me a DM on mobile in Android, I get this error in the PWA:

tmp-1713455351100_720

```json
{
  "timestamp": "2024-04-18T03:25:56.577Z",
  "type": "error",
  "msg": [
    "[chelonia] ERROR 'TypeError' in sideEffect for <op_ae|z9brRu3VSVRdQPTkw7b2KkkXoQrnAQ2JeriCdafLThAU9yHsjAXs of z9brRu3VUgFkg1eAfirGJ454n49S9sDgBDRx3EDAzPHXzUMSjaXj>: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.",
    {
      "name": "TypeError",
      "message": "Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.",
      "stack": "TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.\n    at makeNotification (eval at chelonia/private/loadManifest (https://xxx.xxx.xxx/assets/js/chunk-M5ENVJQB-cached.js:1:19965), <anonymous>:7081:28)\n    at messageReceivePostEffect (eval at chelonia/private/loadManifest (https://xxx.xxx.xxx/assets/js/chunk-M5ENVJQB-cached.js:1:19965), <anonymous>:7196:28)\n    at Object.sideEffect (eval at chelonia/private/loadManifest (https://xxx.xxx.xxx/assets/js/chunk-M5ENVJQB-cached.js:1:19965), <anonymous>:7475:11)\n    at z9brRu3VQeSP1LaQiXp7p55UkU4rfrSBzkYeEyDQ4daQYyoQcSsg/gi.contracts/chatroom/addMessage/sideEffect (https://xxx.xxx.xxx/assets/js/chunk-M5ENVJQB-cached.js:22:22486)\n    at u (https://xxx.xxx.xxx/assets/js/chunk-SSANYCJJ-cached.js:1:222)\n    at l (https://xxx.xxx.xxx/assets/js/chunk-M5ENVJQB-cached.js:19:27723)\n    at Object.processSideEffects (https://xxx.xxx.xxx/assets/js/chunk-M5ENVJQB-cached.js:19:27802)\n    at chelonia/private/in/handleEvent (https://xxx.xxx.xxx/assets/js/chunk-M5ENVJQB-cached.js:19:25051)\n    at async https://xxx.xxx.xxx/assets/js/chunk-M5ENVJQB-cached.js:19:13995\n    at async okTurtles.eventQueue/queueEvent (https://xxx.xxx.xxx/assets/js/chunk-M5ENVJQB-cached.js:1:2532)"
    },
    {
      "message": "{\"_signedData\":[\"[\\\"z2Drjgb9hxXGP7dt5AtgrviEuorDiJWvvyNStfTfSdUn29vPCje\\\",\\\"HgOEBDYzbu80ntTWkUYhoU2yTOFA3NK/ti4ZAJcYuhxVP55BF9ubWjEbi6FUw4qzPxAY33nRR0ejYBEmLGucAv2OxNilyD3CBjOu+MN9HlV7aJ3gaStmukLX9f6cWiDWTcj9E8Q6dgDpCqoq59zJmiecXwNOWSk+seDmX8kTuHqEvCgIQRG0tVthE+TsfN820zkX/X51bNFK1m9/V868Bab36S31jJ8TTpA0pOifIfwj1E2GUA6D+/1SmD9rx0cZ+dEr8hbG6eJeTFu5qyT9aPcg699dbOBpt4L7F/T4vO9V+1x5/A8YB/XwV+/+2RVBcEMBh+8hN+zFa29Us1Bo8lIaheIAO6k7C/tfc0nrML+MHN9rChOPZkmh2ofosxLAVkSPAO9xX7HbTcbHQY6yPzUdVJPGAkb+Lg0/vK8hSH0j4CAP6Mz/0do5vJv2WtPpV2OiyRvXkPKMY+DOiRP7SCaZZNDQLJ8UhpwsZHxZunVSTQp6j73bogQY0hXR0qKn6FJASIVT\\\"]\",\"z2DrjgbJf8CxGUDyxr1RPNM5dHHihbvZ5HAPHFmU5wFiAZuSJ3n\",\"fhsDPNZX1OPFV/nfLCuAcGXoSEB5f/CfOBrUr19uYwRZWKAb0wok/DsI/4Tfb/DYoTw9AaIpKo6j7cQD6MZ8Dg==\"],\"head\":\"{\\\"version\\\":\\\"1.0.0\\\",\\\"previousHEAD\\\":\\\"z9brRu3VKaZogJFJ1xRF3DtrRKBtzNXApdKoWdwrNfFpEkWNeCjG\\\",\\\"height\\\":6,\\\"contractID\\\":\\\"z9brRu3VUgFkg1eAfirGJ454n49S9sDgBDRx3EDAzPHXzUMSjaXj\\\",\\\"op\\\":\\\"ae\\\",\\\"manifest\\\":\\\"z9brRu3VQeSP1LaQiXp7p55UkU4rfrSBzkYeEyDQ4daQYyoQcSsg\\\"}\"}"
    }
  ]
}
```

### Solution

Find and fix the bug!

### PR DESCRIPTION
**Pull request by snowteamer**
Closes #1944

### Summary of changes
- Change `makeNotification()` to use `ServiceWorkerRegistration.showNotification()` to display browser notifications where `new Notification()` isn't supported, e.g. in Android.

#### Additional information
- Notifications displayed using the above mentioned way do not take the `path` parameter into account, in other words the user isn't redirected to the appropriate page when the notification is clicked.

### CODE REVIEW

File: frontend/model/contracts/shared/nativeNotification.js [hunk 1]
```diff
@@ -31,10 +31,22 @@ export function makeNotification ({ title, body, icon, path }: {
...
+      }
+    } catch {
+      try {
+        // FIXME: find a cross-browser way to pass the 'path' parameter when the notification is clicked.
+        navigator.serviceWorker?.ready.then(registration => {
+          // $FlowFixMe
+          registration.showNotification(title, { body, icon })
+        }).catch(console.warn)
+      } catch (error) {
+        console.debug('makeNotification: ', error.message)
```
Comment (taoeffect) [inline frontend/model/contracts/shared/nativeNotification.js]: Should use `console.error` here probably

File: frontend/model/contracts/shared/nativeNotification.js [hunk 2]
```diff
@@ -31,10 +31,22 @@ export function makeNotification ({ title, body, icon, path }: {
...
-      notification.onclick = function (event) {
-        sbp('controller/router').push({ path }).catch(console.warn)
+    try {
+      const notification = new Notification(title, { body, icon })
+      if (path) {
+        notification.onclick = (event) => {
+          sbp('controller/router').push({ path }).catch(console.warn)
+        }
+      }
+    } catch {
```
Comment (taoeffect) [inline frontend/model/contracts/shared/nativeNotification.js:41]: Is `typeof window.Notification` (or similar) not a reliable way to test this? Catching an exception is the only way?

File: frontend/controller/serviceworkers/sw-primary.js [hunk 3]
```diff
@@ -66,6 +66,11 @@ self.addEventListener('message', function (event) {
   }
 })
 
+// Handle clicks on notifications issued via registration.showNotification().
+self.addEventListener('notificationclick', event => {
+  console.debug('[sw] Notification clicked:', event.notification)
+})
+
```
Comment (taoeffect) [inline frontend/controller/serviceworkers/sw-primary.js:73]: Curious, does this actually get called?

If so, it sounds like a maybe broadcasting the click to all of the open windows (or "the most prominent one", if such a concept exists) might be the answer?

**Review by taoeffect — CHANGES_REQUESTED** [review]
Nicely done @snowteamer!

I tried to test this with `grunt dev --tunnel` and wasn't able to get push notifications working — but that's because they aren't implemented. The good news is, while the app was in the foreground, I saw no errors in the logs (via the Application Logs in the UI), and did hear a chime indicating someone had messaged.

Review below!

File: frontend/model/contracts/shared/nativeNotification.js (hunk 2 above)
Comment (snowteamer) [reply frontend/model/contracts/shared/nativeNotification.js:41]: Yea the `Notification` object does exist in Android, but calling it with `new` yields that "Illegal constructor" error

File: frontend/controller/serviceworkers/sw-primary.js (hunk 3 above)
Comment (snowteamer) [reply frontend/controller/serviceworkers/sw-primary.js:73]: This did get called in the SW console (not the main console) when I tested.

And this could indeed be used to focus the window (a.k.a Client) from which the `showNotification` call originated.
But when `path` is given in `makeNotification()` we also want to redirect to another page, and I'm not sure yet how to achieve that.

Comment (taoeffect) [reply frontend/controller/serviceworkers/sw-primary.js:73]: We could probably leave this to @corrideat in his upcoming Push Notifications PR as he's building a communications system between the service worker and the open windows/tabs.

**Review by taoeffect — APPROVED** [review]
Thanks @snowteamer! LGTM!
