### PR TITLE
#778 improve modal keyboard navigation

### LINKED ISSUE #778: Modals - Keyboard navigation is incorrect.
### Problem

I'll give the example of Login modal, but this happens to all the modals.

When we navigate in a modal with the keyboard, and we try to focus the last element of it (for example "Login" button, (after being enabled!), the focus position moves immediately to the close button. It should instead stay on the "Login" button.

### Solution
The way we trap focus needs to be done with a native 'keyup' eventListener to the document, not the modal itself (as it is nowadays). That way we can detect when the user starts to tab to outside of the modal and redirect them back to the first clickable element inside the modal.

### PR DESCRIPTION
**Pull request by sandrina-p**
Closes #778 

Apr-11-2020 14-49-02

- Improved the keyboard navigation within a modal: It now works as expected: when reaching the last interactive element, the next time we press `Tab` it goes back to the first element and vice-versa.
- The "solid" buttons didn't change background color on `:focus`, Now they do, as in DS.
- Add a required prop to modal: `a11yTitle` so that SR (screen readers) can read correctly what's the modal about when they start to interact with it.

### CODE REVIEW

**Review by pieer — DISMISSED** [review]

**Comment by dotmacro** [comment]
Log in modal works great! :-D 

Tab still misses the "Log in" _link_ in the footer of the sign up modal. (Should it also be a button, like "Create an account" in the footer of the Log In modal?)
Screen Shot 2020-04-13 at 7 25 49 PM

Scout rule: "Login" button on welcome screen and "Log in" modal should say "Log in" with a space, just like the modal title.

File: frontend/views/containers/access/LoginModal.vue [hunk 1]
```diff
@@ -1,5 +1,5 @@
 <template lang='pug'>
-  modal-template(class='has-background' ref='modal')
+  modal-template(class='has-background' ref='modal' :a11yTitle='L("Login")')
```
Comment (taoeffect) [inline frontend/views/containers/access/LoginModal.vue]: Andrea noticed that we've been writing "Login" incorrectly, it should be "Log In"

**Review by taoeffect — CHANGES_REQUESTED** [review]
Just one minor copy issue related to "Login" vs "Log In" (Andrea noticed we've been writing that incorrectly) + if you can see if you can fix the issue she noticed with consistent tab behavior between Log In and Sign Up modals.

**Comment by sandrina-p** [comment]
@dotmacro the "Log in" link is fixed now and accessible by keyboard!

> Should it also be a button, like "Create an account" in the footer of the Log In modal?

Yes, it should be a button. Before it was a `<a>` tag without `href=''`. An `<a>` element is only keyboard accessible when it has a non-empty href attribute. `<a>` or `<a href="">` should not be used for links. In this case it must be a `<button>`. [webAIM reference](https://webaim.org/techniques/keyboard/)

**Review by taoeffect — APPROVED** [review]
👍
