### PR TITLE
Basic notifications improvements

### LINKED ISSUE #1349: Basic notifications improvements
### Problem

Our notifications setup could still use some improvements.

- Our notifications settings don't allow you to toggle notifications on and off
- User feedback for notifications isn't the best
- When a user clicks on a notification for an @mention, it doesn't take them to the message

### Solution

h/t @snowteamer for the following suggestions:

> - Use a toggle switch like we already do e.g. for the reduced motion setting. This would also allow revoking a previously granted permission, which currently doesn't look easy to do.

Greg adds: since we don't have designs for this, a simple checkbox will do.

> - Emit a single notification when the permission is granted, with a nice feedback message. This would immediately reassure users that native notifications are now effectively enabled and working. A corresponding Vue notification is not necessary.

And from myself:

> clicking on the browser notifications => taking you to the corresponding message in chatroom or DM

### LINKED ISSUE #1350: Exception thrown in chat sideEffect
### Problem

When @dotmacro used the app, she encountered this error:

image

However, the error went away after she refreshed the page. Still we should track it down and fix it.

### Solution

Find the issue and fix.

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of Changes

- Closes #1349 
- Tried to resolve #1350 ( But did not get this error. )
- Fix error to display unread position
  1. Regarding `createdDate`
  2. When switch channel very fast
- Display `Original message was removed.` in reply message
- Fix error in delete chatroom
- Improve to display the mentions count when user edit message

### CODE REVIEW

File: frontend/model/contracts/chatroom.js [hunk 1]
```diff
@@ -393,6 +399,15 @@ sbp('chelonia/defineContract', {
         if (msgIndex >= 0) {
           state.messages.splice(msgIndex, 1)
         }
+        // filter replied messages and check if the current message is original
+        for (const message of state.messages) {
+          if (message.replyingMessage) {
+            if (message.replyingMessage.id === data.id) {
```
Comment (snowteamer) [inline frontend/model/contracts/chatroom.js]: No big deal but these two conditions could be merged into one with `&&`

File: frontend/model/contracts/shared/nativeNotification.js [hunk 2]
```diff
@@ -9,20 +10,39 @@ export async function requestNotificationPermission (force: boolean = false): Pr
...
-
   try {
-    return await Notification.requestPermission()
+    const permission = await Notification.requestPermission()
+    if (permission === 'granted') {
+      sbp('state/vuex/commit', 'setNotificationGranted', true)
+    } else {
+      sbp('state/vuex/commit', 'setNotificationGranted', false)
+    }
+    return permission
```
Comment (taoeffect) [inline frontend/model/contracts/shared/nativeNotification.js]: I do not think these changes are an improvement. They seem to me to be very unnecessary and only add the unnecessary complexity of managing more state for no reason.

It is perfectly fine to call `makeNotification` without checking whether this variable is set, because that function already checks if permissions are granted.

Please remove `setNotificationGranted`, `state.notificationGranted`, and everything associated with it.

File: frontend/model/contracts/shared/nativeNotification.js [hunk 3]
```diff
@@ -9,20 +10,39 @@ export async function requestNotificationPermission (force: boolean = false): Pr
...
+    }
+  }
+}
+
+export function getNotificationPermission (): string | null {
+  if (typeof Notification === 'undefined') {
+    return null
+  }
+
+  return Notification.permission
```
Comment (taoeffect) [inline frontend/model/contracts/shared/nativeNotification.js]: This function does basically nothing. It should be removed.

Wherever you need to check for these permissions, you can simply do:

```js
Notification?.permission === 'granted'
```

File: frontend/views/containers/chatroom/ChatMain.vue [hunk 4]
```diff
@@ -449,7 +454,9 @@ export default ({
       } else {
         events = await sbp('chelonia/out/eventsBefore', before, limit)
       }
-
+      if (curChatRoomId !== this.currentChatRoomId) {
+        return
+      }
```
Comment (taoeffect) [inline frontend/views/containers/chatroom/ChatMain.vue]: This needs a comment above it explaining why this is here

File: frontend/model/contracts/chatroom.js [hunk 5]
```diff
@@ -59,13 +59,19 @@ function addMention ({ contractID, messageId, datetime, text, username, chatRoom
...
 
-  const rootGetters = sbp('state/vuex/getters')
-  const groupID = rootGetters.groupIdFromChatRoomId(contractID)
-  makeNotification({
-    title: `# ${chatRoomName}`,
-    body: text,
-    icon: rootGetters.globalProfile2(groupID, username).picture
-  })
+  const rootState = sbp('state/vuex/state')
+  if (rootState.notificationGranted) {
```
Comment (taoeffect) [inline frontend/model/contracts/chatroom.js]: Please revert this change (see other comment below)

**Review by taoeffect — CHANGES_REQUESTED** [review]
Great work @Silver-IT! Preliminary review finished!

File: frontend/model/contracts/shared/nativeNotification.js [hunk 6]
```diff
@@ -9,20 +10,39 @@ export async function requestNotificationPermission (force: boolean = false): Pr
...
     return null
   }
-
   try {
-    return await Notification.requestPermission()
+    const permission = await Notification.requestPermission()
+    if (permission === 'granted') {
+      sbp('state/vuex/commit', 'setNotificationGranted', true)
+    } else {
+      sbp('state/vuex/commit', 'setNotificationGranted', false)
```
Comment (snowteamer) [inline frontend/model/contracts/shared/nativeNotification.js]: Could also slightly simplify here, with `sbp('state/vuex/commit', 'setNotificationGranted', permission === 'granted')`

File: frontend/model/contracts/shared/nativeNotification.js (hunk 2 above)
Comment (Silver-IT) [reply frontend/model/contracts/shared/nativeNotification.js]: The reason why I used this state.notificationGranted is because users can not switch Notification permission using the Switch button.
For example, if a user allows permission and switch on, the notifications should be working.
And once he switched off, the notifications should not be working.
But a simple switching off, this can not deny browser notification permission.

That's why it is necessary.

File: frontend/model/contracts/shared/nativeNotification.js (hunk 3 above)
Comment (Silver-IT) [reply frontend/model/contracts/shared/nativeNotification.js]: Yeah. Correct. Nice catch.

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 4 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue]: Got it.

File: frontend/model/contracts/shared/nativeNotification.js (hunk 2 above)
Comment (taoeffect) [reply frontend/model/contracts/shared/nativeNotification.js]: @Silver-IT There has to be a better way to implement this.

For example, in `mounted` you could check to see what the value of it is, and then set an ephemeral boolean variable in the NotificationSettings.vue component based on it.

Then it will be sync'd from that point on.

File: frontend/model/contracts/shared/nativeNotification.js [hunk 7]
```diff
@@ -9,20 +10,39 @@ export async function requestNotificationPermission (force: boolean = false): Pr
...
     return
   }
-  // eslint-disable-next-line
-  new Notification(title, { body, icon })
+
+  const notification = new Notification(title, { body, icon })
+  if (url) {
+    notification.onclick = function (event) {
+      event.preventDefault()
+      open(url, '_blank')
```
Comment (snowteamer) [inline frontend/model/contracts/shared/nativeNotification.js]: I don't feel really comfortable with the `open()` function. Wouldn't it be better to somehow push the URL onto the Vue router?

File: frontend/model/contracts/shared/nativeNotification.js (hunk 2 above)
Comment (Silver-IT) [reply frontend/model/contracts/shared/nativeNotification.js]: > For example, in mounted you could check to see what the value of it is, and then set an ephemeral boolean variable in the NotificationSettings.vue component based on it.

```
  mounted () {
    const permission = Notification?.permission
    if (permission === null) {
      this.disabled = true
    } else {
      this.granted = permission === 'granted' && this.notificationGranted
    }
  },
```

We use `granted` as a init value of the Switch component. Do you mean this?
Actually this value `this.granted` is the final boolean flag represents the if notification will be displayed or not.

File: frontend/model/contracts/chatroom.js (hunk 1 above)
Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js]: if (message.replyingMessage?.id === data.id)
And this is better solution, isn't it?

File: frontend/model/contracts/shared/nativeNotification.js (hunk 6 above)
Comment (Silver-IT) [reply frontend/model/contracts/shared/nativeNotification.js]: Yeah. You are the KING of Code Optimization. 😁

File: frontend/model/contracts/shared/nativeNotification.js (hunk 7 above)
Comment (Silver-IT) [reply frontend/model/contracts/shared/nativeNotification.js]: Yeah. I am not sure why I didn't think that way. Really nice catch it is.

File: frontend/model/contracts/shared/nativeNotification.js (hunk 2 above)
Comment (taoeffect) [reply frontend/model/contracts/shared/nativeNotification.js]: > We use granted as a init value of the Switch component. Do you mean this?

Yeah that looks good, something like that! 👍

File: frontend/model/contracts/shared/nativeNotification.js (hunk 6 above)
Comment (taoeffect) [reply frontend/model/contracts/shared/nativeNotification.js]: @snowteamer See other discussion about this being removed completely: https://github.com/okTurtles/group-income/pull/1355#discussion_r926296100

File: frontend/model/contracts/shared/nativeNotification.js (hunk 2 above)
Comment (Silver-IT) [reply frontend/model/contracts/shared/nativeNotification.js]: `this.notificationGranted` is the Vuex state. So do you agree to use vuex state for this purpose?

Comment (taoeffect) [reply frontend/model/contracts/shared/nativeNotification.js]: Oops! Sorry I didn't see that part. No I'm still very much against using vuex for this :P

Why is that part even there? Couldn't it be just:

```js
  mounted () {
    const permission = Notification?.permission
    if (permission === null) {
      this.disabled = true
    } else {
      this.granted = permission === 'granted'
    }
  },
```

File: frontend/model/contracts/chatroom.js (hunk 1 above)
Comment (snowteamer) [reply frontend/model/contracts/chatroom.js]: Indeed (provided `data.id` cannot be undefined)

File: frontend/model/contracts/shared/nativeNotification.js (hunk 6 above)
Comment (snowteamer) [reply frontend/model/contracts/shared/nativeNotification.js]: @greg Yea this makes my suggestion redundant

File: frontend/model/contracts/chatroom.js (hunk 1 above)
Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js]: Right. Only `message.replyingMessage` could be undefined.
```
if (message.replyingMessage?.id === data.id)
```

File: frontend/model/contracts/chatroom.js [hunk 8]
```diff
@@ -367,11 +371,10 @@ sbp('chelonia/defineContract', {
         const mentions = makeMentionFromUsername(me)
         const isIncludeMention = data.text.includes(mentions.me) || data.text.includes(mentions.all)
         if (!isAlreadyAdded && isIncludeMention) {
-          // TODO: Not sure createdDate should be this way
           addMention({
             contractID,
             messageId: data.id,
-            datetime: meta.createdDate,
+            datetime: data.createdDate, // TODO: Not sure createdDate should be this way
```
Comment (taoeffect) [inline frontend/model/contracts/chatroom.js]: Can you explain why you are using `data.createdDate` here instead of `meta.createdDate`? What does this represent?

File: frontend/model/contracts/shared/nativeNotification.js [hunk 9]
```diff
@@ -1,28 +1,33 @@
...
+import sbp from '@sbp/sbp'
 
 // NOTE: since these functions don't modify contract state, it should
 //       be safe to modify them without worrying about version conflicts.
 
 export async function requestNotificationPermission (force: boolean = false): Promise<null | string> {
   if (typeof Notification === 'undefined' ||
-    (!force && Notification.permission !== 'default') ||
-    (force && Notification.permission === 'granted')) {
+    (!force && Notification.permission !== 'default')) {
```
Comment (taoeffect) [inline frontend/model/contracts/shared/nativeNotification.js]: Why are we returning `null` in this case instead of just calling `await Notification.requestPermission()` below?

What if `Notification.permission` is === `'granted'` here? It would return `null` but we want this to return `'granted'` in that case...

File: frontend/model/contracts/chatroom.js (hunk 8 above)
Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js]: That's because this `datetime` is used to decide if the this mention should be removed or not.
Let's say the last message was a mention.
If user reads the last message, the mention is removed from the list of mentions.
And also the `UnreadSince.messageId` is the ID of the last message which made mention.
Here, if user edits the message(the last one) for example, user can update mention from @all to @alex or just update original message content, the mention is created again.
If the new mention's datetime is the editing time, it is later than the UnreadSince.createdDate.
So we can not delete this mention unless user creates a new message and read it.
That's why I used the `data.createdDate` instead of `meta.createdDate`.

Comment (taoeffect) [reply frontend/model/contracts/chatroom.js]: OK, I'm having difficulty following, and I don't think you answered what `data.createdDate` represents. What time does it represent? What time is stored in it?

Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js]: `meta.createdDate` : The date when edit this message
`data.createdDate` : The date when the message was created

Comment (taoeffect) [reply frontend/model/contracts/chatroom.js]: >  data.createdDate : The date when the message was created

OK, I see.

Normally that information is stored on the message object itself when it was created via `'gi.contracts/chatroom/addMessage'`.

Is there a reason you can't do that here and have to instead pass it in as part of the message edit?

File: frontend/model/contracts/shared/nativeNotification.js (hunk 9 above)
Comment (Silver-IT) [reply frontend/model/contracts/shared/nativeNotification.js]: > Why are we returning null in this case instead of just calling await Notification.requestPermission() below?

We don't need to request permission because Notification is undefined or user already reacted.
Since the `force` is false, we don't need to request if he is already replied.

File: frontend/model/contracts/chatroom.js (hunk 8 above)
Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js]: Correct, we can not do this in `process` or `sideEffect` or addMessage.
This happens only when the message is edited.

File: frontend/model/contracts/shared/nativeNotification.js (hunk 9 above)
Comment (taoeffect) [reply frontend/model/contracts/shared/nativeNotification.js]: @Silver-IT The problem though is that it's not specified what this function is supposed to return, and it should be specified.

In some places in the code you check the return value of this function and expect it to be a string, and check to see if it's `'granted'`. In other places you don't check the return the value - but if you're checking for `'granted'` even in a single place - then it's implied that this function returns `'granted'` when permissions are granted.

Yet here the function will return `null` in some cases when permissions are `'granted'`. That is very confusing and I think will lead to bugs.

Comment (Silver-IT) [reply frontend/model/contracts/shared/nativeNotification.js]: > What if Notification.permission is === 'granted' here? It would return null but we want this to return 'granted' in that case...

The main purpose of this condition is to skip when Notification is `undefined` or user has already replied.
Also it's good idea to return permission if Notification is not `undefined`.

File: frontend/model/contracts/chatroom.js (hunk 8 above)
Comment (taoeffect) [reply frontend/model/contracts/chatroom.js]: Right, but I asked if there was a reason that it has to be passed in here like this, instead of being stored when `addMessage` is called?

Can you add in a comment and explain the reason?

File: frontend/model/contracts/shared/nativeNotification.js (hunk 9 above)
Comment (taoeffect) [reply frontend/model/contracts/shared/nativeNotification.js]: OK, then the behavior should be changed to return `null` when `Notification` is `undefined`, and the permission otherwise.

*Edit: And also re-request permissions if `force` is `true` + return the permission

File: frontend/model/contracts/chatroom.js (hunk 8 above)
Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js]: Okay.

File: frontend/model/contracts/shared/nativeNotification.js (hunk 9 above)
Comment (Silver-IT) [reply frontend/model/contracts/shared/nativeNotification.js]:
```
export async function requestNotificationPermission (force: boolean = false): Promise<null | string> {
  if (typeof Notification === 'undefined') {
    return null
  } else if (!force && Notification.permission !== 'default') {
    return Notification.permission
  }
  try {
    return await Notification.requestPermission()
  } catch (e) {
    return null
  }
}
```

So, is this fine with you?

Comment (taoeffect) [reply frontend/model/contracts/shared/nativeNotification.js]: How about?

```js
export async function requestNotificationPermission (force: boolean = false): Promise<null | string> {
  if (typeof Notification === 'undefined') {
    return null
  }
  if (force) {
    try {
      return await Notification.requestPermission()
    } catch (e) {
      console.error('requestNotificationPermission:', e.message)
      return null
    }
  }
  return Notification.permission
}
```

Comment (Silver-IT) [reply frontend/model/contracts/shared/nativeNotification.js:9]: Much better.

Comment (Silver-IT) [reply frontend/model/contracts/shared/nativeNotification.js]: But your code missed one situation. When force is false and the permission is `default`.

Comment (Silver-IT) [reply frontend/model/contracts/shared/nativeNotification.js]:
```
export async function requestNotificationPermission (force: boolean = false): Promise<null | string> {
  if (typeof Notification === 'undefined') {
    return null
  }
  if (force || Notification.permission === 'default') {
    try {
      return await Notification.requestPermission()
    } catch (e) {
      console.error('requestNotificationPermission:', e.message)
      return null
    }
  }
  return Notification.permission
}
```

This could be perfect.

Comment (taoeffect) [reply frontend/model/contracts/shared/nativeNotification.js]: > But your code missed one situation. When force is false and the permission is default.

Good catch!!

Is this right?

```js
export async function requestNotificationPermission (force: boolean = false): Promise<null | string> {
  if (typeof Notification === 'undefined') {
    return null
  }
  if (force || Notification.permission === 'default') {
    try {
      return await Notification.requestPermission()
    } catch (e) {
      console.error('requestNotificationPermission:', e.message)
      return null
    }
  }
  return Notification.permission
}
```

Comment (taoeffect) [reply frontend/model/contracts/shared/nativeNotification.js]: > This could be perfect.

We both wrote the same thing 😄

Comment (Silver-IT) [reply frontend/model/contracts/shared/nativeNotification.js]: Hahaha. Sure. Not only right. It's perfect.

File: contracts/0.0.1/group-slim.js [hunk 10]
```diff
@@ -1464,7 +1464,7 @@ ${this.getErrorInfo()}`;
           }
         },
         process({ data, meta }, { state }) {
-          import_common2.Vue.delete(state.chatRooms, data.chatRoomID);
+          import_common2.Vue.delete(state.chatRooms[data.chatRoomID]);
```
Comment (taoeffect) [inline contracts/0.0.1/group-slim.js]: Looks like this got reverted in the recent commit. Did you undo the `grunt pin:0.0.1` that you did earlier? Remember you need to delete the old `contracts/0.0.1` folder and run that command each time you update this PR.

Comment (Silver-IT) [reply contracts/0.0.1/group-slim.js]: I removed `0.0.1` folder and run `grunt pin:0.0.1`. Also I tried it again just before but it works that way.
Weird...

Comment (Silver-IT) [reply contracts/0.0.1/group-slim.js]: However, It's a really nice catch...

Comment (Silver-IT) [reply contracts/0.0.1/group-slim.js]: Should I run `grunt dev` and then `grunt pin:0.0.1`?

Comment (Silver-IT) [reply contracts/0.0.1/group-slim.js]: I did this way and it is resolved...

File: frontend/views/containers/user-settings/NotificationSettings.vue [hunk 11]
```diff
@@ -1,20 +1,52 @@
...
+      if (permission !== null) {
+        permission = await requestNotificationPermission(true)
+      }
+      if (!this.granted && (permission === 'granted')) {
+        makeNotification({
+          title: L('Congratulations'),
+          body: L('You have granted browser notification!')
+        })
+      }
+      this.$refs.permission.checked = this.granted = permission === 'granted'
```
Comment (taoeffect) [inline frontend/views/containers/user-settings/NotificationSettings.vue]: OK, this is my fault @Silver-IT - I gave you a somewhat problematic review earlier — my apologies!! 🙇‍♂️

You were right - we do need a setting in the user settings for whether or not notifications are enabled, because there's no way to tell Firefox to disable the notifications once the permissions have been granted.

Thankfully, I don't think `chatroom.js` needs to be modified.

The only modifications that are needed are in this file (to check and toggle the user setting), `state.js` (to add the setting), and two functions in `nativeNotifications.js`.

Something like this for `requestNotificationPermission`:

```js
export async function requestNotificationPermission (force: boolean = false): Promise<null | string> {
  if (typeof Notification === 'undefined') {
    return null
  }
  if (force || Notification.permission === 'default') {
    try {
      const permission = await Notification.requestPermission()
      sbp('state/vuex/commit', 'setNotificationsEnabled', permission === 'granted')
    } catch (e) {
      console.error('requestNotificationPermission:', e.message)
      return null
    }
  }
  return Notification.permission
}
```

And something like this for `makeNotification`:

```js
export function makeNotification ({ title, body, icon, path }: {
  title: string, body: string, icon?: string, path?: string
}): void {
  const notificationsEnabled = sbp('state/vuex/state').notificationsEnabled
  if (typeof Notification === 'undefined' || Notification.permission !== 'granted' || !notificationsEnabled) {
    return
  }

  const notification = new Notification(title, { body, icon })
  if (path) {
    notification.onclick = function (event) {
      event.preventDefault()
      sbp('controller/router').push({ path }).catch(console.warn)
    }
  }
}
```

**Review by taoeffect — CHANGES_REQUESTED** [review]
Great work @Silver-IT - something was messed up by my earlier review - sorry! See comment:

File: frontend/views/containers/user-settings/NotificationSettings.vue (hunk 11 above)
Comment (Silver-IT) [reply frontend/views/containers/user-settings/NotificationSettings.vue]: > There's no way to tell Firefox to disable the notifications once the permissions have been granted.

Yeah. It's same in the Google Chrome. That's why I made this.
```
this.$refs.permission.checked = this.granted = permission === 'granted'
```
So switch will not be changed **unless user reset the notification permission and set the permission again**.

Comment (taoeffect) [reply frontend/views/containers/user-settings/NotificationSettings.vue]: Right, but doing it this way means that there's no way to uncheck the button, and notifications are always enabled, even if the user wants to disable them.

Comment (Silver-IT) [reply frontend/views/containers/user-settings/NotificationSettings.vue]: It's same as if user wants to enable after he denied the permission.
User needs to reset permission anyway.

Comment (taoeffect) [reply frontend/views/containers/user-settings/NotificationSettings.vue]: @Silver-IT If we are offering the user a checkbox, then the user should be able to easily disable the notifications using this checkbox. Right now it doesn't work - clicking on the checkbox does nothing after notifications permissions have been granted.

We need this to behave in the way users expect: for notifications to stop when they uncheck the checkbox. And since there is no API to disable notifications permissions, we do have to add an extra variable to the state.

Comment (Silver-IT) [reply frontend/views/containers/user-settings/NotificationSettings.vue]: Yeah. This is what I thought.
But users will see that switch component doesn't work unless they reset notification permission.
Could it be helpful for the users to know why it doesn't work and make him to reset browser permission?

Comment (taoeffect) [reply frontend/views/containers/user-settings/NotificationSettings.vue]: Yep! Per the discussion on Slack, in such instances we can let them know via an `alert`

**Review by taoeffect — APPROVED** [review]
Great work @Silver-IT! Approved! 😄
