### PR TITLE
Bugfixes

### LINKED ISSUE #2916: Cannot read properties of undefined (reading 'status')
### Problem

After re-logging in to groupincome.app and reload everything from scratch I saw this error in the console:

Image

### Solution

I'm not 100% sure but I think it could be this code in the group contract:

Image

```js
          if (profiles[innerSigningContractID].status !== PROFILE_STATUS.ACTIVE) {
            return
          }
```

I don't see any other `.status` call that could be the culprit.

### LINKED ISSUE #2919: Fatal error upon changing group mincome: "Tried to access currentGroupState from outside a browsing context"
### Problem

Steps to reproduce:
- In the testing server, create an account, then a group
- In "My income details", check "Yes" and fill in some pledge amount
- Change the mincome amount via the "Change" link in the right panel behind the "i" button

Image

The same steps taken locally on master yield the following error and logs:

Image

[gi_logs.json(1).txt](https://github.com/user-attachments/files/22667128/gi_logs.json.1.txt)

### PR DESCRIPTION
**Pull request by corrideat**
Closes #2916
Closes #2919

### CODE REVIEW

File: frontend/model/contracts/shared/getters/group.js [hunk 1]
```diff
@@ -123,8 +123,13 @@ export default ({
   groupMincomeAmount (state, getters) {
     return getters.groupMincomeAmountForGroup(getters.currentGroupState)
   },
+  groupMincomeCurrencyForGroup (state, getters) {
+    return state => {
+      return getters.groupSettingsForGroup(state).mincomeCurrency
```
Comment (taoeffect) [inline frontend/model/contracts/shared/getters/group.js:128]: Does this need the optional chaining before `.mincomeCurrency` for consistency?

Similar question for:

```js
groupMincomeAmountForGroup (state, getters) {
  return state => getters.groupSettingsForGroup(state).mincomeAmount
},
```

Comment (corrideat) [reply frontend/model/contracts/shared/getters/group.js:128]: If you mean:

`getters.groupSettingsForGroup(state)?.mincomeAmount`

Then, no, because this is how `groupSettingsForGroup` is defined (arguably, we could do optional chaining in `groupSettingsForGroup`, like this, `state?.settings || {}`, so that it'll never throw, but we don't seem to have needed that so far).

```js
  groupSettingsForGroup (state, getters) {
    return (state) => state.settings || {}
  },
```

**Review by taoeffect — APPROVED** [review]
Great work @corrideat! 👏
