### PR TITLE
Fix SBP warnings for already registered selectors

### LINKED ISSUE #2871: [SBP WARN]: not registering already registered selector
### Problem

Ever since merging support for `@chelonia/lib` we've been seeing these extra warnings in both the server, the workers on the server, and the frontend:

Image
Image

### Solution

Find out why this is happening. It seems like the same library is being bundled multiple times and therefore this is happening... not entirely sure exactly what the problem is though.

### PR DESCRIPTION
**Pull request by snowteamer**
Closes #2871 

### Summary of changes:
- Bumped `@sbp/okturtles.*` dependencies to match versions used in `@chelonia/lib`:
    - @sbp/okturtles.data: 0.1.5 -> 0.1.7
    - @sbp/okturtles.eventqueue: 1.2.0 -> 1.2.1
    - @sbp/okturtles.events: 1.0.0 -> 1.0.1

### CODE REVIEW

File: backend/server.js [hunk 1]
```diff
@@ -668,3 +668,34 @@ sbp('okTurtles.data/set', PUBSUB_INSTANCE, createServer(hapi.listener, {
...
+      repl.on('exit', () => {
+        socket.end()
+      })
+      // $FlowIgnore
+      repl.context.socket = socket
+      // $FlowIgnore
+      Object.assign(repl.context, imports)
+    }).listen(1337)
+  })()
+}
```
Comment (taoeffect) [inline backend/server.js]: What is this code... why is it here, why's it starting a server on 1337?

Comment (taoeffect) [reply backend/server.js]: Oh OK, @corrideat explained to me on today's call that this creates a repl that can be accessed via `telnet` that lets you run commands on the server.

This is pretty cool but it's not relevant to closing this issue, and also we're about to remove the entire `backend/` folder once #2961 is merged. So feel free to send a PR along these lines after creating an issue in https://github.com/okTurtles/chel/ and sending a PR there

File: package.json [hunk 2]
```diff
@@ -122,9 +122,9 @@
     "@hapi/hapi": "20.1.2",
     "@hapi/inert": "6.0.3",
     "@hapi/joi": "17.1.1",
-    "@sbp/okturtles.data": "0.1.5",
-    "@sbp/okturtles.eventqueue": "1.2.0",
-    "@sbp/okturtles.events": "1.0.0",
+    "@sbp/okturtles.data": "0.1.7",
+    "@sbp/okturtles.eventqueue": "1.2.1",
+    "@sbp/okturtles.events": "1.0.1",
```
Comment (taoeffect) [inline package.json:127]: Did you want to make these use `~`?

File: backend/server.js (hunk 1 above)
Comment (corrideat) [reply backend/server.js]: I agree with @taoeffect's assessment, and this will result in a merge conflict with #2961. I suggest proceeding as follows, since this seems like a useful feature:

1. Delete all of these changes (so, the only changes in this PR would be the version bumps)
2. Here you have two options:
  a. Create an issue on [chel](https://github.com/okTurtles/chel/) for adding this feature (you could copy this snippet / diff so that we don't have to do the work again); or
  b. Create a PR on [chel](https://github.com/okTurtles/chel/) adding this feature to the `chel serve` command. It should have the following modifications:
     1. The 1337 default is fine, but it should be configurable (see how we use nconf and yargs for settings)
     2. I think we might also want to have this for production, so adding a CLI flag to enable the REPL server could be best.

Comment (corrideat) [reply backend/server.js]: On another note, check if the imports here make sense. In particular, importing `import('@chelonia/lib')` along with `import('@chelonia/lib/<something else>')` is generally discouraged, since the former usually implies the latter.

**Review by corrideat — DISMISSED** [review]
Approved, but please revert changes to `server.js` before merging.

File: backend/server.js (hunk 1 above)
Comment (snowteamer) [reply backend/server.js]: @taoeffect This is some local dev stuff that I apparently forgot to remove. My apologies!

File: package.json (hunk 2 above)
Comment (snowteamer) [reply package.json:127]: I did suggest it, but in the meantime I went ahead and made this PR without ~.

**Review by taoeffect — APPROVED** [review]
Thank you @snowteamer !
