### PR TITLE
#2907 - Anchor-link issue

### LINKED ISSUE #2907: Make anchor links work properly in rendered markdown links
### Problem

As a followup to #2891, the one link type that doesn't work now is the anchor link, e.g.: `[link](/app/dashboard#proposals)`.

To test this, I had to hackishly add a named anchor link to `ProposalsWidget.vue`: as `  a(name='proposals') &nbsp;`:

```pug
component(
  :is='componentData.type'
  v-bind='componentData.props'
  :class='{ "c-has-extra-bottom-margin": ephemeral.isMenuOpen }'
  data-test='proposalsSection'
)
  a(name='proposals') &nbsp;
  template(#cta='')
```

Then I made the window height small, posted `[link](/app/dashboard#proposals)` to the chat, and clicked it.

### Solution

Find out why these types of links don't seem to work and fix. They could be useful in directly users to very specific elements on page.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #2907

### CODE REVIEW

File: frontend/views/components/Page.vue [hunk 1]
```diff
@@ -84,6 +84,22 @@ export default ({
...
+  watch: {
+    '$route': {
+      immediate: true,
+      handler (to, from) {
+        if (to.hash && from?.hash !== to.hash) {
+          setTimeout(() => {
+            this.findAndScrollToAnchor(to.hash.slice(1))
+          }, 100)
+        }
+      }
```
Comment (SebinSong) [inline frontend/views/components/Page.vue:107]: Scrolling down to a specific anchor point via specifying `#string` is a browser's native behavior. But for some reason, this does not work reliably in our app(I've observed this in some other SPA websites at the other company) so we need a logic to handle this manually. Since `Page.vue` is used in all pages, decided this is the good place for it.

File: frontend/views/components/PageSection.vue [hunk 2]
```diff
@@ -21,24 +21,6 @@ export default ({
...
-    '$route': {
-      immediate: true,
-      handler (to, from) {
-        if (to.hash &&
-          (from?.hash !== to.hash) &&
-          `#${this.anchor}` === to.hash) {
-          setTimeout(this.scrollToAnchor, 100)
-        }
-      }
-    }
```
Comment (SebinSong) [inline frontend/views/components/PageSection.vue:41]: moved this logic to `Page.vue` and made it more general.

File: frontend/views/components/Page.vue [hunk 3]
```diff
@@ -84,6 +84,22 @@ export default ({
     },
     checkIsTouch () {
       this.ephemeral.isTouch = window.innerWidth < DESKTOP
+    },
+    findAndScrollToAnchor (str) {
+      const anchorEl = this.$el.querySelector(`:is([id='${str}'], [name='${str}'], [href='#${str}'])`)
+      anchorEl && anchorEl.scrollIntoView({ behavior: 'smooth', block: 'start' })
+    }
```
Comment (taoeffect) [inline frontend/views/components/Page.vue:96]: Sonnet 4.5 had some good suggestions here:

<details>


## 🔴 Security Issue: CSS Selector Injection

In `frontend/views/components/Page.vue`, the `findAndScrollToAnchor` method is vulnerable to CSS selector injection:

```javascript
findAndScrollToAnchor (str) {
  const anchorEl = this.$el.querySelector(`:is([id='${str}'], [name='${str}'], [href='#${str}'])`)
  anchorEl && anchorEl.scrollIntoView({ behavior: 'smooth', block: 'start' })
}
```

**Problem:** If `str` contains special CSS characters like quotes, backslashes, or parentheses, it could break the selector or cause errors. Since this value comes from `to.hash` (the URL hash), it's user-controlled input.

**Fix:** Escape the string or use a safer approach:

```javascript
findAndScrollToAnchor (str) {
  // Sanitize the string by using getElementById or escaping special chars
  const anchorEl = document.getElementById(str) || 
                   this.$el.querySelector(`[name="${CSS.escape(str)}"]`)
  anchorEl && anchorEl.scrollIntoView({ behavior: 'smooth', block: 'start' })
}
```

Or even simpler, since you're setting `id` attributes in the components:

```javascript
findAndScrollToAnchor (str) {
  const anchorEl = document.getElementById(str)
  anchorEl && anchorEl.scrollIntoView({ behavior: 'smooth', block: 'start' })
}
```

## 🟡 Logic Issue: Incorrect Selector

```javascript
const anchorEl = this.$el.querySelector(`:is([id='${str}'], [name='${str}'], [href='#${str}'])`)
```

**Problem:** The `[href='#${str}']` part matches links that *point to* the anchor, not the anchor itself. This seems incorrect for the intended purpose.

**Fix:** Remove the href selector since you want to find the target element, not links pointing to it:

```javascript
const anchorEl = document.getElementById(str) || 
                 this.$el.querySelector(`[name="${CSS.escape(str)}"]`)
```

## 🟡 Timing Issue: Arbitrary setTimeout

```javascript
setTimeout(() => {
  this.findAndScrollToAnchor(to.hash.slice(1))
}, 100)
```

**Problem:** The 100ms timeout is arbitrary and may not be sufficient for slow renders or large DOMs. It could also fire too early.

**Fix:** Use `$nextTick` or wait for the component to be fully mounted:

```javascript
handler (to, from) {
  if (to.hash && from?.hash !== to.hash) {
    this.$nextTick(() => {
      this.findAndScrollToAnchor(to.hash.slice(1))
    })
  }
}
```

## 🟢 Suggestion: Consider Accessibility

The previous implementation clicked on an anchor link, which has better accessibility implications (focus management, browser history, etc.). Your new implementation scrolls but doesn't manage focus.

**Consider adding:**

```javascript
findAndScrollToAnchor (str) {
  const anchorEl = document.getElementById(str)
  if (anchorEl) {
    anchorEl.scrollIntoView({ behavior: 'smooth', block: 'start' })
    // Set focus for accessibility if the element is focusable
    if (anchorEl.tabIndex >= 0 || anchorEl.hasAttribute('tabindex')) {
      anchorEl.focus()
    }
  }
}
```

## Questions

1. Why did you move the scroll logic from `PageSection.vue` to `Page.vue`? Was there an issue with the previous per-section approach?
2. Are there other components besides `PageSection` and `CalloutCard` that need anchor scrolling support?

</details>

I agree that for example `[href='#${str}']` isn't something we want to match.

So I would do a combination of:

```js
findAndScrollToAnchor (str) {
  // Sanitize the string by using getElementById or escaping special chars
  const anchorEl = document.getElementById(str) || 
                   this.$el.querySelector(`[name="${CSS.escape(str)}"]`)
  anchorEl && anchorEl.scrollIntoView({ behavior: 'smooth', block: 'start' })
}
```

And the accessibility advice it gave so that the section or element becomes focused:

```js
    // Set focus for accessibility if the element is focusable
    if (anchorEl.tabIndex >= 0 || anchorEl.hasAttribute('tabindex')) {
      anchorEl.focus()
    }
```

**Review by taoeffect — CHANGES_REQUESTED** [review]
Tested it and it works great, fantastic job @SebinSong!

I made one minor change request based on something Sonnet 4.5 noticed:

**Review by taoeffect — APPROVED** [review]
Nice work @SebinSong! 👍
