### PR TITLE
Fix new CSS assets not being used after a rebuild

### LINKED ISSUE #1099: New CSS assets are not used after a rebuild
### Problem

After changing a .scss file, new versions of `main.css` and `main.css.map` are created and and output to `main.js`'s directory.
However, they remain unused since our `index.html` tries to load them from `dist/assets/css`, where only outdated versions are available.

### Solution

Some ideas:
- Make esbuild redirect CSS asset output to the correct directory.
- Implement logic to move the relevant files after a rebuild occured.
- Change `index.html` to load both `main.css` and `main.js` from the same directory.

### PR DESCRIPTION
**Pull request by snowteamer**
Closes #1099

Fixes the relevant issue by copying new `main.css` and `main.css.map` over to the correct location.

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -427,6 +426,14 @@ module.exports = (grunt) => {
             await buildServiceWorkers.run()
           } else {
             await buildMain.run()
+            if (['.css', '.sass', '.scss'].includes(extension)) {
+              // Esbuild outputs `main.css` and `main.css.map` along `main.js`,
+              // but `index.html` wants to load them from `dist/assets/css`.
+              await fs.promises.copyFile(`${distJS}/main.css`, `${distCSS}/main.css`)
+              if (buildMain.options.sourcemap) {
+                await fs.promises.copyFile(`${distJS}/main.css.map`, `${distCSS}/main.css.map`)
+              }
```
Comment (taoeffect) [inline Gruntfile.js]: This seems very granular of a way to do it, very specific to esbuild as well, which will make it more difficult to close #1085, I think. Have you considered doing it using the existing `grunt-contrib-copy` stuff that we have, or in a more generic way that is less specific to esbuild integration?

**Review by taoeffect — COMMENTED** [review]
Good catch @snowteamer. I left a question.

File: Gruntfile.js (hunk 1 above)
Comment (snowteamer) [reply Gruntfile.js]: Indeed, and it also introduces a bit of code duplication since the same copying operation occurs on the first build.

So I've considered specifying this post-build operation as a custom option, then thought it was better to keep things simple for now; but I should be able to add it if you don't mind the extra option.

I it is also possible via `grunt copy`, but I think it would still be as much specific to esbuild as plain code, and likely a bit slower. I'm also slightly reluctant to increase our dependency to Grunt since we might want to switch to Snowpack later.

Comment (taoeffect) [reply Gruntfile.js]: Would the post-build option would help with #1085 and DRY the code more?

If so, then I think it's worth doing.

Comment (snowteamer) [reply Gruntfile.js]: I think so since this copying operation might not be needed with other build tools, or they might require doing something else.

**Review by taoeffect — CHANGES_REQUESTED** [review]
Per the convo here: https://github.com/okTurtles/group-income-simple/pull/1100/files#r710204644

Implement the copying part using a post-build option to DRY things and help with #1085

File: scripts/esbuild-commands.js [hunk 2]
```diff
@@ -3,32 +3,51 @@
...
+    async rerun ({ fileEventName, filePath }) {
+      const { state } = this
+
+      if (!state.result || !esbuildOptions.incremental) {
+        throw new Error('Cannot use rerun() on this task. Use run() instead.')
+      }
+      await state.result.rebuild()
+
+      if (otherOptions.postoperation) {
+        await otherOptions.postoperation({ fileEventName, filePath })
```
Comment (taoeffect) [inline scripts/esbuild-commands.js]: These two functions, `run` and `rerun`, are nearly identical except for the difference between:

```js
      state.result = await esbuild.build(esbuildOptions)
```

And:

```js
      await state.result.rebuild()
```

Couldn't therefore the logic be simplified so that there is only a single `run` function that keeps track of whether or not it has already been called before, and proceeds accordingly?

Comment (snowteamer) [reply scripts/esbuild-commands.js]: There was indeed a single `run()` method before, which used `state.result` to check whether it had already been called.

Since additional arguments must now be accepted when a rebuild occurs, I've been considering whether `run()` should be split in two distinct methods with different signatures, rather than a single catch-all method which accepts optional arguments.
Besides, esbuild itself also has both `build()` and `rebuild()` methods.

It's a tradeoff between two simpler functions and a more complex one.
So I've tried this approach somewhat as an experiment, but I don't mind also trying the monolithic method.

Comment (taoeffect) [reply scripts/esbuild-commands.js]: In your estimation, which approach would make more sense from the perspective of creating a build system that is agnostic to the underlying bunder? (i.e., issue #1085)?

Comment (snowteamer) [reply scripts/esbuild-commands.js]: Both should be roughly equivalent in that respect at first guess (I might be wrong though).
In any case, issue #1085 will likely involve several refactorings.

**Review by taoeffect — APPROVED** [review]
Approved! Great catch @snowteamer! (My bad for not catching it originally!)
