### PR TITLE
Fix issue 1629

### LINKED ISSUE #1629: Page doesn't refresh on new version
### Problem

Try the following:

1. Delete `data/groupincome.db` and run `GI_PERSIST=sqlite grunt dev`
2. Create a group and go to the chatroom, post a message
3. Stop the server with `^C` and make some changes to the chatroom contract, then run `grunt pin:0.1.5`
4. Run `GI_PERSIST=sqlite grunt dev` again

The open page you were logged in on will reconnect but won't refresh. It should refresh.

### Solution

Find and fix bug.

### PR DESCRIPTION
**Pull request by snowteamer**
Closes #1629

### Summary of changes:
- New `process.env.CONTRACTS_VERSION`  field available, taken from `package.json`'s `contractsVersion`.
- The server will now send both its current `GI_VERSION` and `CONTRACTS_VERSION` to the client on every (re)connection, including in development mode, allowing it to reload if necessary (fix issue #1629).
- Fixed a bug causing the server to not log ping rounds despite the option being enabled.
-

### CODE REVIEW

File: backend/pubsub.js [hunk 1]
```diff
@@ -107,7 +107,7 @@ export function createServer (httpServer: Object, options?: Object = {}): Object
   // Setup a ping interval if required.
   if (server.options.pingInterval > 0) {
     server.pingIntervalID = setInterval(() => {
-      if (server.clients.length && server.options.logPingRounds) {
+      if (server.clients.size && server.options.logPingRounds) {
```
Comment (Silver-IT) [inline backend/pubsub.js:110]: Nice catch. `server.clients` is `Set` object which has `size` instead of `length`.

File: frontend/controller/backend.js [hunk 2]
```diff
@@ -13,8 +13,8 @@ const languageFileMap = new Map([
   ['fr', 'french.json']
 ])
 
-sbp('okTurtles.events/on', NOTIFICATION_TYPE.APP_VERSION, (version) => {
-  console.info('New Group Income version available:', version)
+sbp('okTurtles.events/on', NOTIFICATION_TYPE.UPDATE_AVAILABLE, (versionInfo) => {
```
Comment (Silver-IT) [inline frontend/controller/backend.js]: I think it should be `NOTIFICATION_TYPE.VERSION_INFO` instead of `NOTIFICATION_TYPE.UPDATE_AVAILABLE`.

File: shared/domains/chelonia/chelonia.js [hunk 3]
```diff
@@ -148,12 +148,14 @@ export default (sbp('sbp/selectors/register', {
...
           const ourVersion = process.env.GI_VERSION
-          const theirVersion = msg.data
+          const theirVersion = msg.data.GI_VERSION
 
-          if (ourVersion !== theirVersion) {
-            sbp('okTurtles.events/emit', NOTIFICATION_TYPE.APP_VERSION, theirVersion)
+          const ourContractsVersion = process.env.CONTRACTS_VERSION
+          const theirContractsVersion = msg.data.CONTRACTS_VERSION
+          if (ourVersion !== theirVersion || ourContractsVersion !== theirContractsVersion) {
+            sbp('okTurtles.events/emit', NOTIFICATION_TYPE.UPDATE_AVAILABLE, { ...msg.data })
```
Comment (Silver-IT) [inline shared/domains/chelonia/chelonia.js]: I also think this should be `VERSION_INFO` instead of `UPDATE_AVAILABLE`.

File: frontend/controller/backend.js (hunk 2 above)
Comment (Silver-IT) [reply frontend/controller/backend.js]: Or should add `UPDATE_AVAILABLE` in `NOTIFICATION_TYPE`.

**Review by Silver-IT — CHANGES_REQUESTED** [review]
Great work, @snowteamer. Left a few feedback.

File: shared/domains/chelonia/chelonia.js (hunk 3 above)
Comment (snowteamer) [reply shared/domains/chelonia/chelonia.js]: Yeah there was an inconsistency here, thank you for noticing!

**Review by taoeffect — APPROVED** [review]
Great work @snowteamer! Tested & approved!
