### PR TITLE
Closes #2072 - capture tunnel logs

### LINKED ISSUE #2072: Capture dev tunnel logs on server
### Problem

When testing via `grunt dev --tunnel` a lot of things seem to go wrong and it's difficult on a phone to know what happened.

Although it's possible to capture logs via a USB cable in some situations, this is inconvenient and not always possible.

### Solution

Send the logs directly to the server and have the server log them whenever we're in development mode and the page is loaded over the tunnel.

### PR DESCRIPTION
**Pull request by taoeffect**
Captures phone logs to server console run accessing via `grunt dev --tunnel`.

Adds new `'appLogs/logServer'` selector that can be called manually if necessary before the log capture begins (when login is called). Generally speaking you won't need to call this manually and the logs will appear automatically on the backend, color coded.

### CODE REVIEW

File: frontend/model/captureLogs.js [hunk 1]
```diff
@@ -189,5 +190,20 @@ sbp('sbp/selectors/register', {
   'appLogs/get' () { return getLogger()?.entries?.toArray() ?? [] },
   'appLogs/save' () { getLogger()?.save() },
   'appLogs/pauseCapture': captureLogsPause,
-  'appLogs/startCapture': captureLogsStart
+  'appLogs/startCapture': captureLogsStart,
+  'appLogs/logServer': process.env.NODE_ENV !== 'development' || !window.location.href.startsWith('https://gi')
+    ? noop
+    : function (level, stringifyMe) {
+      if (level === 'debug') return // comment out to send much more log info
+      const string = JSON.stringify(stringifyMe)
```
Comment (Silver-IT) [inline frontend/model/captureLogs.js]: I would like to change name from `string` to `value` since `string` is the name of type.

File: frontend/model/captureLogs.js [hunk 2]
```diff
@@ -189,5 +190,20 @@ sbp('sbp/selectors/register', {
   'appLogs/get' () { return getLogger()?.entries?.toArray() ?? [] },
   'appLogs/save' () { getLogger()?.save() },
   'appLogs/pauseCapture': captureLogsPause,
-  'appLogs/startCapture': captureLogsStart
+  'appLogs/startCapture': captureLogsStart,
+  'appLogs/logServer': process.env.NODE_ENV !== 'development' || !window.location.href.startsWith('https://gi')
```
Comment (Silver-IT) [inline frontend/model/captureLogs.js:196]: What does `'https://gi'` mean?

**Review by Silver-IT — CHANGES_REQUESTED** [review]
Nice work, @taoeffect! It works well.

File: frontend/model/captureLogs.js (hunk 2 above)
Comment (SebinSong) [reply frontend/model/captureLogs.js:196]: Seems like `L:194` here is for specifically filtering the app run by `grunt dev --tunnel`. I noticed every external https URL created by it always starts with `https://gi...`.

**Review by SebinSong — DISMISSED** [review]
LGTM

File: frontend/model/captureLogs.js (hunk 2 above)
Comment (Silver-IT) [reply frontend/model/captureLogs.js:196]: Yeah, I remember. 👍

**Review by Silver-IT — APPROVED** [review]
LGTM! Nice work! 👍
