### PR TITLE
#2721 - Fix the scroll-position bug

### LINKED ISSUE #2721: ChatMain no longer remember scroll position
### Problem

Image

I'm not sure what happened. Perhaps some recent changes to ChatMain broke its ability to remember scroll positions.

Switching on GIG between `#random` and `#general` doesn't remember scroll position, and seems stuck for me on an old message. In other words, it doesn't scroll to the end as it shou.d

### Solution

Fix.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #2721 

https://github.com/user-attachments/assets/f22f285e-3c8c-402f-81b1-88a1b13862ab

### CODE REVIEW

File: frontend/views/containers/chatroom/ChatMain.vue [hunk 1]
```diff
@@ -887,6 +887,28 @@ export default ({
...
+            if (scrollingToSpecificMessage) {
+              const newQuery = { ...this.$route.query }
+              delete newQuery.mhash
+              this.$router.replace({ query: newQuery })
+            }
+
+            // This ensures that scroll-to-specific-message (or to the latest message) happens one time after the initial chatroom load.
+            this.ephemeral.scrollHashOnInitialLoad = null
+          })
+        }
```
Comment (SebinSong) [inline frontend/views/containers/chatroom/ChatMain.vue:911]: From more thorough investigation, this appears to be a better place to execute the `initial-scroll` logic. From my observation, executing this logic from the original place (L1092 below) seemed premature especially when the chatroom has many image attachments. This leads to a situation like below for example,

[1] Some messages are rendered.
[2] initial-scroll logic is executed.
[3] Images that are rendered later causes the scroll-height of the chatroom to increase.
[4] This leads to a sudden jump of the scroll position.

After moving this logic here, I have not observed this happening again.

**Review by taoeffect — COMMENTED** [review]
Interesting! @SebinSong - I've verified that this seems to fix the problem on my end, nice work!

Does this count though as a logic fix? It seems to leave the logic the same and just mess with the timings a bit. Are you sure this will be sufficient under all circmstances?

**Comment by SebinSong** [comment]
@taoeffect 
Yes, the logics for **1.** remembering the scroll-position in `onChatScroll` method **2.** determining the initial scroll-position during the initial message-chain render and auto-scroll to it are actually not broken and are in the same places as they were.

I've actually spent a while yesterday trying to fix the issue by moving 2. above to somewhere else, but these little adjustments to the delay values were the best fix I could find so far..

Let me maybe spend some more time exploring/trying the APIs `vue-infinite-loading` provides, just to see if there is a better fix and then give you a heads up if any changes. (Or you could merge this PR as is).

**Comment by SebinSong** [comment]
@taoeffect PR is ready for review again.

There isn't anything useful in `vue-infinite-loading`'s API (it only provides 1 event which is`@infinite`), so I've actually had to come up with a logic using setTimeout/clearTimeout pair. From my local testing with relatively large size chatroom(80+ messages with lots of attachments), This fix works most consistently so far, so updated the PR with it.

Thanks.

**Review by taoeffect — APPROVED** [review]
Seems to work well, great job @SebinSong!
