### PR TITLE
Various bugfixes:

### LINKED ISSUE #2066: Testing site broken (private chatroom not syncing across devices)
### Problem

1. While desktop computer was asleep, I created a private chatroom on my phone via the PWA
2. Posted a few messages to it
3. Woke up computer and did not see the chatroom listed. No errors in console. Refreshing page doesn't fix it! However, opening a private window and re-logging in there does show the private chatroom.

Phone PWA:

tmp-1718337318871

Desktop:

Screenshot 2024-06-13 at 8 54 54 PM

### Solution

Find and fix the problem.

### LINKED ISSUE #2093: TypeError in internals related to OP_KEYSHARE
### Problem

While testing #2011 I ran into a surprising error when u2 joined a group:

Screenshot 2024-06-18 at 7 44 45 PM_resized

Here's the code near the top of the exception stack:

Screenshot 2024-06-18 at 7 44 53 PM_resized
Screenshot 2024-06-18 at 7 45 00 PM_resized
Screenshot 2024-06-18 at 7 45 26 PM_resized

And here are all of the events just preceding the exception:

Screenshot 2024-06-18 at 8 04 00 PM

### Solution

Find and fix.

### PR DESCRIPTION
**Pull request by corrideat**
- Comments explaining retain / release logic
- Closes #2093
- #2066 (potential fix)

### CODE REVIEW

**Review by taoeffect — APPROVED** [review]
Nice comments!

File: frontend/model/contracts/group.js [hunk 1]
```diff
@@ -1768,29 +1784,18 @@ sbp('chelonia/defineContract', {
...
+          encryptionKeyId
         }).catch(e => {
           if (e.name === 'GIErrorUIRuntimeError' && e.cause?.name === 'GIChatroomAlreadyMemberError') {
-            if (actorID === memberID) {
-              // Increase reference count if we've already joined
-              // Note: this addresses syncing the contract from a new device,
-              // where `retain` in postpublish hasn't been called and the
-              // reference count is zero due to the state being fresh.
-              sbp('chelonia/contract/retain', chatRoomID)
-            }
```
Comment (taoeffect) [inline frontend/model/contracts/group.js:1787]: Nice simplification!
