### PR TITLE
Better error handling. Closes #2522.

### LINKED ISSUE #2522: Regression introduced in PendingApproval.vue
### Problem

When creating a group and joining it for the first time (while testing Sebin's PR #2521), I saw this:

Image

This is caused by recently merged code here:

Image

Note that this did not prevent the group from being joined eventually, but it is a bug that needs to be fixed.

### Solution

Fix the bug.

### PR DESCRIPTION
**Pull request by corrideat**

### CODE REVIEW

File: shared/domains/chelonia/localSelectors.js [hunk 1]
```diff
@@ -90,5 +91,23 @@ export default (sbp('sbp/selectors/register', {
         sbp('okTurtles.events/emit', CONTRACTS_MODIFIED_READY, subscriptionSet, { added, removed })
       })
     })
+  },
+  'chelonia/externalStateWait': async function (contractID) {
```
Comment (taoeffect) [inline shared/domains/chelonia/localSelectors.js:98]: Above line 95 could you please give a detailed description of:

1. What this function is doing
2. Why it exists, e.g. the sorts of scenarios it should be used in

File: shared/domains/chelonia/localSelectors.js [hunk 2]
```diff
@@ -90,5 +91,23 @@ export default (sbp('sbp/selectors/register', {
...
+    await sbp('chelonia/contract/wait', contractID)
+    const { cheloniaState } = await sbp('chelonia/contract/fullState', contractID)
+    const localState = sbp(this.stateSelector)
+    if (cheloniaState.height >= localState.contracts[contractID]?.height) return
```
Comment (taoeffect) [inline shared/domains/chelonia/localSelectors.js]: A comment above this line saying what it's checking would be helpful too

File: shared/domains/chelonia/localSelectors.js [hunk 3]
```diff
@@ -90,5 +91,23 @@ export default (sbp('sbp/selectors/register', {
...
+
+    return new Promise((resolve) => {
+      const removeListener = sbp('okTurtles.events/on', EVENT_HANDLED_READY, (cID) => {
+        if (cID !== contractID) return
+
+        const localState = sbp(this.stateSelector)
+        if (cheloniaState.height >= localState.contracts[contractID]?.height) {
+          resolve()
+          removeListener()
```
Comment (taoeffect) [inline shared/domains/chelonia/localSelectors.js:116]: This seems somewhat odd, I rarely see any code after `resolve()`... would it make sense to flip these two lines so that `removeListener()` is called first?

**Review by taoeffect — CHANGES_REQUESTED** [review]
Review ready!

File: shared/domains/chelonia/localSelectors.js (hunk 3 above)
Comment (corrideat) [reply shared/domains/chelonia/localSelectors.js:116]: I don't think so. The idea here (and in general, I think) is to resolve when the promise should resolve. The cleanup code comes after `resolve()` because it doesn't affect the settlement of the promise. For example, if `removeListener()` should throw, it makes sense for the promise to still resolve. Investing the order would have a different effect.

**Review by taoeffect — APPROVED** [review]
Nice work @corrideat!
