### PR TITLE
Fix error in creating duplicated notifications while rejoining

### LINKED ISSUE #1838: Duplicated notifications after rejoining
### Problem

**Steps to reproduce**
- [Tab1] `u1` signs up, and creates a group
- [Tab2] `u2` joins the group
- [Tab3] `u3` joins the group
- [Tab1] `u1` creates two proposals; one to change mincome, and the other is generic
- [Tab3] `u3` leaves the group, and rejoins the group
- [Tab3] `u3` checks the duplicated notifications
image

**What should be happening**
- [Tab3] There should be no duplicated notifications

### Solution

Fix it

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of Changes

- Closes #1838

### CODE REVIEW

File: frontend/main.js [hunk 1]
```diff
@@ -553,8 +553,7 @@ async function startApp () {
       ...mapState(['contracts']),
       ourUnreadMessagesCount () {
         return Object.keys(this.ourUnreadMessages)
-          // TODO: need to remove the '|| []' after we release 0.2.*
-          .map(cId => (this.ourUnreadMessages[cId].unreadMessages || []).length)
```
Comment (taoeffect) [inline frontend/main.js:557]: Great catch!

File: frontend/model/contracts/group.js [hunk 2]
```diff
@@ -199,7 +199,7 @@ function memberLeaves ({ memberID, dateLeft, heightLeft }, { contractID, meta, s
   state._volatile.pendingKeyRevocations[CEKid] = true
 }
 
-function isActionOlderThanUser (contractID: string, height: number, userProfile: ?Object): boolean {
```
Comment (taoeffect) [inline frontend/model/contracts/group.js:202]: Also a nice catch 👍 

One problem though: this function is named incorrectly. It asks if the action is older than the user.

So if the action happened at block 15, and the user joined at block 20, then it should return true (because the action is "older than" when the user joined).

However, the condition below will do:

```
20 < 15 ===> false
```

So this function is named in the opposite way of how it should be.

Either the function needs to be renamed to `isActionNewerThanUserJoinedDate`, or the condition below needs to be reversed.

I recommend renaming the function, because that won't require changing the code that uses the function.

File: frontend/model/contracts/group.js [hunk 3]
```diff
@@ -830,7 +836,11 @@ sbp('chelonia/defineContract', {
           })
         }
 
-        sbp('gi.contracts/group/emitNotificationsAfterSyncing', contractID, notifications)
+        const { loggedIn } = sbp('state/vuex/state')
```
Comment (taoeffect) [inline frontend/model/contracts/group.js:821]: Since `'gi.contracts/group/emitNotifications'` does nothing significant anymore, it can be removed, and instead of calling it like this, `notifications` array can be deleted.

Then the loop above can be rewritten, something like this:

```js
if (isActionNewerThanUserJoinedDate(height, myProfile)) {
  for (const proposalId of data.proposalIds) {
    sbp('gi.notifications/emit', 'PROPOSAL_EXPIRING', {
      // ...
    })
  }
}
```

File: frontend/model/contracts/group.js [hunk 4]
```diff
@@ -1823,12 +1831,7 @@ sbp('chelonia/defineContract', {
         console.warn(`removeForeignKeys: ${e.name} error thrown:`, e)
       })
     },
-    'gi.contracts/group/emitNotificationsAfterSyncing': async (contractIDs, notifications) => {
-      const listOfIds = typeof contractIDs === 'string' ? [contractIDs] : contractIDs
-      for (const id of listOfIds) {
-        await sbp('chelonia/contract/wait', id)
-      }
-
+    'gi.contracts/group/emitNotifications': (notifications) => {
```
Comment (taoeffect) [inline frontend/model/contracts/group.js]: This method no longer does anything useful and therefore can be deleted

File: frontend/model/contracts/group.js [hunk 5]
```diff
@@ -982,21 +1004,7 @@ sbp('chelonia/defineContract', {
...
-                sbp('gi.contracts/group/emitNotificationsAfterSyncing', [], [{
-                  notificationName: 'MEMBER_ADDED',
-                  notificationData: {
-                    createdDate: meta.createdDate,
-                    groupID: contractID,
-                    memberID: innerSigningContractID
-                  }
-                }])
-              }
-            }).catch((e) => {
```
Comment (taoeffect) [inline frontend/model/contracts/group.js]: I do not see a good reason to move this code above. Can it be reverted?

**Review by taoeffect — CHANGES_REQUESTED** [review]
Great work @Silver-IT! Review ready!

File: frontend/model/contracts/group.js (hunk 2 above)
Comment (Silver-IT) [reply frontend/model/contracts/group.js:202]: I also think renaming is better. Nice catch!

File: frontend/model/contracts/group.js (hunk 5 above)
Comment (Silver-IT) [reply frontend/model/contracts/group.js]: Actually, the reason was to emit notification inside the invocation queue of syncing contracts. But since I blocked the duplicated notifications in notifications Vuex mutation, this could be reverted.

**Review by taoeffect — APPROVED** [review]
Great work @Silver-IT 👏
