### PR TITLE
fix preferred language not displaying

### LINKED ISSUE #2800: Preferred Language isn't respected in Brave and Firefox
### Problem

I added French as the preferred language and moved it to the top:

Image

Refreshed the testing site but it still shows up as English.

EDIT: same issue with Firefox too:

Image

Out of curiosity I tried switching in the macOS system preferences, but no luck either:

Image

### Solution

Find out why this is and fix.

### PR DESCRIPTION
**Pull request by taoeffect**
Closes #2800.

### CODE REVIEW

File: frontend/main.js [hunk 1]
```diff
@@ -49,6 +49,9 @@ console.info('CONTRACTS_VERSION:', process.env.CONTRACTS_VERSION)
 console.info('LIGHTWEIGHT_CLIENT:', process.env.LIGHTWEIGHT_CLIENT)
 console.info('NODE_ENV:', process.env.NODE_ENV)
 
+// this needs to be done early
```
Comment (corrideat) [inline frontend/main.js]: AFAICT, this is the only significant change in this entire PR. I'll preemptively approve this PR, but can you please re-write the comment to also explain _why_ this needs to be done early?

**Review by corrideat — DISMISSED** [review]

**Review by corrideat — APPROVED** [review]
