### PR TITLE
Improve Test Scenario & Fix UI Issues in Group Chat

### LINKED ISSUE #1327: Improve group chat test scenario
### Problem

We have very simple test scenario for the complex group chat functions.
The missing parts are
- `@` mentions and notifications and sounds by the mentions
- Saving and restoring the recent scroll position
- Saving and restoring the unread message and its updates
- Saving reply message and scroll to the target message when click it
- Infinite scroll [optional]
- ...

### Solution

Add test cases and make the Travis passed.

### LINKED ISSUE #1343: Design when the target message is deleted
### Problem

When user tries to scroll to the target message for a reply message.
image

In the Discord, it shows that the original message was deleted.
image
In Slack, nothing happens.
image

What should we do?

### Solution

Make design or let us know what we should do. Even say `Nothing will be happening.`

### LINKED ISSUE #1416: Absolute position of message container should be changed
### Problem

Message position should be changed while we reply messages and scroll up.
image
image

### Solution

Fix the absolute position of the message container considering the updated height of textarea.

### LINKED ISSUE #1420: Trying to get identity profile before sync the identity contract
### Problem

1. User1 creates a group and shares the invitation link with User2 and logs out.
2. User2 joins the group by the invitation link and goes to the group chat room (`General` channel)
3. User2 mentions User1 and logs out.
(In this situation, User1 has already logged out so he doesn't sync all the events of Group and Chatroom)
4. User1 logs in and gets error.
(User2 mentioned User1 so it would make a notification which needs to access the sender(User2)'s identity contract to get display name and picture. But at this point, User1 could not have completed to sync the identity contract even completed to sync group contract)

So I disabled to do something when the identity contract is not synced like the following.
```
const identityState = rootGetters.globalProfile2(groupID, username)
  if (identityState) {
    makeNotification({
      title: `# ${chatRoomName}`,
      body: text,
      icon: identityState.picture,
      path
    })
  } else {
    // this happens when identity contract of username is not synced yet
    // this means when new user joins the group and mentions immediately when I am absent
  }
```
model/contracts/chatroom.js L66 ~ L77

### Solution

To be honest, not sure what should we do for this. @taoeffect can decide this.

My options for the solution are
- Ignore this case
- Sync group contract and then identity contract. After that, chatroom contract

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of Changes
- Closes #1327 
- Closes #1416 
- Closes #1343 
- Closes #1420 
- Fix some UI issues comes from the new design of textarea

### CODE REVIEW

File: frontend/views/containers/chatroom/MessageBase.vue [hunk 1]
```diff
@@ -273,6 +297,10 @@ export default ({
     color: var(--text_2);
     border-color: var(--text_1); // var(--text_2);
   }
+
+  & .c-mention {
```
Comment (SebinSong) [inline frontend/views/containers/chatroom/MessageBase.vue]: it seems`&` here is a typo or safe to be removed. :)

**Comment by SebinSong** [comment]
Looks good to me! :)

File: frontend/views/containers/chatroom/MessageBase.vue (hunk 1 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/MessageBase.vue]: Correct. That's not necessary.

File: contracts/0.0.4/chatroom-slim.js [hunk 2]
```diff
@@ -420,12 +420,16 @@ ${this.getErrorInfo()}`;
...
+    const identityState = rootGetters.globalProfile2(groupID, username);
+    if (identityState) {
+      makeNotification({
+        title: `# ${chatRoomName}`,
+        body: text,
+        icon: identityState.picture,
+        path
+      });
+    } else {
+    }
```
Comment (taoeffect) [inline contracts/0.0.4/chatroom-slim.js]: PRs must never modify existing pinned contracts. They can only ever pin new ones.

None of the files under `0.0.4` can change, so please remove all of these changes.

File: frontend/views/containers/chatroom/MessageBase.vue [hunk 3]
```diff
@@ -112,20 +118,10 @@ export default ({
...
-      return this.text
-        .split(new RegExp(`(${possibleMentions.join('|')})`))
-        .map(t => possibleMentions.includes(t)
-          ? { type: TextObjectType.Mention, text: t }
-          : { type: TextObjectType.Text, text: t }
-        )
+      return this.generateTextObjectsFromText(this.text)
+    },
+    replyMessageObjects () {
+      return this.generateTextObjectsFromText(this.replyingMessage)
```
Comment (taoeffect) [inline frontend/views/containers/chatroom/MessageBase.vue:124]: Good job DRY'ing this 👍

File: strings/french.json [hunk 4]
```diff
@@ -84,7 +104,14 @@
   "Open Prompt": "Open Prompt",
   "Leave {channelName}": "Leave {channelName}",
   "Next distribution date is on {date}. Make sure to update your {r1}income details{r2} by then.": "Next distribution date is on {date}. Make sure to update your {r1}income details{r2} by then.",
-  "Date": "Date",
+  "ALL": "ALL",
```
Comment (taoeffect) [inline strings/french.json:108]: If you're going to update the strings, please also use [the latest version](https://github.com/okTurtles/strings/releases/) of Simon's strings utility. It has be improved significantly, and one of the changes is that all of these will be sorted alphabetically.

File: test/cypress/integration/group-chat-message.spec.js [hunk 5]
```diff
@@ -1,9 +1,22 @@
 import { CHATROOM_GENERAL_NAME } from '../../../frontend/model/contracts/shared/constants.js'
 
+/**
+ * Should import from this function from '../../../frontend/model/contracts/shared/functions.js'
+ * But Cypress doesn't render files using Flowtype annotations
+ * So copied that function and use it here
+ */
```
Comment (taoeffect) [inline test/cypress/integration/group-chat-message.spec.js:8]: Good job with this comment.

Could you please also add a TODO? E.g. something like:

```js
// TODO: figure out how to import functions with type annotations in Cypress
```

**Review by taoeffect — CHANGES_REQUESTED** [review]
Nice work @Silver-IT!

File: test/cypress/integration/group-chat-message.spec.js (hunk 5 above)
Comment (Silver-IT) [reply test/cypress/integration/group-chat-message.spec.js:8]: Sure. Why not?

File: strings/french.json (hunk 4 above)
Comment (Silver-IT) [reply strings/french.json:108]: Oh. I missed it... Okay.

**Review by taoeffect — APPROVED** [review]
Approved!! Fantastic work @Silver-IT! 😄 🎉

File: frontend/model/contracts/chatroom.js [hunk 6]
```diff
@@ -66,7 +66,7 @@ function addMention ({ contractID, messageId, datetime, text, username, chatRoom
   makeNotification({
     title: `# ${chatRoomName}`,
     body: text,
-    icon: rootGetters.globalProfile2(groupID, username).picture,
+    icon: rootGetters.globalProfile2(groupID, username)?.picture,
```
Comment (taoeffect) [inline frontend/model/contracts/chatroom.js:69]: @Silver-IT I forgot to add - we need a comment above these lines explaining why this `?.` is here, to prevent someone from removing it in the future.

Something like:

```js
// this ?. is important - as in some scenarios the profile could be undefined here, see issue #1420
```

Maybe this could be added in a future PR you send?

Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js:69]: Yeah. I will add this comment in the next PR...
