### PR TITLE
#2283 - Chat should not replace symbols in <code>

### LINKED ISSUE #2283: Chat should not replace symbols in <code> (aka <pre>) tags
### Problem

Screenshot 2024-08-05 at 10 36 24 AM

We can't paste code that has a `>` symbol in it into code blocks, so code like this doesn't work:

```js
() => foo
```

### Solution

Not sure.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #2283 

[Proof of the fix]

### CODE REVIEW

File: frontend/views/utils/markdown-utils.js [hunk 1]
```diff
@@ -33,11 +33,21 @@ export function renderMarkdown (str: string): any {
...
-    .replace(/(\d+\.|-)(\s.+)\n<br>/g, '$1$2\n\n') // this is a custom-logic added so that the end of ordered/un-ordered lists are correctly detected by markedjs.
+      entryText = entryText.replace(/\n(?=\n)/g, '\n<br>')
+        .replace(/<br>\n(\s*)(\d+\.|-)/g, '\n\n$1$2') // custom-handling the case where <br> is directly followed by the start of ordered/unordered lists
+        .replace(/(\d+\.|-)(\s.+)\n<br>/g, '$1$2\n\n') // this is a custom-logic added so that the end of ordered/un-ordered lists are correctly detected by markedjs.
+
+      entry.text = entryText
+    }
+  })
+
+  str = combineMarkdownSegmentListIntoString(strSplitByCodeMarkdown)
```
Comment (SebinSong) [inline frontend/views/utils/markdown-utils.js:50]: The cause of the issue was that,
These additional fixes & adjustments related to white-spaces, line-breaks and `<` and `>` did not need to be applied to the contents of `<code>...</code>`.
So a logic added here where it selectively apply these adjustments to the text contents outside of `<code>...</code>`.

**Review by taoeffect — APPROVED** [review]
Fantastic!
