### PR TITLE
Close #2553

### LINKED ISSUE #2553: Followup to infinite loop in eventsAfter (#2544)
### Problem

Followup to #2544 (we didn't test it).

So I tested this by using our GIG group DB and a DM with myself.

- I made a copy of the DB, sent myself a few DMs and switched to `#general`, then shut down the server, replaced the newer DB with the older copy, and re-ran `GI_PERSIST=sqlite grunt dev`
- Then I visited my DM with myself again to load it. I was greeted with the alert* and clicked OK.
- The chat fixed itself (I think; I might've had to first switch to `#general` and back, please test this), however the red banner remained visible when it should be removed since the problem is fixed
- Furthermore, another problem appeared, which was the backend being hammered with these requests:

Image

*When I tried this a second time, I oddly enough wasn't greeted with the alert, but did see the constant `streamEntriesAfter` on the backend... odd.

### Solution

Test this scenario thoroughly locally and fix all remaining bugs, specifically:

- The red critical banner should be dismissed if the resync was a success
- The infinite loop should be fixed for good

EDIT: [it seems the infinite loop was fixed](https://github.com/okTurtles/group-income/issues/2553#issuecomment-2619635109); issue is now about:

- Log BOTH the `GI_VERSION` and the `GI_GIT_VERSION` = `git describe --dirty` in the service worker when it starts up, so that we can be 100% sure that we're running the latest version. 
- Immediately dismiss the danger banner after the user clicks OK to resync the contract.
- Log the URL for `eventsAfter` when an exception is thrown (in production, the parameters are not logged)

### PR DESCRIPTION
**Pull request by corrideat**
EDIT (by @taoeffect): Closes #2553

### CODE REVIEW

File: shared/domains/chelonia/utils.js [hunk 1]
```diff
@@ -747,6 +749,7 @@ export function eventsAfter (contractID: string, sinceHeight: number, limit?: nu
           }
         }
       } catch (e) {
+        console.error('[eventsAfter] Error', { lastUrl }, e)
```
Comment (taoeffect) [inline shared/domains/chelonia/utils.js:752]: Why log `{ lastURL }` instead of `lastURL`?

Comment (corrideat) [reply shared/domains/chelonia/utils.js:752]: `lastURL` isn't defined

**Review by taoeffect — APPROVED** [review]
🎉🎉🎉
