### PR TITLE
#1823 Get the push-notification working again

### LINKED ISSUE #1823: PWA push subscription flow is broken
### Problem

After `e2e-protocol` branch has been merged to the `master`, the push-subscription logic in the app is broken, generating the warning messages above.

### Solution
Figure out the reason why and fix it.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #1823

### CODE REVIEW

File: frontend/model/contracts/shared/nativeNotification.js [hunk 1]
```diff
@@ -18,11 +18,8 @@ export async function requestNotificationPermission (force: boolean = false): Pr
     }
   }
 
-  // TODO FIXME: TEMPORARILY DISABLED AS IT CAUSES AN ERROR DURING THE TESTS
-  if (isNaN(1) && Notification.permission === 'granted') {
+  if (Notification.permission === 'granted') {
     await sbp('service-worker/setup-push-subscription').catch((e) => {
-      // TODO: Temporary until this is better addressed. When running tests,
-      // it results in an AbortError.
```
Comment (SebinSong) [inline frontend/model/contracts/shared/nativeNotification.js:25]: Actually, just removing that `isNaN(1)` made it start working again, and I didn't encounter any `AbortError` kind of error message while seeing it was running okay. My guess is that probably the similar issue was sorted out a while ago but then that fix didn't get merged to `e2e-protocol` branch and went to `master` instead.

**Review by taoeffect — APPROVED** [review]
Great work @SebinSong!
