### PR TITLE
Check whether suitable keys exist before sending

### LINKED ISSUE #3066: Error creating DM with 2 other people
### Problem

When attempting to create a DM with @SebinSong and @corrideat on `staging`, I got:

Image

Dismissing this dialog the chatroom still appears to have been created and I was able to post a message to it.

Then, when I tried switching to `#general` from there, I suddenly got:

Image

And now the `#general` chatroom won't load at all, even on refresh. Each time I visit it I get this `Failed to initialize chatroom` dialog.

Note: I did the same thing on groupincome.app, and I got the same `Failed to create chatroom` dialog in the 1st screenshot above, but visiting `#general` still works there.

- 📎  [gi_logs(failed to create 2-party DM).json.txt](https://github.com/user-attachments/files/26285084/gi_logs.failed.to.create.2-party.DM.json.txt)

### Solution

1. Find out why the `Failed to create chatroom` dialog appears and fix it. Clearly the chatroom was created.
2. Fix the `#general` chatroom being now broken on `staging` (at least for my user). (EDIT: this is now being handled in a separate issue: #3069)

### PR DESCRIPTION
**Pull request by corrideat**
Closes #3066

TODO:

- [x] The underlying issue is that some keys aren't available, so we need to address that.

Then, in terms of mitigations:

- [X] At the very least, we should check that we have all necessary keys before creating a DM.
- [x] Then, if an issue still happens, we could delete the DM.

- [x] An even more comprehensive fix would be having confirmation that everyone has been able to join.

---

<a href="https://app.devin.ai/review/okturtles/group-income/pull/3074" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

**Comment by corrideat** [comment]
/crush_fast

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23673800956)._

**Comment by corrideat** [comment]
/crush_fast

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23698558939)._

**Comment by corrideat** [comment]
/crush_fast

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23698975558)._

**Comment by corrideat** [comment]
/crush_fast {{zai-coding-plan, glm-5}}

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23699451719)._

**Comment by taoeffect** [comment]
/crush_fast {{openrouter, google/gemini-3.1-pro-preview, google/gemini-3-flash-preview}}

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23699681619)._

File: frontend/model/state.js [hunk 1]
```diff
@@ -309,6 +309,65 @@ sbp('sbp/selectors/register', {
...
+      // Did we find a PEK?
+      if (!pek) return
+
+      // $FlowFixMe[incompatible-use]
+      if (dmk.meta?.private?.content?.[0] === pek.id) return
+
+      // $FlowFixMe[incompatible-use]
+      const hasItBeenSharedBefore = state[ourIdentityContractId]._vm.sharedKeyIds?.some((k) => k.id === dmk.id)
+
+      if (hasItBeenSharedBefore) return
```
[the remark this answers is not in the document]
Comment (corrideat) [reply frontend/model/state.js:364]: This doesn't make sense, since the `.id` access appears to be done on the member object, not on `authorizedKeys`.

File: frontend/controller/app/chatroom.js [hunk 2]
```diff
@@ -28,11 +28,11 @@ sbp('okTurtles.events/on', JOINED_CHATROOM, ({ identityContractID, groupContract
...
       const rootGetters = sbp('state/vuex/getters')
       if (!rootGetters.isJoinedChatRoom(chatRoomID, identityContractID)) {
-        if (++attemptCount > 5) {
-          console.warn('[JOINED_CHATROOM] Given up on setCurrentChatRoomId after 5 attempts', { identityContractID, groupContractID, chatRoomID })
+        if (++attemptCount > 10) {
+          console.warn('[JOINED_CHATROOM] Given up on setCurrentChatRoomId after 10 attempts', { identityContractID, groupContractID, chatRoomID })
           return
         }
-        setTimeout(setCurrentChatRoomId, 5 * Math.pow(1.75, attemptCount))
+        setTimeout(setCurrentChatRoomId, 5 * Math.pow(1.65, attemptCount))
```
Comment (taoeffect) [inline frontend/controller/app/chatroom.js]: Why are these values being changed? If the tests are failing repeatedly, fiddling with timeouts doesn't seem like the correct response to me

Comment (corrideat) [reply frontend/controller/app/chatroom.js]: Devin suggested a minor refactoring (so that the chatroom gets deleted on any error) that seems to cause issues with when the `JOINED_CHATROOM` event is created. I'm testing out how to fix this issue.

This particular change was a test to see how to fix this (there's an explanation above this explaining why this uses timeouts).

I'm now refactoring this function to avoid needing timeouts. However, completely eliminating seemingly arbitrary timeouts is proving difficult due to some seemingly weird Vue behaviour. For example, I check that the chatroom is in `ourGroupDirectMessages`, but then the same getter a bit later the same check gives a different result.

**Comment by corrideat** [comment]
/crush_fast {{zai-coding-plan, glm-5}}

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23759141539)._

**Comment by taoeffect** [comment]
/review_fast

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23760088783)._

**Comment by taoeffect** [comment]
/crush_fast

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23761476859)._

File: frontend/controller/actions/identity.js [hunk 3]
```diff
@@ -718,84 +758,142 @@ export default (sbp('sbp/selectors/register', {
...
+      return [promise, outerResolve, outerReject]
+    })()
+    const receivedCreateDirectMessage: [Promise<any>, Function, Function] = (() => {
+      let outerResolve, outerReject
+      const promise = new Promise((resolve, reject) => {
+        outerResolve = resolve
+        outerReject = reject
+      })
+      return [promise, outerResolve, outerReject]
+    })()
```
Comment (taoeffect) [inline frontend/controller/actions/identity.js]: This looks like a good pattern that can be reused in various places. So let's DRY this and improve it:

1. Create a utility function and save it under `frontend/utils` somewhere
2. Instead of returning an array, return an object

For (2), this way you can do stuff like this:

```js
receivedChatroomJoin.reject()

// and

onprocessed: receivedChatroomJoin.resolve
```

And also `receivedChatroomJoin.promise`

Apparently there's also: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers

File: frontend/controller/actions/identity.js [hunk 4]
```diff
@@ -718,84 +758,142 @@ export default (sbp('sbp/selectors/register', {
...
+        receivedCreateDirectMessage[2](e)
+        throw e
+      })
+
+      // Prevent the promises from hanging forever
+      setTimeout(() => {
+        const e = new Error('Timeout exceeded')
+        receivedChatroomJoin[2](e)
+        receivedCreateDirectMessage[2](e)
+      }, 5000)
```
Comment (taoeffect) [inline frontend/controller/actions/identity.js]: Shouldn't this timeout be cancelled if the promise succeeds first? Right now it'll always call reject (are you sure that's "clean"?)

File: frontend/controller/actions/identity.js [hunk 5]
```diff
@@ -718,84 +758,142 @@ export default (sbp('sbp/selectors/register', {
...
+
+        // Share the keys to the newly created chatroom with partners
+        // TODO: We need to handle multiple groups and the possibility of not
+        // having any groups in common
+        await sbp('gi.actions/out/shareVolatileKeys', {
+          contractID: partnerIDs[index],
+          contractName: 'gi.contracts/identity',
+          subjectContractID: chatroomID,
+          keyIds: '*'
+        })
```
Comment (taoeffect) [inline frontend/controller/actions/identity.js]: What does it mean that we're not currently handling multiple groups?

(And why can't we do that now?)

File: frontend/controller/actions/identity.js [hunk 6]
```diff
@@ -718,84 +758,142 @@ export default (sbp('sbp/selectors/register', {
...
+      })
+    } catch (e) {
+      sbp('chelonia/out/deleteContract', chatroomID, {
+        [chatroomID]: { billableContractID: identityContractID }
+      }).catch((e2) => {
+        console.error('[gi.actions/identity/createDirectMessage] Error attempting to delete chatroom after error', chatroomID, e, e2)
       })
+
+      receivedChatroomJoin[0].catch(() => { /* no unhandled promise rejection */ })
+      receivedCreateDirectMessage[0].catch(() => { /* no unhandled promise rejection */ })
```
Comment (taoeffect) [inline frontend/controller/actions/identity.js]: Are you sure that attaching these `.catch` handlers here that do nothing will still cause the above Promise.all to trigger the `.catch` when the timeout is hit?

Comment (corrideat) [reply frontend/controller/actions/identity.js]: Yes, that's only to avoid unhandled promise rejection errors (if the promise rejects).

`.catch` / `.then` / `.finally` doesn't change what the original promise resolves to (the value doesn't change).

```
const a = Promise.resolve('a')

console.log(await a) // 'a'
console.log(await a) // 'a'
console.log(await a) // 'a'
```

File: frontend/controller/actions/identity.js (hunk 5 above)
Comment (corrideat) [reply frontend/controller/actions/identity.js]: This is an old comment. `shareVolatileKeys` will pick a key in common to send `OP_KEY_SHARE`, which is tied to joining a group. If one has multiple groups in common, one of them will be picked. If one has no groups in common, the operation will generally fail (but we're only sending this for people who share at least one group)

File: frontend/controller/actions/identity.js (hunk 4 above)
Comment (corrideat) [reply frontend/controller/actions/identity.js]: reject() after resolve() should not do anything, but you're right that it's cleaner to cancel the timeout.

File: frontend/controller/actions/identity.js (hunk 5 above)
Comment (taoeffect) [reply frontend/controller/actions/identity.js]: Based on convo it sounds like we *do* currently handle multiple groups, but not when no groups are shared in common, and that an error will occur in that situation. So could you update the comment to reflect that to say that if a DM is initiated with someone with no groups in common with us then in that case this code will fail?

File: frontend/views/containers/chatroom/DeleteChannelModal.vue [hunk 7]
```diff
@@ -63,6 +63,9 @@ export default ({
   },
   computed: {
     ...mapGetters(['currentChatRoomId', 'chatRoomAttributes', 'groupGeneralChatRoomId']),
+    // TODO: BEGIN Temporary code (see issue #3066) for removing DMs
+    ...mapGetters(['ourIdentityContractId', 'isGroupDirectMessage']),
+    // TODO: END   Temporary code (see issue #3066) for removing DMs
     ...mapState(['currentGroupId'])
```
[the remark this answers is not in the document]
Comment (corrideat) [reply frontend/views/containers/chatroom/DeleteChannelModal.vue:69]: Dismissed because this is a temporary change.

**Comment by taoeffect** [comment]
/crush_fast

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23763847680)._

**Comment by taoeffect** [comment]
/crush_fast {{openrouter, google/gemini-3.1-pro-preview, google/gemini-3-flash-preview}}

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23763920501)._

File: frontend/controller/actions/identity.js [hunk 8]
```diff
@@ -718,84 +759,138 @@ export default (sbp('sbp/selectors/register', {
...
-        contractID: partnerIDs[index],
-        contractName: 'gi.contracts/identity',
-        subjectContractID: message.contractID(),
-        keyIds: '*'
+      // Prevent the promises from hanging forever
+      const timeoutId = setTimeout(() => {
+        const e = new Error('Timeout exceeded')
+        receivedChatroomJoin.reject(e)
+        receivedCreateDirectMessage.reject(e)
+      }, 5000)
```
Comment (taoeffect) [inline frontend/controller/actions/identity.js]: Could you update the code, so that if it takes a while for the DM to be created, and the user — frustrated by the delay — attempts to create another identical DM, that the UI gives a prompt saying that an existing chatroom creation is pending? You could use `okTurtles.data` to manage these. This would be reset on page refresh

**Comment by taoeffect** [comment]
/crush_fast {{openrouter, google/gemini-3.1-pro-preview, google/gemini-3-flash-preview}}



---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23765826994)._

**Comment by taoeffect** [comment]
/crush_fast

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23766381594)._

**Comment by taoeffect** [comment]
/crush_fast

---

_AI review [started](https://github.com/okTurtles/group-income/actions/runs/23766435349)._

**Review by taoeffect — APPROVED** [review]
Great work @corrideat!!! 👏 👏 👏 👏 👏
