### PR TITLE
Error handling

### LINKED ISSUE #2624: Heisenbug: Local test failure in group-chat.spec: failed to join #general
### Problem

EDIT: this happens on GitHub too: https://cloud.cypress.io/projects/q6whky/runs/3974/test-results

While running `grunt test` locally, I got failure on this 3 times in a row, with the 4th test passing:

https://github.com/user-attachments/assets/a1380d28-3326-466b-8523-97b3152814d8

<details>

```
  Console Logs:
  ========================
  [["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VJjB6ezCDaEg1eFqUWF32nqefSsEeWauJ7Z9Mczzg1Dex",false]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VNj8fcWcMtULBMMUGMHZmQGfczhB2bzJVCN3yiquGCHuB",true]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VMzUDzTF4bdr2GPuiLNCWtM4BgTcF8qVkuPvZxXKwTmJC",true]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VGzgHjPm9iamCTsGnTGmsHdBDSELJA8GDd5PFopZN7bwS",true]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VJ2ZJror7tNVPi17wNCdnU7KjPHsYzr5TsC6JpkAYAFRv",true]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VJjB6ezCDaEg1eFqUWF32nqefSsEeWauJ7Z9Mczzg1Dex",true]]
  ["debug","[sbp] okTurtles.events/emit",["joined-group",{"identityContractID":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","groupContractID":"z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"}]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["debug","[sbp] okTurtles.events/emit",["namespace-registration",{"name":"user1-6190000000596046447754","value":"z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km"}]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VQAUyRn1HXrGxAw9hpvTyZgKZAjy6y4QmXwsb1KHjGK71",false]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VQAUyRn1HXrGxAw9hpvTyZgKZAjy6y4QmXwsb1KHjGK71",true]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f",true]]
  ["debug","[sbp] okTurtles.events/emit",["kv-event",{"contractID":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","key":"notifications","data":{"z2DrjgbLc2irk64yv1qUEweBJTR3d4LNKNfZWJXbumagEHwUUei":{"timestamp":1739480536169,"read":false},"z2Drjgb6QXYe2145WCm65xogn49kUMz8dmqDDL33PggPSdR68pH":{"timestamp":1739480556675,"read":false}}}]]
  ["debug","[sbp] state/vuex/commit",["setNotificationStatus",{"z2DrjgbLc2irk64yv1qUEweBJTR3d4LNKNfZWJXbumagEHwUUei":{"timestamp":1739480536169,"read":false},"z2Drjgb6QXYe2145WCm65xogn49kUMz8dmqDDL33PggPSdR68pH":{"timestamp":1739480556675,"read":false}}]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VGzgHjPm9iamCTsGnTGmsHdBDSELJA8GDd5PFopZN7bwS",false]]
  ["debug","[sbp] okTurtles.events/emit",["contracts-modified",["z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f","z9brRu3VMKCTM65XE9dqGEpcSBGFTWH1GFfGRZZXRW9FNkXLqQko","z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km","z9brRu3VQAUyRn1HXrGxAw9hpvTyZgKZAjy6y4QmXwsb1KHjGK71","z9brRu3VNj8fcWcMtULBMMUGMHZmQGfczhB2bzJVCN3yiquGCHuB","z9brRu3VMzUDzTF4bdr2GPuiLNCWtM4BgTcF8qVkuPvZxXKwTmJC","z9brRu3VJ2ZJror7tNVPi17wNCdnU7KjPHsYzr5TsC6JpkAYAFRv","z9brRu3VJjB6ezCDaEg1eFqUWF32nqefSsEeWauJ7Z9Mczzg1Dex"],{"added":[],"removed":["z9brRu3VGzgHjPm9iamCTsGnTGmsHdBDSELJA8GDd5PFopZN7bwS"]}]]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VJ2ZJror7tNVPi17wNCdnU7KjPHsYzr5TsC6JpkAYAFRv",false]]
  ["debug","[sbp] okTurtles.events/emit",["contracts-modified",["z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f","z9brRu3VMKCTM65XE9dqGEpcSBGFTWH1GFfGRZZXRW9FNkXLqQko","z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km","z9brRu3VQAUyRn1HXrGxAw9hpvTyZgKZAjy6y4QmXwsb1KHjGK71","z9brRu3VNj8fcWcMtULBMMUGMHZmQGfczhB2bzJVCN3yiquGCHuB","z9brRu3VMzUDzTF4bdr2GPuiLNCWtM4BgTcF8qVkuPvZxXKwTmJC","z9brRu3VJjB6ezCDaEg1eFqUWF32nqefSsEeWauJ7Z9Mczzg1Dex"],{"added":[],"removed":["z9brRu3VJ2ZJror7tNVPi17wNCdnU7KjPHsYzr5TsC6JpkAYAFRv"]}]]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VJjB6ezCDaEg1eFqUWF32nqefSsEeWauJ7Z9Mczzg1Dex",false]]
  ["debug","[sbp] okTurtles.events/emit",["contracts-modified",["z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f","z9brRu3VMKCTM65XE9dqGEpcSBGFTWH1GFfGRZZXRW9FNkXLqQko","z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km","z9brRu3VQAUyRn1HXrGxAw9hpvTyZgKZAjy6y4QmXwsb1KHjGK71","z9brRu3VNj8fcWcMtULBMMUGMHZmQGfczhB2bzJVCN3yiquGCHuB","z9brRu3VMzUDzTF4bdr2GPuiLNCWtM4BgTcF8qVkuPvZxXKwTmJC"],{"added":[],"removed":["z9brRu3VJjB6ezCDaEg1eFqUWF32nqefSsEeWauJ7Z9Mczzg1Dex"]}]]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["debug","[sbp] okTurtles.events/emit",["namespace-registration",{"name":"user1-6190000000596046447754","value":"z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km"}]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VQAUyRn1HXrGxAw9hpvTyZgKZAjy6y4QmXwsb1KHjGK71",false]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f",false]]
  ["debug","[sbp] okTurtles.events/emit",["notification-emitted",{"title":"Internal error","body":"GIChatroomNotMemberError during process for 'a' to 'gi.contracts/chatroom': 'Can not leave the chatroom z9brRu3VNj8fcWcMtULBMMUGMHZmQGfczhB2bzJVCN3yiquGCHuB which z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf is not part of'","plaintextBody":"GIChatroomNotMemberError during process for 'a' to 'gi.contracts/chatroom': 'Can not leave the chatroom z9brRu3VNj8fcWcMtULBMMUGMHZmQGfczhB2bzJVCN3yiquGCHuB which z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf is not part of'","icon":"exclamation-triangle","level":"danger","linkTo":"/app/dashboard?modal=UserSettingsModal&tab=application-logs&errorMsg=Can%20not%20leave%20the%20chatroom%20z9brRu3VNj8fcWcMtULBMMUGMHZmQGfczhB2bzJVCN3yiquGCHuB%20which%20z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf%20is%20not%20part%20of","scope":"app","hash":"z2Drjgb7ezGPtC5f2YViTRoQa4YcbMoZobuZUaVuesJia8wWGCC","avatarUserID":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","timestamp":1739480557597,"type":"CHELONIA_ERROR"}]]
  ["debug","[sbp] state/vuex/commit",["addNotification",{"title":"Internal error","body":"GIChatroomNotMemberError during process for 'a' to 'gi.contracts/chatroom': 'Can not leave the chatroom z9brRu3VNj8fcWcMtULBMMUGMHZmQGfczhB2bzJVCN3yiquGCHuB which z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf is not part of'","plaintextBody":"GIChatroomNotMemberError during process for 'a' to 'gi.contracts/chatroom': 'Can not leave the chatroom z9brRu3VNj8fcWcMtULBMMUGMHZmQGfczhB2bzJVCN3yiquGCHuB which z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf is not part of'","icon":"exclamation-triangle","level":"danger","linkTo":"/app/dashboard?modal=UserSettingsModal&tab=application-logs&errorMsg=Can%20not%20leave%20the%20chatroom%20z9brRu3VNj8fcWcMtULBMMUGMHZmQGfczhB2bzJVCN3yiquGCHuB%20which%20z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf%20is%20not%20part%20of","scope":"app","hash":"z2Drjgb7ezGPtC5f2YViTRoQa4YcbMoZobuZUaVuesJia8wWGCC","avatarUserID":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","timestamp":1739480557597,"type":"CHELONIA_ERROR"}]]
  ["debug","[sbp] okTurtles.events/emit",["notification-emitted",{"title":"Internal error","body":"TypeError during handleEvent for 'a' to 'gi.contracts/chatroom': 'Cannot read properties of undefined (reading 'authorizedKeys')'","plaintextBody":"TypeError during handleEvent for 'a' to 'gi.contracts/chatroom': 'Cannot read properties of undefined (reading 'authorizedKeys')'","icon":"exclamation-triangle","level":"danger","linkTo":"/app/dashboard?modal=UserSettingsModal&tab=application-logs&errorMsg=Cannot%20read%20properties%20of%20undefined%20(reading%20'authorizedKeys')","scope":"app","hash":"z2DrjgbGvhZ9v1govw84jMvzpZH62Ey1VHwzw9j8LwW6KWA5fGC","avatarUserID":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","timestamp":1739480557602,"type":"CHELONIA_ERROR"}]]
  ["debug","[sbp] state/vuex/commit",["addNotification",{"title":"Internal error","body":"TypeError during handleEvent for 'a' to 'gi.contracts/chatroom': 'Cannot read properties of undefined (reading 'authorizedKeys')'","plaintextBody":"TypeError during handleEvent for 'a' to 'gi.contracts/chatroom': 'Cannot read properties of undefined (reading 'authorizedKeys')'","icon":"exclamation-triangle","level":"danger","linkTo":"/app/dashboard?modal=UserSettingsModal&tab=application-logs&errorMsg=Cannot%20read%20properties%20of%20undefined%20(reading%20'authorizedKeys')","scope":"app","hash":"z2DrjgbGvhZ9v1govw84jMvzpZH62Ey1VHwzw9j8LwW6KWA5fGC","avatarUserID":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","timestamp":1739480557602,"type":"CHELONIA_ERROR"}]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VNj8fcWcMtULBMMUGMHZmQGfczhB2bzJVCN3yiquGCHuB",false]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VMzUDzTF4bdr2GPuiLNCWtM4BgTcF8qVkuPvZxXKwTmJC",false]]
  ["debug","[sbp] okTurtles.events/emit",["contracts-modified",["z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f","z9brRu3VMKCTM65XE9dqGEpcSBGFTWH1GFfGRZZXRW9FNkXLqQko","z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km","z9brRu3VQAUyRn1HXrGxAw9hpvTyZgKZAjy6y4QmXwsb1KHjGK71","z9brRu3VNj8fcWcMtULBMMUGMHZmQGfczhB2bzJVCN3yiquGCHuB"],{"added":[],"removed":["z9brRu3VMzUDzTF4bdr2GPuiLNCWtM4BgTcF8qVkuPvZxXKwTmJC"]}]]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["debug","[sbp] okTurtles.events/emit",["kv-event",{"contractID":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","key":"notifications","data":{"z2DrjgbLc2irk64yv1qUEweBJTR3d4LNKNfZWJXbumagEHwUUei":{"timestamp":1739480536169,"read":false},"z2Drjgb6QXYe2145WCm65xogn49kUMz8dmqDDL33PggPSdR68pH":{"timestamp":1739480556675,"read":false},"z2Drjgb9wT1JzjyQpTn4DxcHjZCuvcLVwGgtt81nQjEdrST6DUg":{"timestamp":1739480556684,"read":false}}}]]
  ["debug","[sbp] state/vuex/commit",["setNotificationStatus",{"z2DrjgbLc2irk64yv1qUEweBJTR3d4LNKNfZWJXbumagEHwUUei":{"timestamp":1739480536169,"read":false},"z2Drjgb6QXYe2145WCm65xogn49kUMz8dmqDDL33PggPSdR68pH":{"timestamp":1739480556675,"read":false},"z2Drjgb9wT1JzjyQpTn4DxcHjZCuvcLVwGgtt81nQjEdrST6DUg":{"timestamp":1739480556684,"read":false}}]]
  ["debug","[sbp] okTurtles.events/emit",["namespace-registration",{"name":"user1-6190000000596046447754","value":"z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km"}]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["event-handled",null]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km",false]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km",true]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["debug","[sbp] okTurtles.events/emit",["contract-is-syncing","z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km",false]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["debug","[sbp] okTurtles.events/emit",["kv-event",{"contractID":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","key":"notifications","data":{"z2DrjgbLc2irk64yv1qUEweBJTR3d4LNKNfZWJXbumagEHwUUei":{"timestamp":1739480536169,"read":false},"z2Drjgb6QXYe2145WCm65xogn49kUMz8dmqDDL33PggPSdR68pH":{"timestamp":1739480556675,"read":false},"z2Drjgb9wT1JzjyQpTn4DxcHjZCuvcLVwGgtt81nQjEdrST6DUg":{"timestamp":1739480556684,"read":false},"z2Drjgb7ezGPtC5f2YViTRoQa4YcbMoZobuZUaVuesJia8wWGCC":{"timestamp":1739480557597,"read":false}}}]]
  ["debug","[sbp] state/vuex/commit",["setNotificationStatus",{"z2DrjgbLc2irk64yv1qUEweBJTR3d4LNKNfZWJXbumagEHwUUei":{"timestamp":1739480536169,"read":false},"z2Drjgb6QXYe2145WCm65xogn49kUMz8dmqDDL33PggPSdR68pH":{"timestamp":1739480556675,"read":false},"z2Drjgb9wT1JzjyQpTn4DxcHjZCuvcLVwGgtt81nQjEdrST6DUg":{"timestamp":1739480556684,"read":false},"z2Drjgb7ezGPtC5f2YViTRoQa4YcbMoZobuZUaVuesJia8wWGCC":{"timestamp":1739480557597,"read":false}}]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["debug","[sbp] okTurtles.events/emit",["kv-event",{"contractID":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","key":"notifications","data":{"z2DrjgbLc2irk64yv1qUEweBJTR3d4LNKNfZWJXbumagEHwUUei":{"timestamp":1739480536169,"read":false},"z2Drjgb6QXYe2145WCm65xogn49kUMz8dmqDDL33PggPSdR68pH":{"timestamp":1739480556675,"read":false},"z2Drjgb9wT1JzjyQpTn4DxcHjZCuvcLVwGgtt81nQjEdrST6DUg":{"timestamp":1739480556684,"read":false},"z2Drjgb7ezGPtC5f2YViTRoQa4YcbMoZobuZUaVuesJia8wWGCC":{"timestamp":1739480557597,"read":false},"z2DrjgbGvhZ9v1govw84jMvzpZH62Ey1VHwzw9j8LwW6KWA5fGC":{"timestamp":1739480557602,"read":false}}}]]
  ["debug","[sbp] state/vuex/commit",["setNotificationStatus",{"z2DrjgbLc2irk64yv1qUEweBJTR3d4LNKNfZWJXbumagEHwUUei":{"timestamp":1739480536169,"read":false},"z2Drjgb6QXYe2145WCm65xogn49kUMz8dmqDDL33PggPSdR68pH":{"timestamp":1739480556675,"read":false},"z2Drjgb9wT1JzjyQpTn4DxcHjZCuvcLVwGgtt81nQjEdrST6DUg":{"timestamp":1739480556684,"read":false},"z2Drjgb7ezGPtC5f2YViTRoQa4YcbMoZobuZUaVuesJia8wWGCC":{"timestamp":1739480557597,"read":false},"z2DrjgbGvhZ9v1govw84jMvzpZH62Ey1VHwzw9j8LwW6KWA5fGC":{"timestamp":1739480557602,"read":false}}]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]
  ["debug","[sbp] chelonia/contract/fullState",["z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f"]]
  ["ERROR(CYPRESS)","couldn't stringify debug message in app test due to ChelErrorSignatureError: 'Missing contract state'","original message (with cycle removed):","\"[sbp] okTurtles.events/emit\"","[circular reference]"]


[.. snip ..]

  ["debug","[sbp] chelonia/in/processMessage",["{\"_signedData\":[\"[{\\\"name\\\":\\\"csk\\\",\\\"oldKeyId\\\":\\\"z2DrjgbJQ6N9Vos3ykzZadsydAL7hyZrBiiKtkx5319tfyYea4i\\\",\\\"id\\\":\\\"z2DrjgbGCQKHkUSMEGqWHRbsxu9KiRC6vRGVKySxXjvC88vwxtZ\\\",\\\"data\\\":\\\"[\\\\\\\"edwards25519sha512batch\\\\\\\",\\\\\\\"ekNT6Jq4cFUN5jhRIYwvOo+/Km6hmkJk38g21DDipi4=\\\\\\\",null]\\\"},{\\\"name\\\":\\\"cek\\\",\\\"oldKeyId\\\":\\\"z2Drjgb6ZRGc8SrQSw98L4TS656XrPmg5LGMGRWu2nY3peW9sdC\\\",\\\"id\\\":\\\"z2DrjgbB7ru3zJK3MC4LUb2hfxP8Xa5hX52vWuT3MFvpqfPLqXP\\\",\\\"data\\\":\\\"[\\\\\\\"curve25519xsalsa20poly1305\\\\\\\",\\\\\\\"kSGdJ7qgXMgbCuHwGEeuwRb3gxyvx/zryHrP3jSBXGE=\\\\\\\",null]\\\"}]\",\"z2DrjgbJQ6N9Vos3ykzZadsydAL7hyZrBiiKtkx5319tfyYea4i\",\"7RwQfQHGeKh0OvN+GFz9+FhUZ7yiWbMetaa2GqylRT6MkBDFURitsiepVDyOqm0/zXwVFA9dpHCs9aYMdkLjDw==\"],\"head\":\"{\\\"version\\\":\\\"1.0.0\\\",\\\"previousHEAD\\\":\\\"z9brRu3VUf4EQv44aS5bm1hpaED8yyrdJdQp8SGpq9TGZMz1KhHb\\\",\\\"height\\\":12,\\\"contractID\\\":\\\"z9brRu3VNj8fcWcMtULBMMUGMHZmQGfczhB2bzJVCN3yiquGCHuB\\\",\\\"op\\\":\\\"ku\\\",\\\"manifest\\\":\\\"z9brRu3VG4upaWM76rFFqPd5iHEmnduW2DLdRpQ3dijQxkeD2ZDp\\\"}\"}",{"settings":{"actionsPerPage":40,"maxNameLength":50,"maxDescriptionLength":280},"attributes":{"adminIDs":[],"deletedDate":null,"name":"general","type":"group","description":"","privacyLevel":"group","creatorID":"z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km"},"members":{"z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km":{"joinedDate":"2025-02-13T21:01:42.333Z","joinedHeight":2}},"_vm":{"type":"gi.contracts/chatroom","authorizedKeys":{"z2Drjgb5EvyTukYDkUjVpPDTUMNWxG3rYWe5yvpKXP2zhgbSGcD":{"id":"z2Drjgb5EvyTukYDkUjVpPDTUMNWxG3rYWe5yvpKXP2zhgbSGcD","name":"csk","purpose":["sig"],"ringLevel":0,"permissions":"*","allowedActions":"*","foreignKey":"shelter:z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f?keyName=csk","data":"[\"edwards25519sha512batch\",\"zelaJfeBAZ2rbZc37aK2+4ZKjebpopzmB8zsuelkG9s=\",null]","_notBeforeHeight":0,"_notAfterHeight":8},"z2DrjgbGL4VA5ii1yU7HE5WaXsHSd2tgazY6FDjqLSheudBjMYd":{"id":"z2DrjgbGL4VA5ii1yU7HE5WaXsHSd2tgazY6FDjqLSheudBjMYd","name":"cek","purpose":["enc"],"ringLevel":0,"permissions":["ae"],"allowedActions":"*","foreignKey":"shelter:z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f?keyName=cek","data":"[\"curve25519xsalsa20poly1305\",\"VDucaZMXYBlzMPGhtn3q6I+c/+7YBxYLc743BsxUKUw=\",null]","_notBeforeHeight":0,"_notAfterHeight":8},"z2Drjgb4bn7WWrkD5XFRDxEfVzPkNdc192P3wxntLrQFmgnxhWb":{"id":"z2Drjgb4bn7WWrkD5XFRDxEfVzPkNdc192P3wxntLrQFmgnxhWb","name":"#sak","purpose":["sak"],"ringLevel":0,"permissions":[],"allowedActions":[],"meta":{"private":{"content":["z2DrjgbGL4VA5ii1yU7HE5WaXsHSd2tgazY6FDjqLSheudBjMYd","sFhdnc8kazo/hiWfcPg8qAQOcSc7aDQXsvXjstifGlmBv4nXq4KrF2s5wygiOe25WzxO0g/jLxwX4Y1lroSKnQt/umloJ+w3EfPSiTSpenlSKq2quT1HSDevo4Xj3HpPTfhXIGwCnbpNVCHC7I+PLUAdRUssfkA3oWNBROBEUUEIXarTJ4zFZ4IqQIxVKl5HGBEKv9MJPjN38WZXTMMg3gEfl4rVdLPfY9468ZB5g/ME3kmR9pnJHI5ZsWllaH0ppkw8a51Xlh5l"]}},"data":"[\"edwards25519sha512batch\",\"Cc+1XJHf3NIeCF/1oZDKOAjvmTcohmNALz4Oq3jsCVk=\",null]","_notBeforeHeight":0},"z2Drjgb5mj3HidEjKna68hEuvcvTeTDzdhdwX8m4WXgoeGBjGt1":{"foreignKey":"shelter:z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km?keyName=csk","id":"z2Drjgb5mj3HidEjKna68hEuvcvTeTDzdhdwX8m4WXgoeGBjGt1","data":"[\"edwards25519sha512batch\",\"AtQDdWp06g46A5zwQNnmmVEUxtWtk8f9fMDDoePwjAA=\",null]","permissions":["ae#inner"],"allowedActions":"*","purpose":["sig"],"ringLevel":9007199254740991,"name":"z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km/z2Drjgb5mj3HidEjKna68hEuvcvTeTDzdhdwX8m4WXgoeGBjGt1","_private":"z2DrjgbGL4VA5ii1yU7HE5WaXsHSd2tgazY6FDjqLSheudBjMYd","_notBeforeHeight":2},"z2DrjgbCR3aULgAnTuprdkugD1y4h3n1Qwj4KTMD2QnXnH8AvEJ":{"foreignKey":"shelter:z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA?keyName=csk","id":"z2DrjgbCR3aULgAnTuprdkugD1y4h3n1Qwj4KTMD2QnXnH8AvEJ","data":"[\"edwards25519sha512batch\",\"vb9QVj7uIsTNAZW1RclmC5/zZ4fnsF3PoBgmF4gzobI=\",null]","permissions":["ae#inner"],"allowedActions":"*","purpose":["sig"],"ringLevel":9007199254740991,"name":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA/z2DrjgbCR3aULgAnTuprdkugD1y4h3n1Qwj4KTMD2QnXnH8AvEJ","_private":"z2DrjgbGL4VA5ii1yU7HE5WaXsHSd2tgazY6FDjqLSheudBjMYd","_notBeforeHeight":3,"_notAfterHeight":7},"z2Drjgb88UygBG5VXHJ56uCF6vFCoBZ4abFn4JMUWjLjfAEi6pX":{"foreignKey":"shelter:z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf?keyName=csk","id":"z2Drjgb88UygBG5VXHJ56uCF6vFCoBZ4abFn4JMUWjLjfAEi6pX","data":"[\"edwards25519sha512batch\",\"hldZb+L+j4qurl5Pe31DzU1+lrrUrYIHfE+3zPKvEco=\",null]","permissions":["ae#inner"],"allowedActions":"*","purpose":["sig"],"ringLevel":9007199254740991,"name":"z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf/z2Drjgb88UygBG5VXHJ56uCF6vFCoBZ4abFn4JMUWjLjfAEi6pX","_private":"z2DrjgbGL4VA5ii1yU7HE5WaXsHSd2tgazY6FDjqLSheudBjMYd","_notBeforeHeight":4,"_notAfterHeight":10},"z2DrjgbH3oQ6fKgMiDxz3hE9DA5nGnGRMkifTVoxCPyWmwqN4wR":{"id":"z2DrjgbH3oQ6fKgMiDxz3hE9DA5nGnGRMkifTVoxCPyWmwqN4wR","name":"csk","purpose":["sig"],"ringLevel":0,"permissions":"*","allowedActions":"*","foreignKey":"shelter:z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f?keyName=csk","data":"[\"edwards25519sha512batch\",\"fX1yqbSNVjg7ewCWWWr7b24oAkDmgovZl08SHxpUwV4=\",null]","_notBeforeHeight":8,"_notAfterHeight":9},"z2DrjgbM2z284WSKCqNS1guAe2LKQF3gt4hUwbv1NAeMxXQ2SYr":{"id":"z2DrjgbM2z284WSKCqNS1guAe2LKQF3gt4hUwbv1NAeMxXQ2SYr","name":"cek","purpose":["enc"],"ringLevel":0,"permissions":["ae"],"allowedActions":"*","foreignKey":"shelter:z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f?keyName=cek","data":"[\"curve25519xsalsa20poly1305\",\"yTXivxF7A9K0ji7OMKbQ80ptuBo5FgREoz6HFg+UrRs=\",null]","_notBeforeHeight":8,"_notAfterHeight":9},"z2DrjgbJQ6N9Vos3ykzZadsydAL7hyZrBiiKtkx5319tfyYea4i":{"id":"z2DrjgbJQ6N9Vos3ykzZadsydAL7hyZrBiiKtkx5319tfyYea4i","name":"csk","purpose":["sig"],"ringLevel":0,"permissions":"*","allowedActions":"*","foreignKey":"shelter:z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f?keyName=csk","data":"[\"edwards25519sha512batch\",\"elTGd0ZEjoQby9NSs9xBPNeoNH9d2pvYpKXVQCgcLqc=\",null]","_notBeforeHeight":9},"z2Drjgb6ZRGc8SrQSw98L4TS656XrPmg5LGMGRWu2nY3peW9sdC":{"id":"z2Drjgb6ZRGc8SrQSw98L4TS656XrPmg5LGMGRWu2nY3peW9sdC","name":"cek","purpose":["enc"],"ringLevel":0,"permissions":["ae"],"allowedActions":"*","foreignKey":"shelter:z9brRu3VFLtZsjH2QSqjsnoZ5fxSf8vXuDh2AvEyCCnbd5r4iy5f?keyName=cek","data":"[\"curve25519xsalsa20poly1305\",\"cKngekSOTAAQbsLzgml0D9uZWLDdmEWbDt/Y8TAeejA=\",null]","_notBeforeHeight":9}},"pendingWatch":{"z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km":[["csk","z2Drjgb5mj3HidEjKna68hEuvcvTeTDzdhdwX8m4WXgoeGBjGt1"],["csk","z2Drjgb5mj3HidEjKna68hEuvcvTeTDzdhdwX8m4WXgoeGBjGt1"],["csk","z2Drjgb5mj3HidEjKna68hEuvcvTeTDzdhdwX8m4WXgoeGBjGt1"],["csk","z2Drjgb5mj3HidEjKna68hEuvcvTeTDzdhdwX8m4WXgoeGBjGt1"],["csk","z2Drjgb5mj3HidEjKna68hEuvcvTeTDzdhdwX8m4WXgoeGBjGt1"]],"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA":[],"z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf":[]}},"messages":[{"type":"notification","hash":"z9brRu3VRc3furdXLZQpx3wmoQRX1WTybnxJvVmwBSTQofKChgyL","height":2,"from":"z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km","datetime":"2025-02-13T21:01:42.333Z","notification":{"type":"join-member","params":{"channelName":"general","channelDescription":"","memberID":"z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km"}}},{"type":"notification","hash":"z9brRu3VTesqybbx3MAcSFT68w9VXVMLYdUnAJPaaSHTFjovJWAB","height":3,"from":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","datetime":"2025-02-13T21:01:49.639Z","notification":{"type":"join-member","params":{"channelName":"general","channelDescription":"","memberID":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA"}}},{"type":"notification","hash":"z9brRu3VVstMD14EyJXsujuZUqztbC6tJ3Hu5tGkceRboGRQEmWi","height":4,"from":"z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf","datetime":"2025-02-13T21:01:54.512Z","notification":{"type":"join-member","params":{"channelName":"general","channelDescription":"","memberID":"z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf"}}},{"type":"interactive","hash":"z9brRu3VJygT2f5woz3eoVokAH4EAiw7AYAT1ienyWRTrCHN13KR","height":5,"from":"z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf","datetime":"2025-02-13T21:02:16.206Z","proposal":{"proposalType":"remove-member","proposalData":{"memberID":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","reason":"Leaving group by proposal to test leaving chatroom"},"expires_date_ms":1740690136166,"createdDate":"2025-02-13T21:02:16.169Z","creatorID":"z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf","proposalId":"z9brRu3VL5rVvVKwkkX476iuPaa9Ljt6nRgDJAaovRCGi5yEWuWK","status":"open"}},{"type":"interactive","hash":"z9brRu3VEyxePHuFdpJXRxUbVHpD15crxAGSBcJBSA73ianDSD3K","height":6,"from":"z9brRu3VWZAZrJNyfPGqW2DQjFBiyakXyz1yFbdPoHe6rXpcM3km","datetime":"2025-02-13T21:02:16.963Z","proposal":{"proposalType":"remove-member","proposalData":{"memberID":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","reason":"Leaving group by proposal to test leaving chatroom"},"expires_date_ms":1740690136166,"createdDate":"2025-02-13T21:02:16.169Z","creatorID":"z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf","proposalId":"z9brRu3VL5rVvVKwkkX476iuPaa9Ljt6nRgDJAaovRCGi5yEWuWK","status":"passed"}},{"type":"notification","hash":"z9brRu3VFw3YwbrjBmKB3FhCsb994XoHYLPH2UbGWdmM8Piev7qE","height":7,"from":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA","datetime":"2025-02-13T21:02:17.113Z","notification":{"type":"leave-member","params":{"channelName":"general","channelDescription":"","memberID":"z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA"}}},{"type":"notification","hash":"z9brRu3VSg5JcSBLEsALquxnwfCbkiBdcymc6BUCZuR5MzFFnVf8","height":10,"from":"z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf","datetime":"2025-02-13T21:02:23.968Z","notification":{"type":"leave-member","params":{"channelName":"general","channelDescription":"","memberID":"z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf"}}},{"type":"notification","hash":"z9brRu3VUf4EQv44aS5bm1hpaED8yyrdJdQp8SGpq9TGZMz1KhHb","height":11,"from":"z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf","datetime":"2025-02-13T21:02:25.830Z","notification":{"type":"leave-member","params":{"channelName":"general","channelDescription":"","memberID":"z9brRu3VNoKxQ8XcuTf8EvY3aQFiNjMu8pZEduk1W9eRo7rnMzwf"}}}],"pinnedMessages":[],"renderingContext":true,"_volatile":{"pendingKeyRevocations":{}}}]]
  ["log","Avatar under vue-component-26-Tooltip blobURL:",null,"src:",null]
  ["debug","[sbp] state/vuex/save",[]]
  ["debug","[sbp] okTurtles.eventQueue/queueEvent",["state/vuex/save",null]]
  ["debug","[sbp] 'gi.db/settings/save'","z9brRu3VWwaPuMCGuGqYhoaUvf5qyGk5ZPETS13D2J164bQeqyqA"]]
```

</details>

### Solution

Fix...

### PR DESCRIPTION
**Pull request by corrideat**
Closes #2624

### CODE REVIEW

File: frontend/model/contracts/group.js [hunk 1]
```diff
@@ -1590,7 +1591,7 @@ sbp('chelonia/defineContract', {
         state?.chatRooms?.[chatRoomID]?.members[memberID]?.status !== PROFILE_STATUS.ACTIVE ||
         state?.chatRooms?.[chatRoomID]?.members[memberID]?.joinedHeight !== height
       ) {
-        sbp('okTurtles.data/set', `gi.contracts/group/chatroom-skipped-${contractID}-${chatRoomID}-${height}`, true)
+        console.info('[gi.contracts/group/joinGroupChatrooms] Skipping outdated action', { actorID, contractID, chatRoomID, originalActorID, memberID, height, groupStatusActor: state?.profiles?.[actorID]?.status, groupSatusMember: state?.profiles?.[memberID]?.status, chatRoomStatus: state?.chatRooms?.[chatRoomID]?.members[memberID]?.status, chatRoomHeight: state?.chatRooms?.[chatRoomID]?.members[memberID]?.joinedHeight })
```
Comment (taoeffect) [inline frontend/model/contracts/group.js]: This line is absurdly long. Could you please modify it to read:

```js
        console.info('[gi.contracts/group/joinGroupChatrooms] Skipping outdated action', {
          actorID, contractID, chatRoomID, originalActorID, memberID, height,
          groupStatusActor: state?.profiles?.[actorID]?.status,
          groupSatusMember: state?.profiles?.[memberID]?.status,
          chatRoomStatus: state?.chatRooms?.[chatRoomID]?.members[memberID]?.status,
          chatRoomHeight: state?.chatRooms?.[chatRoomID]?.members[memberID]?.joinedHeight
        })
```

File: frontend/model/contracts/group.js [hunk 2]
```diff
@@ -1582,6 +1582,7 @@ sbp('chelonia/defineContract', {
 
       // Session has changed
       if (actorID !== originalActorID) {
+        console.info('[gi.contracts/group/joinGroupChatrooms] Session changed', { actorID, contractID, chatRoomID, originalActorID, memberID, height })
```
Comment (taoeffect) [inline frontend/model/contracts/group.js]: Please shorten to:

```js
        console.info('[gi.contracts/group/joinGroupChatrooms] Session changed', {
          actorID, contractID, chatRoomID, originalActorID, memberID, height
        })
```

**Review by taoeffect — CHANGES_REQUESTED** [review]
Awesome job @corrideat! Minor formatting change request.

**Review by taoeffect — APPROVED** [review]
Awesome!
