### PR TITLE
#2676 - Fix undismissible Signup modal issue

### LINKED ISSUE #2676: Cannot dismiss SignUp modal on error
### Problem

Image

If an error occurred while signing up, you cannot dismiss the signup modal:

- Clicking "X" doesn't work
- Clicking the background doesn't work
- Clicking "Log in" link doesn't work

### Solution

Fix.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #2676

### CODE REVIEW

File: frontend/views/containers/access/SignupModal.vue [hunk 1]
```diff
@@ -53,7 +53,7 @@ export default ({
           break
         }
         default: // 'error' status
-          this.ephemeral.isSigningUp = true
+          this.ephemeral.isSigningUp = false
```
Comment (SebinSong) [inline frontend/views/containers/access/SignupModal.vue:56]: This is a typo that went unnoticed in the last PR

**Review by taoeffect — APPROVED** [review]
Nice!
