### PR TITLE
Fix UI issues and minor simplifications

### LINKED ISSUE #1627: [Bug] Chat channel menu doesn't work
### Problem

https://github.com/okTurtles/group-income/assets/138706/c8a97aa2-8aad-4594-a443-8de3fa724408

### Solution

Fix.

### LINKED ISSUE #1636: DMs are not displayed per-group
### Problem

DMs are not per-group as seen in this video:

https://github.com/okTurtles/group-income/assets/138706/53477a49-6181-4735-8697-10ae877f1af4

Reproduce:

1. u1 create a group (g1)
2. u1 invite u2, and u2 join (in a separate container tab)
3. u1 invite u4, and u4 join (in a separate container tab)
4. u1 create DM with u2 in g1
5. u3 sign up (in a separate container tab) create a new group (g2)
6. u3 copy invite link and invite u1 to join g2
7. u1 now part of g1 and g2, switch between them, see DM between u1 and u2 visible in both groups

### Solution

Find and fix the getters that are not scoped to per-group properly.

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of Changes

- Closes #1627 
- Fixed some more issues regarding `Menu` component
- Deleted `Message.vue` page
- Simplified `ProfileCard` using `DMMixin`
- Added `Update description` in menu
- Improve page layout styles and truncate page title in desktop view

### CODE REVIEW

**Review by Silver-IT — COMMENTED** [review]
@taoeffect, @SebinSong. Ready for your reviews.

File: frontend/views/components/ProfileCard.vue [hunk 1]
```diff
@@ -161,28 +162,13 @@ export default ({
...
-              hidden: false
-            }
-          })
+          this.setDMVisibility(chatRoomId, false)
         } else {
-          this.$router.push({
-            name: 'GroupChatConversation',
-            params: { chatRoomId }
-          }).catch(logExceptNavigationDuplicated)
+          this.redirect(chatRoomId)
```
Comment (taoeffect) [inline frontend/views/components/ProfileCard.vue:171]: None of the potential errors are being handled here, so I opened a separate issue to address this: #1647

File: frontend/views/components/Page.vue [hunk 2]
```diff
@@ -183,13 +183,6 @@ $pagePaddingDesktop: 5.5rem;
   display: flex;
   align-items: center;
 
-  > span {
-    width: fit-content;
-    white-space: nowrap;
-    overflow: hidden;
-    text-overflow: ellipsis;
-  }
-
```
Comment (taoeffect) [inline frontend/views/components/Page.vue]: @SebinSong can you double-check this deletion?

**Review by taoeffect — DISMISSED** [review]
Looks good to me but I'd like to hear what @SebinSong thinks as well regarding some of the CSS changes.

File: frontend/views/components/Page.vue (hunk 2 above)
Comment (Silver-IT) [reply frontend/views/components/Page.vue]: This style seems like to truncate the title. But based on my testing, it doesn't truncate.
Because `overflow: hidden` style, the group chat menu can't be visible. So I removed it.

Comment (taoeffect) [reply frontend/views/components/Page.vue]: This was a recent change by @SebinSong so I think it might be important

Comment (SebinSong) [reply frontend/views/components/Page.vue]: @taoeffect is correct. This is a bug-fix for [this](https://github.com/okTurtles/group-income/issues/1576) recently-closed issue.  These lines of code needs to be kept. @Silver-IT

Comment (taoeffect) [reply frontend/views/components/Page.vue]: (EDIT: looks like Sebin commented at the same time) OK, I tested this and this was a requested change that @SebinSong made in a recently approved and merged PR. It's supposed to look like this:

Screen Shot 2023-06-07 at 6 38 58 PM

But now looks like this:

Screen Shot 2023-06-07 at 6 38 40 PM

Please undo this change, and in the future please also also double-check with the author of the code if you'd like to delete their code if the author is available and it wasn't a requested change. 🙏

**Review by taoeffect — CHANGES_REQUESTED** [review]
@Silver-IT See review!

File: frontend/views/components/Page.vue (hunk 2 above)
Comment (Silver-IT) [reply frontend/views/components/Page.vue]: Because of this `overflow: hidden`, Issue #1627 is raised. I will try to find another way to fix both issues (#1576, #1627 ) together.

Comment (taoeffect) [reply frontend/views/components/Page.vue]: I don't understand how #1627 is related to this, can you elaborate?

Comment (Silver-IT) [reply frontend/views/components/Page.vue]: Those styles are for the `span` element.
`Menu` is the child component of this `span` which has the style `overflow: hidden`.
So when the `Menu`'s `position` is `absolute`, the menu content can only be visible inside this span and out side of this span would be hidden.

Comment (Silver-IT) [reply frontend/views/components/Page.vue:192]: Check this `span` element and `[data-test="menuContent"]` element.

Comment (Silver-IT) [reply frontend/views/components/Page.vue]: Check this `span` element and `[data-test="menuContent"]` element.
image

Comment (taoeffect) [reply frontend/views/components/Page.vue]: Oh I see, understood 👍

**Review by Silver-IT — COMMENTED** [review]
Removed changes on other pages instead of `GroupChat`. I think it's fine now. :grin: :grin: :grin:

File: frontend/views/components/Page.vue [hunk 3]
```diff
@@ -186,12 +186,12 @@ $pagePaddingDesktop: 5.5rem;
...
     max-width: 100%;
 
-    & > span {
+    &:not(:has(*)) {
       display: block;
       max-width: 100%;
     }
 
-    & > span,
+    &:not(:has(*)),
```
Comment (taoeffect) [inline frontend/views/components/Page.vue]: What does `:has(*)` mean? I've never seen this before. /cc @SebinSong your thoughts also appreciated

File: frontend/views/components/Page.vue [hunk 4]
```diff
@@ -183,14 +183,24 @@ $pagePaddingDesktop: 5.5rem;
...
+      max-width: 100%;
+    }
+
+    &:not(:has(*)),
+    & > .c-header > span {
+      width: fit-content;
+      white-space: nowrap;
+      overflow: hidden;
+      text-overflow: ellipsis;
+    }
```
Comment (taoeffect) [inline frontend/views/components/Page.vue]: What does `:has(*)` mean? I've never seen this before. /cc @SebinSong your thoughts also appreciated

Comment (Silver-IT) [reply frontend/views/components/Page.vue]: `Has any child element`. Only `GroupChat` page has child elements.

Dashboard
```
<span> Group Income Contributors<span>
```
Group Chat
```
<span>
  <div>
    ...
  </div>
</span>
```

Comment (taoeffect) [reply frontend/views/components/Page.vue]: Since this block is starting to look quite complicated, could you please document as clearly as you can, in a comment above line 186, what these changes are doing and why these different cases? Maybe also include link references to related issues.

Comment (SebinSong) [reply frontend/views/components/Page.vue]: @Silver-IT Let me take some time investigating the original issue in a separate branch and get back to this thread.

Comment (SebinSong) [reply frontend/views/components/Page.vue]: @taoeffect @Silver-IT 
Just created a PR for the original issue that has less tweaks.
https://github.com/okTurtles/group-income/pull/1650/files

**Review by Silver-IT — COMMENTED** [review]
@taoeffect, @SebinSong. It seems ready for the final review.

**Review by taoeffect — APPROVED** [review]
Approved! Great job @Silver-IT! 😄 👍
