### PR TITLE
Messaging functions in group chat page

### LINKED ISSUE #1227: "Duplicate keys detected:" in ChatMain.vue
### Problem

I'm not sure if this happens in `master`, but it definitely happens in many of the Cypress tests in my PR (#1224).

An error will flash in the console during the tests. It won't prevent the tests from passing, but it clearly indicates something is wrong:

Screen Shot 2022-04-24 at 3 53 09 PM

### Solution

Based on the error message, something is affected by `setMessageEventListener`, possibly a `v-for` loop. I am guessing it might be `:key='message.id'`.

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of changes

1. Edit / Delete messages
2. Make reactions ( Add / Remove emoticons )
3. Some UI updates
4. Closes #1227 

### TODO
1. `(edited)` label for the edited text ( in the next Pull Request #1274 )

### CODE REVIEW

**Review by Silver-IT — COMMENTED** [review]
TODO: fix error regarding emoticons ( Not well reacted between UI and variable in ChatMain.vue )

File: frontend/model/contracts/chatroom.js [hunk 1]
```diff
@@ -124,17 +124,24 @@ function createNotificationData (
...
-    if (state.messages[i].id === hash) {
-      sbp('okTurtles.events/emit', `${CHATROOM_MESSAGE_ACTION}-${contractID}`, {
-        type,
-        data: { message: state.messages[i] }
-      })
-      break
+  let data = {}
+  if (type === MESSAGE_ACTION_TYPES.ADD_MESSAGE || type === MESSAGE_ACTION_TYPES.EDIT_MESSAGE) {
+    const messagesCount = state?.messages.length || 0
+    for (let i = messagesCount - 1; i >= 0; i--) {
```
Comment (snowteamer) [inline frontend/model/contracts/chatroom.js:149]: What is the reason to use a reverse loop rather than a regular loop of `.find()` call?

File: frontend/views/containers/chatroom/ChatMain.vue [hunk 2]
```diff
@@ -255,6 +258,39 @@ export default ({
       this.ephemeral.replyingMessage = message.text
       this.ephemeral.replyingTo = this.who(message)
     },
+    editMessage (message, newMessage) {
+      console.log('updating...')
```
Comment (snowteamer) [inline frontend/views/containers/chatroom/ChatMain.vue]: Are these log statements still necessary?

File: frontend/views/containers/chatroom/ChatMain.vue [hunk 3]
```diff
@@ -255,6 +258,39 @@ export default ({
...
+        }
+      })
+    },
+    sendMessage (index) {
+      this.ephemeral.replyingMessage = null
+      this.ephemeral.replyingTo = null
+      setTimeout(() => {
+        console.log('TODO $store send message')
+        // this.$set(this.ephemeral.pendingMessages[index], 'hasFailed', true)
+      }, 2000)
```
Comment (snowteamer) [inline frontend/views/containers/chatroom/ChatMain.vue]: This doesn't seem to do anything

File: test/cypress/integration/group-chat-message.spec.js [hunk 4]
```diff
@@ -0,0 +1,210 @@
...
+      cy.get('.c-message').eq(0).find('.c-text').should('contain', `Joined ${CHATROOM_GENERAL_NAME}`)
+
+      cy.get('.c-message').eq(1).find('.c-who > span:first-child').should('contain', user2)
+      cy.get('.c-message').eq(1).find('.c-text').should('contain', `Joined ${CHATROOM_GENERAL_NAME}`)
+
+      cy.get('.c-message').eq(2).find('.c-who > span:first-child').should('contain', user2)
+      cy.get('.c-message').eq(2).find('.c-text').should('contain', 'Can we have a meeting this evening?')
+
+      cy.get('.c-message').eq(3).find('.c-who > span:first-child').should('contain', user1)
+      cy.get('.c-message').eq(3).find('.c-text').should('contain', `Hi ${user2}. I am fine thanks.`)
```
Comment (snowteamer) [inline test/cypress/integration/group-chat-message.spec.js]: Couldn't we reduce code duplication and line lengths by defining some other helper functions, for example `checkSender()`, `checkMessage()`, or something similar?

**Review by snowteamer — DISMISSED** [review]
Great work once again!

I don't have much feedback to give, although I would appreciate:
- some loop optimizations (if possible and not too difficult, otherwise nevermind)
- a few more helper functions in Cypress tests, to make them nicer

File: frontend/views/containers/chatroom/MessageActions.vue [hunk 5]
```diff
@@ -104,8 +107,17 @@ export default ({
...
     isCurrentUser: Boolean
   },
+  computed: {
+    isEditable (): Boolean {
+      if (this.type === MESSAGE_TYPES.TEXT) {
+        return true
+      }
+      return false
+    }
+  },
```
Comment (pieer) [inline frontend/views/containers/chatroom/MessageActions.vue:117]: Maybe we could simplify with online
return this.type === MESSAGE_TYPES.TEXT

File: frontend/model/contracts/chatroom.js (hunk 1 above)
Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js:149]: As you know, the purpose is to find a `message` having same hash as it's `id`.
I think if we do reverse loop, we can save calculation and time to get the right message.
That's because in most cases, we will update message which we sent just before.
We don't update message which I sent long time ago.

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 2 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue]: No. I will remove it. Nice catch.

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 3 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue]: This `sendMessage` function is not necessary at all. I will remove it.

File: test/cypress/integration/group-chat-message.spec.js (hunk 4 above)
Comment (Silver-IT) [reply test/cypress/integration/group-chat-message.spec.js]: Correct. I will update.

File: test/cypress/integration/group-chat-message.spec.js [hunk 6]
```diff
@@ -164,19 +171,12 @@ describe('Send/edit/remove messages & add/remove emoticons inside group chat', (
...
-      cy.get('.c-message').eq(2).find('.c-text').should('contain', 'Can we have a meeting this evening?')
-
-      cy.get('.c-message').eq(3).find('.c-who > span:first-child').should('contain', user1)
-      cy.get('.c-message').eq(3).find('.c-text').should('contain', `Hi ${user2}. I am fine thanks.`)
     })
+
+    checkMessageBySender(0, user1, `Joined ${CHATROOM_GENERAL_NAME}`)
+    checkMessageBySender(1, user2, `Joined ${CHATROOM_GENERAL_NAME}`)
+    checkMessageBySender(2, user2, 'Can we have a meeting this evening?')
+    checkMessageBySender(3, user1, `Hi ${user2}. I am fine thanks.`)
```
Comment (snowteamer) [inline test/cypress/integration/group-chat-message.spec.js:179]: Now this looks great!

**Review by snowteamer — DISMISSED** [review]

File: frontend/model/contracts/chatroom.js (hunk 1 above)
Comment (snowteamer) [reply frontend/model/contracts/chatroom.js:149]: Fair point. I've also been thinking that keeping track of the `id` <-> `message` mappings could sometimes allow to do plain lookups such as `messagesById[hash]` instead of loops, but the mappings object would have to be updated every time a message is added or removed, so I'm not sure.

Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js:149]: In `chat-contract-optimize` branch, I am going to remove `state.messages` to save in the vuex store.
So we can save disk and performance too.

File: frontend/views/containers/chatroom/SendArea.vue [hunk 7]
```diff
@@ -150,8 +153,20 @@ export default ({
...
+      return objElement.id === 'mobileSendButton'
+    },
+    textAreaBlur (event) {
+      if (this.ephemeral.isPhone) {
+        if (this.checkIfMobileSendButton(event.relatedTarget)) {
+          this.sendMessage()
+        } else {
+          this.ephemeral.showButtons = true
+        }
+      }
```
Comment (pieer) [inline frontend/views/containers/chatroom/SendArea.vue:165]: This 10 lines could be simplified in 2 lines maybe:
if (!this.ephemeral.isPhone) return;
event?.relatedTarget?.id === 'mobileSendButton' ? this.sendMessage() : this.ephemeral.showButtons = true

File: frontend/views/containers/chatroom/SendArea.vue [hunk 8]
```diff
@@ -199,7 +214,7 @@ export default ({
       this.$emit('stop-replying')
     },
     sendMessage () {
-      console.log('send')
+      console.log('send', this.$refs.textarea.value)
```
Comment (pieer) [inline frontend/views/containers/chatroom/SendArea.vue]: Remove console log now?

Comment (Silver-IT) [reply frontend/views/containers/chatroom/SendArea.vue]: Yeap.

File: frontend/views/containers/chatroom/MessageActions.vue (hunk 5 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/MessageActions.vue:117]: Nice catch. Thanks

File: frontend/views/containers/chatroom/SendArea.vue (hunk 7 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/SendArea.vue:165]: Yeap. That's right.

**Review by snowteamer — DISMISSED** [review]

File: frontend/model/contracts/chatroom.js [hunk 9]
```diff
@@ -129,17 +129,24 @@ function createNotificationData (
...
+      if (state?.messages[i].id === hash) {
+        data = { message: { ...state?.messages[i] } }
+        break
+      }
     }
+  } else if (type === MESSAGE_ACTION_TYPES.DELETE_MESSAGE) {
+    data = { id: hash }
```
Comment (taoeffect) [inline frontend/model/contracts/chatroom.js:156]: This is confusing me, it suggests that there are two different shapes to the `data` object.

Sometimes `data` contains the `id` directly inside of it, as above: `{ id: hash }`

Other times the `id` is stored inside another object, as on line 142: `{ message: { id, ... } }`

Won't think cause confusion and potential bugs in the rest of the code? Should perhaps this `data` be made more consistent, so that `id` is in the same place in both cases?

File: frontend/model/contracts/chatroom.js [hunk 10]
```diff
@@ -129,17 +129,24 @@ function createNotificationData (
...
 }): void {
-  for (let i = state.messages.length - 1; i >= 0; i--) {
-    if (state.messages[i].id === hash) {
-      sbp('okTurtles.events/emit', `${CHATROOM_MESSAGE_ACTION}-${contractID}`, {
-        type,
-        data: { message: state.messages[i] }
-      })
-      break
+  let data = {}
+  if (type === MESSAGE_ACTION_TYPES.ADD_MESSAGE || type === MESSAGE_ACTION_TYPES.EDIT_MESSAGE) {
```
Comment (taoeffect) [inline frontend/model/contracts/chatroom.js:147]: If `state` is `null` or `undefined`, then this section of the `if` statement won't do anything.

So instead of having constant checks for `state?.` below, couldn't you add `state` to the condition here? E.g. something like:

```js
  if (state && (type === MESSAGE_ACTION_TYPES.ADD_MESSAGE || type === MESSAGE_ACTION_TYPES.EDIT_MESSAGE)) {
```

BUT - an even better question - why are you making `state` optional here? Isn't it passed in everywhere this function is called? If so, then you can update the function parameters to indicate it mandatory, and remove the `state?` stuff below and just make it `state.messages`

File: frontend/model/contracts/chatroom.js [hunk 11]
```diff
@@ -327,36 +334,94 @@ sbp('chelonia/defineContract', {
...
+        objectOf({
+          id: string,
+          text: string
+        })(data)
+        // TODO: need to check if the meta.username === message.from
+      },
       process ({ data, meta }, { state }) {
-
+        for (let i = state.messages.length - 1; i >= 0; i--) {
+          if (state.messages[i].id === data.id) {
```
Comment (taoeffect) [inline frontend/model/contracts/chatroom.js]: I agree with @snowteamer  - this pattern is showing up in your code in several places, so let's DRY this.

I also agree with you @Silver-IT, that it's better to start the search from the end instead of the beginning, and so we should implement our own version of `.find`, e.g. something like:

```js
function findMessageIdx(id, messages) {
  for (let i = messages.length - 1; i >= 0; i--) {
    if (messages[i].id === id) {
      return i
    }
  }
  return -1
}
```

Then you can remove the loops you have everywhere else.

File: frontend/model/contracts/chatroom.js (hunk 9 above)
Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js:156]: Got it. I just wanted to send only necessary data especially only `id`, however I needed to keep consistency of the data type. I agree with it.

But can we skip this in this PR? Because we are not sending those data anymore.
You can see what I am saying if you review PR #1274. 

> sbp('okTurtles.events/emit', `${CHATROOM_MESSAGE_ACTION}-${contractID}`, { hash })

I send only `hash` and no other data in the next  PR.
But anyway, I understand your point and will keep it in my mind.

Comment (taoeffect) [reply frontend/model/contracts/chatroom.js:156]: > But can we skip this in this PR? Because we are not sending those data anymore.

OK, sure 👍

File: frontend/model/contracts/chatroom.js (hunk 10 above)
Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js:147]: Correct. Just make `state` parameter mandatory and remove `?`. Nice catch. Thanks

File: frontend/model/contracts/chatroom.js (hunk 11 above)
Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js]: Nice catch. 10Q

File: frontend/model/contracts/chatroom.js [hunk 12]
```diff
@@ -327,36 +343,88 @@ sbp('chelonia/defineContract', {
...
+              emoticons[emoticon].push(meta.username)
+            }
+          } else {
+            emoticons[emoticon] = [meta.username]
+          }
+          if (emoticons) {
+            Vue.set(state.messages[msgIndex], 'emoticons', emoticons)
+          } else {
+            Vue.delete(state.messages[msgIndex], 'emoticons')
+          }
```
Comment (taoeffect) [inline frontend/model/contracts/chatroom.js]: This code could be simplified & shortened by leaving an empty list when there are no more emoticons left. I don't think it needs the code that completely deletes the entire emoticons list.

File: strings/french.json [hunk 13]
```diff
@@ -420,8 +423,8 @@
   "*This value was automatically adjusted because your group is too small for the disagreement number.": "*Cette valeur a été ajustée automatiquement car la taille de votre groupe est trop petite pour le seuil de désaccord.",
   "Active": "Actif",
   "Change to this system": "Choisir ce système",
-  "Maximum number of \"no\" votes:": "Nombre maximal de votes négatifs :",
-  "Percentage of members that need to agree:": "Pourcentage de votes positifs requis :",
+  "Maximum number of \"no\" votes:": "Nombre maximal de votes négatifs:",
+  "Percentage of members that need to agree:": "Pourcentage de votes positifs requis:",
```
Comment (taoeffect) [inline strings/french.json]: I think we decided that the spaces should exist for French, right @pieer @snowteamer ?

File: frontend/model/contracts/chatroom.js (hunk 12 above)
Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js]: Of course, if there are `emoticons` empty list, there won't be any thing wrong.
All things will work well and nothing breaks. But no need to save redundant thing, don't we?
I think the problem is to shorten the code lines instead of leaving empty array.

File: strings/french.json (hunk 13 above)
Comment (Silver-IT) [reply strings/french.json]: I forgot to run `strings.linux`. After I run it and commit again, they are all solved.
Nice catch, @taoeffect.

File: frontend/model/contracts/chatroom.js (hunk 12 above)
Comment (taoeffect) [reply frontend/model/contracts/chatroom.js]: Well, shorter code is easier to read, understand, and has fewer bugs...

What is the harm with leaving an empty array? These messages will get cleared out of memory eventually anyway.

**Review by taoeffect — CHANGES_REQUESTED** [review]
Looking really good @Silver-IT! I think this is almost ready to merge.

Something that's missing is the little `(edited)` grey text that should appear on messages that have been edited:

Screen Shot 2022-05-15 at 6 19 32 PM

Also, I do still think [this emoticon code](https://github.com/okTurtles/group-income/pull/1264#pullrequestreview-973312189) could be improved by leaving the empty list instead of deleting it. It would improve readability and reduce the likelihood of bugs, with little to no downside.

File: frontend/model/contracts/chatroom.js (hunk 12 above)
Comment (Silver-IT) [reply frontend/model/contracts/chatroom.js]: > These messages will get cleared out of memory eventually anyway.

This makes sense. I will remove the redundant codes then.

**Review by taoeffect — APPROVED** [review]
Great work @Silver-IT! Approved!! 😄 🎉
