### PR TITLE
Fix chatroom rendering issue

### LINKED ISSUE #2798: Forcibly removing a user as admin breaks the #general chatroom
### Problem

@snowteamer forgot his password to GIG, so I decided to remove him and then re-invite him to the group.

I used my admin perms in this dialog to remove him:

Image

After that he was shown as having left the general chatroom:

Image

Then I typed some messages but after I hit send they didn't appear at all in the chatroom! 😱

https://github.com/user-attachments/assets/f0755bd5-268f-45c9-9b7a-7297ddf7a344

There were some errors in the console, including "SIgning key __ is missing permissions for operation ae":

Image

📎 Logs: [gi_logs.json(snow-removed+msg).txt](https://github.com/user-attachments/files/20400552/gi_logs.json.snow-removed%2Bmsg.txt)

When switching to the general chatroom from another view, however, you can see that the messages are there! But they vanish after a few seconds:

https://github.com/user-attachments/assets/680e047d-03bb-4b02-9b5f-92d03bc163a2

This is all on GIG which is running 1.2.18.

NOTE: I tried reproducing this with `testing` and couldn't. However, on the testing server group the distribution period hasn't started yet and to perfectly reproduce this I would assume at least one period would have to have completed payments. (So you'd need to be in payment period 2 before trying).

-------------

More weirdness: Snowteamer can't rejoin the group for some reason:

https://github.com/user-attachments/assets/173fb28a-fb9f-4fd9-851c-a6ef00a8f462

But I was able to successfully with another user, using Firefox Dev Edition. However, there were some errors in the SW..

Image

Image

Image

EDIT: Apparently he can on Firefox, but not on Brave. Weird!

### Solution

Try to reproduce locally, then identify the problem and fix.

### PR DESCRIPTION
**Pull request by corrideat**
Closes #2798

### CODE REVIEW

File: shared/domains/chelonia/utils.js [hunk 1]
```diff
@@ -236,7 +236,9 @@ export const validateKeyUpdatePermissions = (contractID: string, signingKey: SPK
     if (uk.id && uk.id !== uk.oldKeyId) {
       updatedMap[uk.id] = uk.oldKeyId
     }
-    const updatedKey = { ...existingKey }
+    // Discard `_notAfterHeight` and `_notBeforeHeight`, since retaining them
+    // can cause issues reprocessing messages.
+    const { _notAfterHeight, _notBeforeHeight, ...updatedKey } = { ...existingKey }
```
Comment (taoeffect) [inline shared/domains/chelonia/utils.js]: Question + request:

- Wouldn't this trigger an unused variable linter warning? (And if not... why not?)
- Could you elaborate on the comment a bit more and give maybe 1 example of an issue that would happen?

**Review by taoeffect — COMMENTED** [review]
Nice work @corrideat, I'm not sure how to test so I'll assume this fixes it.

Added a small RFC + a question for you, and also added this to Chelonia changes milestone.

**Comment by corrideat** [comment]
Sample reproducing the issue and the fix.

```js
const unwrapMaybeEncryptedData = (data) => ({ encryptionKeyId: null, data })
const validateKeyAddPermissions = (contractID, signingKey, state, v, skipPrivateCheck) => {
  const signingKeyPermissions = Array.isArray(signingKey.permissions) ? new Set(signingKey.permissions) : signingKey.permissions
  const signingKeyAllowedActions = Array.isArray(signingKey.allowedActions) ? new Set(signingKey.allowedActions) : signingKey.allowedActions
  if (!state._vm?.authorizedKeys?.[signingKey.id]) throw new Error('Singing key for OP_KEY_ADD or OP_KEY_UPDATE must exist in _vm.authorizedKeys. contractID=' + contractID + ' signingKeyId=' + signingKey.id)
  const localSigningKey = state._vm.authorizedKeys[signingKey.id]
  v.forEach(wk => {
    const data = unwrapMaybeEncryptedData(wk)
    if (!data) return
    const k = data.data
    if (!skipPrivateCheck && signingKey._private && !data.encryptionKeyId) {
      throw new Error('Signing key is private but it tried adding a public key')
    }
    if (!Number.isSafeInteger(k.ringLevel) || k.ringLevel < localSigningKey.ringLevel) {
      throw new Error('Signing key has ringLevel ' + localSigningKey.ringLevel + ' but attempted to add or update a key with ringLevel ' + k.ringLevel)
    }
    if (signingKeyPermissions !== '*') {
      if (!Array.isArray(k.permissions) || !k.permissions.reduce((acc, cv) => acc && signingKeyPermissions.has(cv), true)) {
        throw new Error('Unable to add or update a key with more permissions than the signing key. signingKey permissions: ' + String(signingKey?.permissions) + '; key add permissions: ' + String(k.permissions))
      }
    }
    if (signingKeyAllowedActions !== '*' && k.allowedActions) {
      if (!signingKeyAllowedActions || !Array.isArray(k.allowedActions) || !k.allowedActions.reduce((acc, cv) => acc && signingKeyAllowedActions.has(cv), true)) {
        throw new Error('Unable to add or update a key with more allowed actions than the signing key. signingKey allowed actions: ' + String(signingKey?.allowedActions) + '; key add allowed actions: ' + String(k.allowedActions))
      }
    }
  })
}

const validateKeyUpdatePermissions = (contractID, signingKey, state, v) => {
  const updatedMap = Object.create(null)
  const keys = v.map((wuk) => {
    const data = unwrapMaybeEncryptedData(wuk)
    if (!data) return undefined
    const uk = data.data

    const existingKey = state._vm.authorizedKeys[uk.oldKeyId]
    if (!existingKey) {
      throw new Error('Missing old key ID ' + uk.oldKeyId)
    }
    if (!existingKey._private !== !data.encryptionKeyId) {
      throw new Error('_private attribute must be preserved')
    }
    if (uk.name !== existingKey.name) {
      throw new Error('Name cannot be updated')
    }
    if (!uk.id !== !uk.data) {
      throw new Error('Both or none of the id and data attributes must be provided. Old key ID: ' + uk.oldKeyId)
    }
    if (uk.data && existingKey.meta?.private && !(uk.meta?.private)) {
      throw new Error('Missing private key. Old key ID: ' + uk.oldKeyId)
    }
    if (uk.id && uk.id !== uk.oldKeyId) {
      updatedMap[uk.id] = uk.oldKeyId
    }
    // Was:    const updatedKey = { ...existingKey }
    const { _notAfterHeight, _notBeforeHeight, ...updatedKey } = { ...existingKey }
    // Set the corresponding updated attributes
    if (uk.permissions) {
      updatedKey.permissions = uk.permissions
    }
    if (uk.allowedActions) {
      updatedKey.allowedActions = uk.allowedActions
    }
    if (uk.purpose) {
      updatedKey.purpose = uk.purpose
    }
    if (uk.meta) {
      updatedKey.meta = uk.meta
    }
    if (uk.id) {
      updatedKey.id = uk.id
    }
    if (uk.data) {
      updatedKey.data = uk.data
    }
    return updatedKey
  }).filter(Boolean)
  validateKeyAddPermissions(contractID, signingKey, state, keys, true)
  return [keys, updatedMap]
}
const has = Function.prototype.call.bind(Object.prototype.hasOwnProperty)

const update = (contractID, height, signingKey, state, v) => {
  if (!state._volatile) state._volatile = Object.create(null)
  if (!state._volatile.pendingKeyRevocations) state._volatile.pendingKeyRevocations = Object.create(null)
  const [updatedKeys, updatedMap] = validateKeyUpdatePermissions(contractID, signingKey, state, v)
  const keysToDelete = Object.values(updatedMap)
  for (const keyId of keysToDelete) {
    if (has(state._volatile.pendingKeyRevocations, keyId)) {
      delete state._volatile.pendingKeyRevocations[keyId]
    }

    state._vm.authorizedKeys[keyId]._notAfterHeight = height
  }
  for (const key of updatedKeys) {
    if (!has(state._vm.authorizedKeys, key.id)) {
      key._notBeforeHeight = height
      console.error('@@@', key.id, JSON.stringify(key))
      state._vm.authorizedKeys[key.id] = JSON.parse(JSON.stringify(key))
    }
  }
}

const state = JSON.parse('{"settings":{},"attributes":{},"members":{},"_vm":{"type":"gi.contracts/chatroom","authorizedKeys":{"z2DrjgbL446xTvBTBTq2YQPQwJrZKbjsFCHVgQ78Lj1vX6YWhHd":{"id":"z2DrjgbL446xTvBTBTq2YQPQwJrZKbjsFCHVgQ78Lj1vX6YWhHd","name":"csk","purpose":["sig"],"ringLevel":0,"permissions":"*","allowedActions":"*","foreignKey":"sp:z9brRu3VKAT4KcwCvVhaTE6HHyJhDb4zQybujaDUNX8k9wbFHBE7?keyName=csk","data":"[\\"edwards25519sha512batch\\",\\"LvX7s6wQXnKtZSrS9ZMq70qJktGHa55QCCHLqo/nQNc=\\",null]","_notBeforeHeight":0,"_notAfterHeight":346},"z2DrjgbFT7bNeWntoW2Bj2R3ug3QmTxQLYyWf4PV1aocYuhkdQP":{"id":"z2DrjgbFT7bNeWntoW2Bj2R3ug3QmTxQLYyWf4PV1aocYuhkdQP","name":"cek","purpose":["enc"],"ringLevel":0,"permissions":["ae"],"allowedActions":"*","foreignKey":"sp:z9brRu3VKAT4KcwCvVhaTE6HHyJhDb4zQybujaDUNX8k9wbFHBE7?keyName=cek","data":"[\\"curve25519xsalsa20poly1305\\",\\"aDM9yg9KO83k4Q/KoC4CkO/Zj3xiS0+O39JhEXCPORI=\\",null]","_notBeforeHeight":0,"_notAfterHeight":346},"z2DrjgbK34AMK4eG3bGVqLqP348AP3VNw2Bbd4WRb45PW8WHTF2":{"id":"z2DrjgbK34AMK4eG3bGVqLqP348AP3VNw2Bbd4WRb45PW8WHTF2","name":"#sak","purpose":["sak"],"ringLevel":0,"permissions":[],"allowedActions":[],"meta":{"private":{"content":["z2DrjgbFT7bNeWntoW2Bj2R3ug3QmTxQLYyWf4PV1aocYuhkdQP","CwqyCaYl3FxNTqOJDdi8sLhreWpxZdfyM1RQgUjF1wdu4Vq8/mIEaip3m7tOhvwWW/64LurhGSlX6pYSkDQasD9Wf0GyBmJk+fW6DXeZt5E/k65jdMuti3cOxtEuXPrXZJ7KNr0kD8X4sYDqxvtF46w1284xQTyO4vGeMEHA+bQyl2Md+i4sabP8Q4T9pqyjYvH4ylWewz2wu+FgqaJBBDHeUQxDZON68qyz0YzNHQxYrW7nXa1eop/dolKz57Sw8bx1jFvW3jDB"]}},"data":"[\\"edwards25519sha512batch\\",\\"ULoNdAg18M8GIxYpNS4IFAtDvntPTaBtWZYunvo6WvM=\\",null]","_notBeforeHeight":0}}},"messages":[],"pinnedMessages":[],"renderingContext":true,"_volatile":{"pendingKeyRevocations":{}}}')

const msg = JSON.parse('{"_signedData":["[{\\"name\\":\\"csk\\",\\"oldKeyId\\":\\"z2DrjgbL446xTvBTBTq2YQPQwJrZKbjsFCHVgQ78Lj1vX6YWhHd\\",\\"id\\":\\"z2Drjgb4SQj9DZqADoaiEHuJkDYMGqnVjtesU8KjEpthUkz4UUv\\",\\"data\\":\\"[\\\\\\"edwards25519sha512batch\\\\\\",\\\\\\"NABcz4Tq5m4a1FmXM2H5r40Hx01cAiPwxiJWODiJ9po=\\\\\\",null]\\"},{\\"name\\":\\"cek\\",\\"oldKeyId\\":\\"z2DrjgbFT7bNeWntoW2Bj2R3ug3QmTxQLYyWf4PV1aocYuhkdQP\\",\\"id\\":\\"z2DrjgbJF9E3HvwhHBye82heY8zSVed1cQpMQbBmNcSbqdn7RNe\\",\\"data\\":\\"[\\\\\\"curve25519xsalsa20poly1305\\\\\\",\\\\\\"2jAs96YDeDdJHOJrDc4SDBjTXhb3o+BswwieSWi1mXA=\\\\\\",null]\\"}]","z2DrjgbL446xTvBTBTq2YQPQwJrZKbjsFCHVgQ78Lj1vX6YWhHd","LQ9rUg7l0kOPBzCX1JA/PR1w09xOWH0cXMIIqiou345ONwEBn98edkQnGadCeNxwFEB6ZPe9gJOJSNYJIxOrAg=="],"head":"{\\"version\\":\\"1.0.0\\",\\"previousHEAD\\":\\"z9brRu3VRhWzsoEGUabLBVdYv37DKFoe6eLvG8ia4sfT4QDVPWqD\\",\\"height\\":346,\\"contractID\\":\\"z9brRu3VGJAVdXihb29ooNjWxQZ5rDsxQj34szBK4LnGbRdLyArZ\\",\\"op\\":\\"ku\\",\\"manifest\\":\\"z9brRu3VFZVa9a79vabmzfVVVjxYAQJPgL2kfxZh9uqWYpycQrHm\\"}"}')

console.error(state._vm.authorizedKeys.z2DrjgbL446xTvBTBTq2YQPQwJrZKbjsFCHVgQ78Lj1vX6YWhHd)

update(
  'z9brRu3VGJAVdXihb29ooNjWxQZ5rDsxQj34szBK4LnGbRdLyArZ',
  346, // or any value, really
  state._vm.authorizedKeys.z2DrjgbL446xTvBTBTq2YQPQwJrZKbjsFCHVgQ78Lj1vX6YWhHd,
  state,
  JSON.parse(msg._signedData[0])
)

console.error(state._vm.authorizedKeys.z2DrjgbL446xTvBTBTq2YQPQwJrZKbjsFCHVgQ78Lj1vX6YWhHd)
console.error(state._vm.authorizedKeys.z2Drjgb4SQj9DZqADoaiEHuJkDYMGqnVjtesU8KjEpthUkz4UUv)
console.assert(state._vm.authorizedKeys.z2Drjgb4SQj9DZqADoaiEHuJkDYMGqnVjtesU8KjEpthUkz4UUv._notAfterHeight == null, '_notAfterHeight must not be set')
```

File: shared/domains/chelonia/utils.js (hunk 1 above)
Comment (corrideat) [reply shared/domains/chelonia/utils.js]: > Wouldn't this trigger an unused variable linter warning? (And if not... why not?)

Apparently it doesn't, not sure why. It does trigger such an error for libchelonia.

Comment (taoeffect) [reply shared/domains/chelonia/utils.js]: Consider `omit` from `turtledash`?

Comment (corrideat) [reply shared/domains/chelonia/utils.js]: Sure, but this way is likely faster.

**Comment by corrideat** [comment]
> Nice work @corrideat, I'm not sure how to test so I'll assume this fixes it.

One way of testing would be using the same DB as the GI app site. I tried logging in from a new device and noticed that the issue is reproducible. So, you can test by:

1. Loading the old DB and verifying that the issue happens.
2. Backporting this specific change and verifying that the issue is fixed.

I've also added a small comment (see above) with a minimally reproducible example of what happens.

**Review by taoeffect — APPROVED** [review]
Great work @corrideat! Seems like an important fix.
