### PR TITLE
#2953 - Cannot attach files from multiple folders

### LINKED ISSUE #2953: Cannot attach files from multiple folders
### Problem

If the user attaches a file(s) to chat and then attaches a file from a different folder, the original file(s) will be removed.

Steps to reproduce:
1. Attach files to chat 
2. Files are attached without issue
3. Attach files from a different folder
4. See original files have been removed, only files from second folder is attached

### Solution

Make it possible to attach files from multiple folders at the same time OR explain to the user that they have to be attached/sent separately.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #2953 

https://github.com/user-attachments/assets/6f275855-e76d-4302-9d72-4ac19aecc4a2

### CODE REVIEW

File: frontend/views/containers/chatroom/SendArea.vue [hunk 1]
```diff
@@ -742,20 +742,13 @@ export default ({
       e.target.blur()
       this.$refs.fileAttachmentInputEl.click()
     },
-    fileAttachmentHandler (filesList, appendItems = false) {
+    fileAttachmentHandler (filesList) {
```
Comment (taoeffect) [inline frontend/views/containers/chatroom/SendArea.vue:745]: It seems Sonnet 4.5 noticed a potential memory leak below, and I think it's right, because `revokeObjectURL` can't be called on this created `fileURL` in that situation.

### 1. Potential Bug in `fileAttachmentHandler` - Early Return Doesn't Clean Up Object URLs

In `SendArea.vue`, when a file exceeds the size limit, the function returns early without cleaning up already-created Object URLs:

```javascript
for (const file of filesList) {
  const fileUrl = URL.createObjectURL(file)
  const fileSize = file.size

  if (fileSize > CHAT_ATTACHMENT_SIZE_LIMIT) {
    return sbp('okTurtles.events/emit', OPEN_MODAL, 'ChatFileAttachmentWarningModal')
  }
```

**Problem**: If the 3rd file in a list of 5 files exceeds the limit, `URL.createObjectURL` was called for files 1-3, but only files 1-2 get added to the list. File 3's URL is created but never stored or revoked, causing a memory leak.

**Fix**: Create the Object URL only after validation passes:

```javascript
for (const file of filesList) {
  const fileSize = file.size

  if (fileSize > CHAT_ATTACHMENT_SIZE_LIMIT) {
    return sbp('okTurtles.events/emit', OPEN_MODAL, 'ChatFileAttachmentWarningModal')
  }

  const fileUrl = URL.createObjectURL(file)

  const attachment = {
    url: fileUrl,
    name: file.name,
    mimeType: file.type || '',
    size: fileSize,
    downloadData: null
  }

  if (getFileType(file.type) === 'image') {
    const img = new Image()
    img.onload = function () {
      const { width, height } = this
      attachment.dimension = { width, height }
    }
    img.src = fileUrl

    attachment.needsImageCompression = fileSize > IMAGE_ATTACHMENT_MAX_SIZE
  }

  list.push(attachment)
}
```

**Review by taoeffect — CHANGES_REQUESTED** [review]
Great work @SebinSong! One very minor issue spotted:

**Review by taoeffect — APPROVED** [review]
Perfect!
