### PR TITLE
Send transferables for event messages.

### LINKED ISSUE #2573: DataCloneError: Failed to execute 'postMessage' on 'Client': A MessagePort could not be cloned because it was not transferred.
### Problem

In v1.2.3, while logged out and first page load:

Image

Image

And I get more of these when I log in.

### Solution

Fix.

### PR DESCRIPTION
**Pull request by corrideat**
Closes #2573.

### CODE REVIEW

File: frontend/controller/serviceworkers/sw-primary.js [hunk 1]
```diff
@@ -104,7 +104,7 @@ sbp('okTurtles.events/on', CHELONIA_RESET, setupRootState)
 
 // These are all of the events that will be forwarded to all open tabs and windows
 ;[
-  CHELONIA_RESET, CONTRACTS_MODIFIED, CONTRACT_IS_SYNCING, CONTRACT_REGISTERED,
+  CHELONIA_RESET, CONTRACTS_MODIFIED, CONTRACT_IS_SYNCING,
```
Comment (taoeffect) [inline frontend/controller/serviceworkers/sw-primary.js:107]: Why is this removing CONTRACT_REGISTERED? Didn't we just add that at Sebin's request?

**Review by taoeffect — APPROVED** [review]
🤞🤞 this does the trick!
