### PR TITLE
#2986 - Login error modal improvement

### LINKED ISSUE #2986: Annoying service worker error during login
### Problem

The PWA on Android sometimes shows this:

Image

It offers only "Log Out" as a solution, but that isn't the best option for this error because force-quitting the PWA and launching it again works just fine.

### Solution

**For this specific error**, instead of "Log Out" as the button, make it say "Refresh" and do [`window.location.reload()`](https://developer.mozilla.org/en-US/docs/Web/API/Location/reload) when clicked.

Below the button, centered, put the following text:

```
If refreshing doesn't work, trying [logging out](#).
```

Make "logging out" a link that does what it currently does when "Log out" is clicked.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #2986 

Didn't want to complicate `Prompt.vue` for this anymore. So created a `LoginErrorModal.vue`.

---

<a href="https://app.devin.ai/review/okturtles/group-income/pull/2987">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

File: frontend/controller/app/identity.js [hunk 1]
```diff
@@ -465,26 +465,28 @@ export default (sbp('sbp/selectors/register', {
...
+          if (forkedChain || deleted) {
+            const promptOptions = {
+              heading: L('Login error'),
+              question: forkedChain
+                ? L('The server\'s history for your identity contract has diverged from ours. This can happen in extremely rare circumstances due to either malicious activity or a bug. {br_}To fix this, the contract needs to be resynced, and some recent events may be missing. {br_}Would you like to log out and resync data on your next login? {br_}Error details: {err}.', { err: errMessage, ...LTags() })
+                : L('Your account seems to have been deleted from the server. {br_}To fix this, you need to log out and create a new account. {br_}Error details: {err}.', { err: errMessage, ...LTags() }),
+              primaryButton: L('Log out'),
+              // secondaryButton: L('No'),
+              primaryButtonStyle: 'primary', // make primary button 'filled' style
+              isContentCentered: !forkedChain && !deleted
```
Comment (taoeffect) [inline frontend/controller/app/identity.js]: This logic is no longer needed since we're guaranteed `forkedChain` or `deleted` will be true here. Can just have `isContentCentered: false`

File: frontend/controller/app/identity.js [hunk 2]
```diff
@@ -465,26 +465,28 @@ export default (sbp('sbp/selectors/register', {
...
+              sbp('gi.ui/clearBanner')
+              return sbp('gi.app/identity/_private/logout', state, forkedChain)
+            } else {
+              sbp('okTurtles.events/emit', LOGIN_ERROR, { username, identityContractID, error: e })
+              throw e
+            }
           } else {
-            sbp('okTurtles.events/emit', LOGIN_ERROR, { username, identityContractID, error: e })
-            throw e
+            sbp('okTurtles.events/emit', REPLACE_MODAL, 'LoginErrorModal', null, { errorMessage: errMessage, errorState: state })
```
Comment (taoeffect) [inline frontend/controller/app/identity.js]: Opus notices that that now the code is falling through as if we've succeeded, whereas before the logic always terminated either by returning or throwing:

<details>

## Critical Bug: Missing Return Statement in identity.js

The most significant issue is in the error handling block. After emitting `REPLACE_MODAL`, execution continues and returns `identityContractID` as if the login succeeded:

```javascript
          } else {
            sbp('okTurtles.events/emit', REPLACE_MODAL, 'LoginErrorModal', null, { errorMessage: errMessage, errorState: state })
          }
        }

        // updating the 'lastLoggedIn' field is done as a periodic notification
        return identityContractID
```

This will cause the login to appear successful even though an error occurred. You need to return or throw after showing the modal:

```javascript
          } else {
            sbp('okTurtles.events/emit', REPLACE_MODAL, 'LoginErrorModal', null, { errorMessage: errMessage, errorState: state })
            return // Prevent returning identityContractID as if login succeeded
          }
```

Alternatively, if callers expect a thrown error on failure:

```javascript
          } else {
            sbp('okTurtles.events/emit', REPLACE_MODAL, 'LoginErrorModal', null, { errorMessage: errMessage, errorState: state })
            throw e // Re-throw to signal login failure
          }
```

</details>

File: frontend/views/components/modal/ModalTemplate.vue [hunk 3]
```diff
@@ -239,18 +239,4 @@ export default ({
...
-      width: 100%;
-      max-width: calc(400px + 2rem);
-      align-self: center;
-
-      @include desktop {
-        text-align: center;
-      }
-    }
-  }
-}
```
Comment (taoeffect) [inline frontend/views/components/modal/ModalTemplate.vue:255]: Opus:

Please verify that no other component relies on this `.is-centered` class. If `Prompt.vue` or other modals use `isContentCentered` prop that applies this class, those modals may now have broken styling.

File: frontend/views/containers/access/LoginErrorModal.vue [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+  template(slot='title')
+    i18n Login error
+
+  .c-container
+    .c-prompt-content(v-safe-html:a='contentMessage')
+
+    .buttons.is-centered.c-buttons
+      i18n.is-outlined(tag='button' type='button' @click.stop='refresh') Refresh
+
+    i18n.c-logout-msg(:args='{ sp_: `<span class="link">`, _sp: "</span>"}' @click='onLogoutMsgClick') If refreshing doesn't work, try {sp_}logging out{_sp}.
```
Comment (taoeffect) [inline frontend/views/containers/access/LoginErrorModal.vue]: Opus:

The "logging out" link is rendered as a `<span>` which isn't keyboard accessible by default:

```pug
i18n.c-logout-msg(:args='{ sp_: `<span class="link">`, _sp: "</span>"}' ...) 
```

Consider using an actual `<a>` tag or adding `tabindex="0"` and keyboard event handling for better accessibility. Using `<a href="#">` with `e.preventDefault()` would be more semantic.

File: frontend/views/containers/access/LoginErrorModal.vue [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+        ? L('An error occurred while logging in. Please try logging in again. {br_}Error details: {err}.', { err: this.errorMessage, ...LTags() })
+        : L('An error occurred while logging in. Please try logging in again.')
+    }
+  },
+  methods: {
+    refresh () {
+      window.location.reload()
+    },
+    onLogoutMsgClick (e) {
+      if (e.target.matches('span.link')) {
```
Comment (taoeffect) [inline frontend/views/containers/access/LoginErrorModal.vue]: Opus:

If the span ever contains nested elements, clicking on those wouldn't match. Consider using `closest()` for more robust matching:

```javascript
if (e.target.closest('span.link')) {
```

**Review by taoeffect — CHANGES_REQUESTED** [review]
Nice work @SebinSong!

I tested this by editing `service-worker.js` to throw the error that I believe is in the issue:

```js
const fn = async (maxControllerChanges, ...args) => {
    throw new Error('Service worker not ready') // eslint-disable-line no-unreachable
    if (!controller) {
      throw new Error('Service worker not ready')
    }
```

However, I didn't get the expected option to refresh:

Screenshot 2026-01-09 at 11 09 03 AM


Also left comments from Opus and me below:

File: frontend/controller/app/identity.js (hunk 2 above)
Comment (SebinSong) [reply frontend/controller/app/identity.js]: Will use `return` here as rethrowing `e` leads to a catch block below where it calls `await sbp('gi.app/identity/_private/logout')` when `LoginErrorModal` lets user choose between refresh and log-out.

File: frontend/views/components/modal/ModalTemplate.vue (hunk 3 above)
Comment (SebinSong) [reply frontend/views/components/modal/ModalTemplate.vue:255]: There is no `.modal-card` element in use in this component. This apparently is style for an old element that was removed before.

File: frontend/views/containers/access/LoginErrorModal.vue (hunk 4 above)
Comment (SebinSong) [reply frontend/views/containers/access/LoginErrorModal.vue]: Good point. Will use `<button class="link">` instead here as we don't need `e.preventDefault()` when using it.

File: frontend/views/containers/access/LoginErrorModal.vue (hunk 5 above)
Comment (SebinSong) [reply frontend/views/containers/access/LoginErrorModal.vue]: > If the span ever contains nested elements

We manually specify the i18n message ourselves in the source-code and it has no dynamic parts. So this is not the case here.

**Comment by SebinSong** [comment]
Updated the PR per feedbacks.

**Review by taoeffect — CHANGES_REQUESTED** [review]
Great! Now I get the error, however sometimes when refreshing (most of the time but not always), it doesn't show the error message in` the modal:

Screenshot_20260113_112718

```diff
diff --git a/frontend/controller/service-worker.js b/frontend/controller/service-worker.js
index b0216d31f..c99ae30d3 100644
--- a/frontend/controller/service-worker.js
+++ b/frontend/controller/service-worker.js
@@ -345,6 +345,7 @@ const swRpc = (() => {
   }, false)
 
   const fn = async (maxControllerChanges, ...args) => {
+    if (isNaN('asdf')) throw new Error('Service worker not ready')
     if (!controller) {
       throw new Error('Service worker not ready')
     }
```

Using this diff it should show `Service worker not ready` in the modal.

**EDIT:**

In testing, applied these changes only after I've logged in and created a group. If I clicked "logging out" and then refreshed the page, it shows the error correctly.

One more issue: clicking "logging out" takes me to a blank grey page. It should take me to the regular sign in page.

**Comment by SebinSong** [comment]
> One more issue: clicking "logging out" takes me to a blank grey page. It should take me to the regular sign in page.

That is not a regression.. The same happens when you click on 'Close' in the original login-error prompt here (which is replaced with the new modal in this PR):

https://github.com/okTurtles/group-income/blob/78430a42dff12b8b9b7fdf64fb3447adc74dbfda/frontend/main.js#L409-L413

And that's because that service-worker error is thrown before `ephemeral.ready = true`:

https://github.com/okTurtles/group-income/blob/78430a42dff12b8b9b7fdf64fb3447adc74dbfda/frontend/main.js#L400-L401

in which case the `<router-view>` isn't enabled yet:
https://github.com/okTurtles/group-income/blob/78430a42dff12b8b9b7fdf64fb3447adc74dbfda/frontend/index.html#L36

**Comment by taoeffect** [comment]
> That is not a regression.. The same happens when you click on 'Close' in the original login-error prompt here (which is replaced with the new modal in this PR):

Roger. Possible to boyscout then for this PR?

**Comment by SebinSong** [comment]
We should add `ephemeral.ready = true` to when a login error is caught as well for that. But not sure if that defeats the original intention this flag was created for. But the blank screen is def not a good user experience, so I can go ahead with this in this PR.

**Comment by SebinSong** [comment]
Updated PR again.

> however sometimes when refreshing (most of the time but not always), it doesn't show the error message in` the modal

This happened because refresh was done with `?modal=LoginErrorModal` remaining as the query string. So by the time the service-worker error is caught and `OPEN_MODAL` event with the error-message is queried, that is ignored as the modal is already there open. Fixed it by making the refresh happen without the query string.

**Review by taoeffect — CHANGES_REQUESTED** [review]
@SebinSong it seems to be working better now, nice job!

During testing, here's what I observed when I triggered the issue:

Screenshot_20260114_133611

There are two issues here:

1. Clicking the `X` to dismiss the top most modal doesn't dismiss it. Instead it dismisses the faded Log In modal you can see the background. This concerns me as it looks like it could be an issue with whole modal system, so we should address this.
2. Clicking `logging out` to log us out appears to log us out, but this isn't a real log out. If the code I added is commented back and then we refresh the page, we see that we're still in fact logged in. So this needs to be fixed too, to be a real logout.

**Comment by SebinSong** [comment]
1]
> Clicking the X to dismiss the top most modal doesn't dismiss it. Instead it dismisses the faded Log In modal you can see the background. This concerns me as it looks like it could be an issue with whole modal system, so we should address this.

Will fix this. 

FYI what is happening here is:
Current modal system logic handles dismissing modals in the correct order(Last-In-First-Out order when multiple modals are up). But this is a special case in that,
- `login-error` modal pops up first -> `log-in` modal is spawned next.
-  But the error modal is still displayed on top of it.
-  This is intentional because when an error occurs while various modals are open, the user still needs to able to be informed about it. (I remember resolving this in a pervioius PR a while ago where prompt modal should be visible on top of other modals)
- Regardless of this, `Modal.vue` handles dismissal queries as Last-In-First-Out order, which needs adjustment for this kind of case.


2]

> Clicking logging out to log us out appears to log us out, but this isn't a real log out.

As in my prev comment, this is not a regression either but an existing issue. This previous logic I've replaced with the error modal does call `await sbp('gi.app/identity/logout')`:

https://github.com/okTurtles/group-income/blob/78430a42dff12b8b9b7fdf64fb3447adc74dbfda/frontend/main.js#L408-L413
 
But refreshing the page after removing the manual service-worker error once this logic is excuted shows it's not logged out.

Will try to figure this out in this PR and boyscout it if a fix found.

File: frontend/views/containers/access/LoginErrorModal.vue [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+  },
+  methods: {
+    refresh () {
+      const { origin, pathname } = window.location
+      // Reload page but without ?modal=LoginErrorModal in the url query string.
+      window.location.href = `${origin}${pathname}`
+    },
+    onLogoutMsgClick (e) {
+      if (e.target.closest('button.link')) {
+        sbp('gi.actions/identity/_private/logout')
```
Comment (taoeffect) [inline frontend/views/containers/access/LoginErrorModal.vue]: Two concerns here:

1. I'm not sure why `_private` is being used... Generally speaking that shouldn't be used unless there's a good  reason, and then that reason should be documented. I do realize that the previous code was using it, but I'm not sure why. Can you try without it and see if everything still works?
2. Why did you switch this to `gi.actions` from `gi.app`? It seems to me like it would be better to call it from `gi.app`... especially as the other code above does too.

Comment (SebinSong) [reply frontend/views/containers/access/LoginErrorModal.vue]: It's just me trying various things to fix `2.` in the comment [above](https://github.com/okTurtles/group-income/pull/2987#pullrequestreview-3662915213)

This is the logout call in the PROD:
https://github.com/okTurtles/group-income/blob/78430a42dff12b8b9b7fdf64fb3447adc74dbfda/frontend/main.js#L408

which I initally tried and does not work. 

`gi.app/identity/logout` internally calls `gi.app/identity/_private/logout` which in turn calls `gi.actions/identity/logout`:

https://github.com/okTurtles/group-income/blob/78430a42dff12b8b9b7fdf64fb3447adc74dbfda/frontend/controller/app/identity.js#L513-L518

But then `gi.actions/identity/logout` here is never called when this manual service-worker error is thrown because of `if (!state.loggedIn) return` here..

`gi.actions/identity/_private/logout` is what `gi.actions/identity/logout` internally calls. That's why I tried calling it directly in the modal.

---
Like I said before `2.` in [this comment](https://github.com/okTurtles/group-income/pull/2987#pullrequestreview-3662915213) is an existing issue if you try the manual service-worker error scenario in the `master`.
Let me just put it back to `gi.app/identity/logout` here. so that the issue can be handled separately from this PR..

Comment (SebinSong) [reply frontend/views/containers/access/LoginErrorModal.vue]: FYI, calling `gi.actions/identity/...` directly didn't work either and leads to the manual service-worker error thrown _once more_. Apparently because that leads to calling `swRpc` function here:
https://github.com/okTurtles/group-income/blob/4be91ab4c0597932176a3c2cd702b014103d7c48/frontend/controller/service-worker.js#L338-L341

possibly due to `gi.actions/*` selector registration further down the file:

https://github.com/okTurtles/group-income/blob/4be91ab4c0597932176a3c2cd702b014103d7c48/frontend/controller/service-worker.js#L402-L404

File: frontend/views/components/modal/ModalMixins.js [hunk 7]
```diff
@@ -49,7 +50,9 @@ const modalMixins = {
       'setTemporaryReducedMotion'
     ]): any),
     close (e: any) {
-      this.unload()
+      // If optional modalName prop is provided, explicitly pass it as the targetModal to unload
+      // Otherwise, the modal system will unload the latest modal(Last in, First out).
+      this.unload(this.modalName || '')
```
Comment (taoeffect) [inline frontend/views/components/modal/ModalMixins.js]: Just to be safe, since we don't know how all of the `CLOSE_MODAL` event listeners are implemented, can this just be:

```js
this.unload(this.modalName || '')
```

*EDIT: oops, I meant `this.unload(this.modalName)`*

This way `undefined` gets passed in to them as before if `this.modalName` is undefined.

File: frontend/views/containers/access/LoginErrorModal.vue (hunk 6 above)
Comment (SebinSong) [reply frontend/views/containers/access/LoginErrorModal.vue]: Another thing I've noticed is, by the time we catch this 'service-worker not ready' error, a logout attempt has already been made:



but the same error is re-thrown again from this `swRpc` function:

https://github.com/okTurtles/group-income/blob/4be91ab4c0597932176a3c2cd702b014103d7c48/frontend/controller/service-worker.js#L402-L413

---

**Q.** Apparently `gi.db/settings/...` selectors are not affected by this `swRpc`. Would it be a safe/good idea to call below codes directly instead of `gi.app/identity/logout` in this case?

https://github.com/okTurtles/group-income/blob/4be91ab4c0597932176a3c2cd702b014103d7c48/frontend/controller/app/identity.js#L548-L550

**Review by taoeffect — DISMISSED** [review]
Seems to work well, great work @SebinSong!

File: frontend/views/components/modal/ModalMixins.js (hunk 7 above)
Comment (SebinSong) [reply frontend/views/components/modal/ModalMixins.js]: Did you mean `this.unload(this.modalName)`? I think it should be fine as `this.unload(this.modalName || '')` but your concern makes sense. will make that update.

Comment (taoeffect) [reply frontend/views/components/modal/ModalMixins.js]: Oh — yes! I did mean that! 🤦‍♂️

**Review by taoeffect — DISMISSED** [review]
Great work!

File: frontend/controller/app/identity.js [hunk 8]
```diff
@@ -465,26 +465,29 @@ export default (sbp('sbp/selectors/register', {
...
```
[the remark this answers is not in the document]
Comment (SebinSong) [reply frontend/controller/app/identity.js]: That's a correct observation. Updated accordingly.

I've also made additional update for 

> 🔴 REPLACE_MODAL crashes when no modal is open during auto-login error

 in `replaceModal` method where if `REPLACE_MODAL` is fired when there is no modal open, it just passes things along to `openModal` so that the modal system doesn't crash.

File: frontend/views/containers/access/LoginErrorModal.vue [hunk 9]
```diff
@@ -0,0 +1,80 @@
...
+  },
+  methods: {
+    refresh () {
+      const { origin, pathname } = window.location
+      // Reload page but without ?modal=LoginErrorModal in the url query string.
+      window.location.href = `${origin}${pathname}`
+    },
+    onLogoutMsgClick (e) {
+      if (e.target.closest('button.link')) {
+        sbp('gi.app/identity/logout')
```
[the remark this answers is not in the document]
Comment (SebinSong) [reply frontend/views/containers/access/LoginErrorModal.vue:48]: This is not a regression. If you check:

https://github.com/okTurtles/group-income/blob/78430a42dff12b8b9b7fdf64fb3447adc74dbfda/frontend/main.js#L408

This one does not pass error state either.

> When errorState is not passed, it falls back to the current vuex state. However, if the login failed before the vuex > state was updated with loggedIn, the logout function will return early at line 519 without performing any cleanup.

That's something I observed during investigation and reported [here](https://github.com/okTurtles/group-income/pull/2987#discussion_r2699850316) too. But due to `swRpc` problem I wrote in the following comment chain, the `gi.app/...` and `gi.actions/...` selectors for logout can't be called for this particular case.. which might be handled as a separate issue. Marking the conversation resolved for now.

**Review by taoeffect — APPROVED** [review]
