### PR TITLE
Resolving a few mobile issues

### LINKED ISSUE #1413: Multiple UI bugs in dashboard
#### Bug 1: Safari can't scroll to the bottom of the dashboard

a1

You must test this on Safari (and preferably on an iPhone) to see if it's fixed, because it doesn't show up in Responsive Mode on Firefox.

#### Bug 2: Right Sidebar doesn't display when scrolled to bottom of dashboard

EDIT: @SebinSong fixed Bug 2 in #1414. But Bug 1 still needs a fix!

b1

This actually is testable in Firefox responsive mode. You must first scroll down to the bottom and then make the right sidebar appear.

### Solution

Fix both!

EDIT: @SebinSong fixed Bug 2 in #1414. But Bug 1 still needs a fix!

### LINKED ISSUE #1576: [Mobile] Can't scroll down on dashboard + hamburger/logo overlap
### Problem

1. I can't scroll down on mobile iOS Safari in the group homepage to see the full text of the proposals. In the image below, that's as far as I can scroll down.
2. The hamburger and group icon are overlapping. Also the 'i' menu on the right isn't properly rendered either, see #1577 for an example of this.

dashboard

### Solution

1. Fix scrolling.
2. Add ellipses to group name if necessary to prevent overlap

### LINKED ISSUE #1598: [Mobile] 'Copy link' button for invite links are broken in mobile screen
### Problem
Invite link 'copy to clipboard' functionality is apparently broken in mobile screen
(The same functionality works well in desktop screen)

### Solution
Fix it.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #1576 
closes #1598 
closes #1413 

The screenshot for  the bug-fixes for issue 1576

### CODE REVIEW

File: frontend/views/pages/GroupChat.vue [hunk 1]
```diff
@@ -204,9 +204,15 @@ export default ({
...
-    display: none;
+::v-deep {
+  .c-logo {
+    @include touch {
+      display: none;
+    }
+  }
+
+  .p-main {
+    height: auto !important;
```
Comment (SebinSong) [inline frontend/views/pages/GroupChat.vue:215]: The fix made above (`height: fit-content;`) cannot be applied to the `GroupChat.vue` page because, the chat currently has the setting where message layout fills the entire available height even when the content is not long enough. So applying `height: auto;` only to `/group-chat` page here.

File: frontend/views/containers/group-settings/InvitationsTable.vue [hunk 2]
```diff
@@ -41,21 +41,17 @@ page-section.c-section(:title='L("Invite links")')
...
+              i.icon-ellipsis-v
+            menu-content.c-dropdown-invite-link
               ul
                 menu-item(
                   tag='button'
                   icon='link'
+                  @click='copyInviteLink(item.inviteLink)'
                 )
-                  // #780 TODO test/verify if webShare works in a real mobile device.
-                  //      And refactor this markup to only have one menu-parent
```
Comment (SebinSong) [inline frontend/views/containers/group-settings/InvitationsTable.vue:58]: worked on this TODO as well while at fixing the issue 1598.

**Review by taoeffect — CHANGES_REQUESTED** [review]
Nice work @SebinSong!

Please make sure to test this PR yourself with `grunt dev --tunnel` to discover issues.

I did that and found that I still could not scroll all the way down to the bottom on iOS:

a

Also, while testing whether the group name would now show ellipses in the title bar, I discovered that on the group settings page I couldn't scroll up to the top either. And I had no way to go back to the dashboard:

b

**Comment by SebinSong** [comment]
@taoeffect Just updated the PR again. Also, please make sure to test it in my feature branch which is **sebin/task/#1576-design-issue-in-mobile** 
As you can see from the screenshots below, I made sure the issues are resolved on my mobile browsers.

- pages are not cropped in mobile browsers




- really long group-name displayed with ellipsis

**Review by taoeffect — APPROVED** [review]
Fan-frickin'-tastic @SebinSong! 😄 🎉

**Review by taoeffect — CHANGES_REQUESTED** [review]
Oops! Spoke too soon.

The scrolling works great now, but the invite link still is broken on iOS:

a

There are 2 issues:

1. The background of the menu does not look right in dark mode. Can you adjust it so that it looks good? (If you can't find designs for it, just pick something that looks good using the existing colors so that there isn't a weird black border outside of the grey menu)
2. Clicking "Copy Link" doesn't copy the link to the clipboard

**Comment by SebinSong** [comment]
@taoeffect Updated the PR again with the work for your two requests.

I actually removed those top/bottom paddings from the pop-up menu and added box-shadow to it to make sure it stands out from the background. Hope it looks good.

**Comment by SebinSong** [comment]
apparently merging this PR will resolve the issue #1413 too.

**Review by taoeffect — APPROVED** [review]
Approved! Great work @SebinSong!
