### PR TITLE
Various fixes & improvements

### LINKED ISSUE #2687: Event handler warning for online and offline events in Brave
### Problem

After a recent update to 1.2.14, the testing site was redirected to a grey page:

Image

Also in the console are these warnings:

Image

### Solution

Maybe we can figure out why it was redirected to a blank page.

But also for this issue would be to fix where this is called:

Image

### PR DESCRIPTION
**Pull request by corrideat**
Definitely closes #2687.
May 'close' #2680, #2690.

### CODE REVIEW

File: frontend/controller/service-worker.js [hunk 1]
```diff
@@ -68,6 +68,8 @@ const waitUntilSwReady = () => {
     const messageChannel = new MessageChannel()
     messageChannel.port1.onmessage = (event) => {
       if (event.data.type === 'ready') {
+        if (!event.data.currentSyncs) return
```
Comment (taoeffect) [inline frontend/controller/service-worker.js]: This is a curious line.... could you add a comment about why it's here? Is this to handle old SW versions or something?

File: frontend/main.js [hunk 2]
```diff
@@ -183,6 +183,9 @@ async function startApp () {
       this.ephemeral.syncs = this.ephemeral.syncs.filter(id => id !== contractID)
     }
   }
+  sbp('okTurtles.events/on', NEW_CURRENT_SYNCS, (currentSyncs) => {
+    this.ephemeral.syncs = currentSyncs
+  })
```
Comment (taoeffect) [inline frontend/main.js]: This seems like a handler that is supposed to update the frontend's understand of whatever contracts are currently being sync'd, but it doesn't seem like it's doing that because the only time the `NEW_CURRENT_SYNCS` event seems to be emitted is once at page load.

File: frontend/controller/serviceworkers/sw-primary.js [hunk 3]
```diff
@@ -325,7 +325,7 @@ const setupPromise = setupChelonia()
 
 self.addEventListener('install', function (event) {
   console.debug('[sw] install')
-  event.waitUntil(Promise.all([setupPromise, self.skipWaiting()]))
+  event.waitUntil(setupPromise.then(() => self.skipWaiting()))
```
Comment (taoeffect) [inline frontend/controller/serviceworkers/sw-primary.js:331]: Are you sure it shouldn't be `skipWaiting.then(() => self.setupPromise())` ?

(I'm not saying it should be... I just don't know myself)

File: frontend/controller/service-worker.js [hunk 4]
```diff
@@ -191,6 +193,19 @@ sbp('sbp/selectors/register', {
...
+          if (['activated', 'redundant'].includes(e.target.state)) {
+            e.target.removeEventListener('statechange', handler)
+            return
+          }
+          if (e.target.state === 'installed') {
+            e.target.postMessage({ type: 'skip-waiting' })
+          }
+        }
+        e.target.installing.addEventListener('statechange', handler, false)
+      })
```
Comment (taoeffect) [inline frontend/controller/service-worker.js:217]: Could you add a brief comment above this explaining why this was added?

**Review by taoeffect — CHANGES_REQUESTED** [review]
Nice work @corrideat!

Left a few comments!

Also, could you please edit the PR description to reference:

- Which issues this definitely closes
- Which issues this might close

File: frontend/main.js (hunk 2 above)
Comment (corrideat) [reply frontend/main.js]: `NEW_CURRENT_SYNCS` is emitted on a SW update.

Comment (taoeffect) [reply frontend/main.js]: I see that, but shouldn't it be emitted whenever there are "new syncs"?

File: frontend/controller/serviceworkers/sw-primary.js (hunk 3 above)
Comment (corrideat) [reply frontend/controller/serviceworkers/sw-primary.js:331]: Not sure myself, and the documentation isn't very helpful here. However, I think this is correct. `skipWaiting` tells the browser that the SW should immediately move from `installed` to `activated` (or from `waiting` to `activated`). We only want to do this after setup is complete, so this seems reasonable. With the previous code, I think it worked the same way too, since it'd wait until `setupPromise` had resolved, but now it's more explicit.

TL;DR: I think it doesn't matter when `skipWaiting` is called, but, if it made a difference, what's now there seems more correct.

File: frontend/controller/service-worker.js (hunk 1 above)
Comment (corrideat) [reply frontend/controller/service-worker.js]: Yes, this should reasonanly handle old or new SW versions that don't have this field.

File: frontend/controller/serviceworkers/sw-primary.js (hunk 3 above)
Comment (taoeffect) [reply frontend/controller/serviceworkers/sw-primary.js:331]: Can you copy/paste that as a comment into the code?

File: frontend/main.js (hunk 2 above)
Comment (taoeffect) [reply frontend/main.js]: Can you rename `NEW_CURRENT_SYNCS` to `CONTRACT_SYNCS_RESET`?

**Comment by taoeffect** [comment]
Could you also add this `no-store` to the `GET /time` to this PR? https://github.com/okTurtles/group-income/pull/2494#discussion_r1978033066

File: frontend/controller/service-worker.js [hunk 5]
```diff
@@ -68,6 +68,10 @@ const waitUntilSwReady = () => {
     const messageChannel = new MessageChannel()
     messageChannel.port1.onmessage = (event) => {
       if (event.data.type === 'ready') {
+        // For backward- and forward-compatibility (`currentSyncs` may not be
+        // defined in a different SW version)
+        if (!event.data.currentSyncs) return
```
Comment (taoeffect) [inline frontend/controller/service-worker.js]: Actually, one more question: should this call `reject` before calling `return`?

Comment (corrideat) [reply frontend/controller/service-worker.js]: No, but `resolve` should be called. Fixed.

**Review by taoeffect — APPROVED** [review]
Nice! 🤞 that this does it!
