### PR TITLE
Issues in Modal and Tab

### LINKED ISSUE #1518: UI issues in Modal and Tab
### Problem

- Modal has `padding-left` and `padding-right` in table and mobile view. I think we should remove it.
image
- Unexpected clickable area in tablet and mobile view.
It's possible to redirect by clicking any point of the screen in tablet and mobile view.
image

### Solution

- In `ModalBaseTemplate.vue`, there is a modal style.
```
.modal {
  ...

  &.fullscreen {
    ...
    padding: 0 1rem;

    @include tablet {
      padding: 0 1.5rem;
    }
  }
}
```
- Need to debug and fix it

cc: @leihla, @taoeffect

### LINKED ISSUE #1522: Group Chat: Delete message animation
### Problem

As it described in [Figma](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=5159-0&t=diXaekDjo34xtEua-0), there should be animation when user deletes messages.
image

### Solution

Make it animate when user deletes any messages.
Duration could be 0.3s or any if it looks better.

### LINKED ISSUE #1531: Flickering when switching to and from chat
### Problem

Is there a way to reduce the flickering seen here?

a mov

### Solution

Ideally, the messages would instantly appear with no flickering (unless they need to be loaded). Since these messages were recently loaded, there shouldn't be any flickering, especially because #1374 was closed.

### PR DESCRIPTION
**Pull request by Silver-IT**
### Summary of Changes

- Closes #1518 
- Fixed error to open `Avatar Upload Dialog` by clicking outside of avatar
- Updated navigation style according to [the Figma design](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=48-86&t=os0ghfUG39u4AYc3-0)
- Fixed position error of textarea in Chat page when the page is full of messages.
  Steps to reproduce
  a. Fill the chat page with messages
  b. Focus on the textarea and add messages having several lines. `Ctrl+Enter` can be used.
  c. Check the position of textarea.
- Closes #1522 
- Closes #1531

### CODE REVIEW

File: frontend/views/components/modal/ModalBaseTemplate.vue [hunk 1]
```diff
@@ -52,11 +52,11 @@ export default ({
...
     background: $general_2;
-    padding: 0 1rem;
+    // padding: 0 1rem;
 
-    @include tablet {
-      padding: 0 1.5rem;
-    }
+    // @include tablet {
+    //   padding: 0 1.5rem;
+    // }
```
Comment (taoeffect) [inline frontend/views/components/modal/ModalBaseTemplate.vue:59]: @pieer this needs your review

File: frontend/views/components/tabs/TabWrapper.vue [hunk 2]
```diff
@@ -25,6 +21,11 @@
           .c-icons
             i.icon-chevron-right
 
+        hr.tab-nav-separator
+
+      .tab-nav-list.is-subtitle Version 1.6.0
```
Comment (taoeffect) [inline frontend/views/components/tabs/TabWrapper.vue]: 1. If you're going to add a user-facing version it needs to match the actual version
2. Missing `i18n`

File: frontend/views/components/tabs/TabWrapper.vue [hunk 3]
```diff
@@ -25,6 +21,11 @@
...
+      .tab-nav-list.tab-nav-ack.is-subtitle Acknowledgements
```
Comment (taoeffect) [inline frontend/views/components/tabs/TabWrapper.vue]: 1. Missing `i18n`
2. Doesn't actually doing anything. I would comment out for now with a `TODO` that points to an issue

**Review by taoeffect — CHANGES_REQUESTED** [review]
Reviewed! @pieer also could use your eyes

File: frontend/views/components/tabs/TabWrapper.vue (hunk 2 above)
Comment (Silver-IT) [reply frontend/views/components/tabs/TabWrapper.vue]: Right. Will do that

File: frontend/views/components/tabs/TabWrapper.vue (hunk 3 above)
Comment (Silver-IT) [reply frontend/views/components/tabs/TabWrapper.vue]: Make sense.

Comment (taoeffect) [reply frontend/views/components/tabs/TabWrapper.vue]: That issue exists btw: https://github.com/okTurtles/group-income/issues/673

File: frontend/views/components/modal/ModalBaseTemplate.vue (hunk 1 above)
Comment (pieer) [reply frontend/views/components/modal/ModalBaseTemplate.vue:59]: If there is no need for padding, then this can be removed.

**Review by pieer — DISMISSED** [review]

File: frontend/views/containers/user-settings/Acknowledgements.vue [hunk 4]
```diff
@@ -0,0 +1,145 @@
+<template lang='pug'>
+  .settings-container
+    section.card
+      .c-header
+        p.c-instructions
+          i18n(
+            :args='{ a_: okTurtlesPageTag, _a: "</a>" }'
+          ) Group Income is developed by the {a_}okTurtles Foundation{_a} and is funded entirely by individual contributions.
+      i18n.link(tag='button' @click='openSupport') Support this project
```
Comment (taoeffect) [inline frontend/views/containers/user-settings/Acknowledgements.vue]: This should go to https://okturtles.org/donate

File: frontend/views/components/tabs/TabWrapper.vue [hunk 5]
```diff
@@ -34,6 +40,8 @@ import sbp from '@sbp/sbp'
 import { mapGetters } from 'vuex'
 import TabItem from '@components/tabs/TabItem.vue'
 import { logExceptNavigationDuplicated } from '@view-utils/misc.js'
+import { L } from '@common/common.js'
+import packageJSON from '~/package.json'
```
Comment (taoeffect) [inline frontend/views/components/tabs/TabWrapper.vue]: I'm not sure, but eslint might be able to optimize this by not including the entire package.json file, and just the version number, if you import like this: `import { contractsVersion } from '~/package.json'`

File: frontend/views/containers/chatroom/ChatMain.vue [hunk 6]
```diff
@@ -552,34 +552,49 @@ export default ({
...
         // NOTE: while syncing the chatroom contract, we should ignore all the events
         if (contractID === this.currentChatRoomId) {
+          const { addedOrDeleted, self } = isMessageAddedOrDeleted(message)
+
+          if (addedOrDeleted === 'DELETED') {
+            // NOTE: Message will be deleted in processMessage function
+            //       but need to make animation to delete it, probably here
+            const messageHash = message.decryptedValue().data.hash
+            const msgIndex = findMessageIdx(messageHash, this.messages)
+            document.querySelectorAll('.c-body-conversation > .c-message')[msgIndex]?.classList.add('c-disappeared')
```
Comment (taoeffect) [inline frontend/views/containers/chatroom/ChatMain.vue:590]: In dark-mode, the deleting animation uses a white background instead of a red one. Can you choose a nice red color so that the animation remains consistent in color?

File: frontend/views/containers/user-settings/Acknowledgements.vue [hunk 7]
```diff
@@ -0,0 +1,145 @@
...
+          },
+          {
+            title: 'Conversation',
+            name: 'By Gregor Cresnar',
+            url: '#'
+          },
+          {
+            title: 'Vote',
+            name: 'By HeadsOfBirds',
+            url: '#'
```
Comment (taoeffect) [inline frontend/views/containers/user-settings/Acknowledgements.vue]: If you aren't able to find links to these, could you comment them out for now?

**Review by taoeffect — CHANGES_REQUESTED** [review]
Excellent work @Silver-IT! Minor details remaining and commented! After this I think it's good to merge!

File: frontend/views/containers/user-settings/Acknowledgements.vue (hunk 7 above)
Comment (Silver-IT) [reply frontend/views/containers/user-settings/Acknowledgements.vue]: Okay.

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 6 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue:590]: Oh, yes. Nice catch. I think the other colors (such as primary, danger, warning) are also strange in dark-mode.
image

I think I should check the color palette.

Comment (taoeffect) [reply frontend/views/containers/chatroom/ChatMain.vue:590]: OK whenever @leihla gets to this we can update it later in a future PR

File: frontend/views/containers/chatroom/ChatMain.vue [hunk 8]
```diff
@@ -415,8 +418,8 @@ export default ({
         onlyRenderMessage: true // NOTE: DO NOT RENAME THIS OR CHATROOM WOULD BREAK
       }
     },
-    async renderMoreMessages (refresh = false) {
-      if (refresh) {
+    async renderMoreMessages (shouldInitiate = true) {
```
Comment (taoeffect) [inline frontend/views/containers/chatroom/ChatMain.vue:423]: Can you add a comment above this line explaining what `shouldInitiate` means?

Also maybe next to `messagesInitiated` on line 165?

Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue:423]: Sure. Will add comment.

File: frontend/views/containers/chatroom/ChatMain.vue (hunk 6 above)
Comment (Silver-IT) [reply frontend/views/containers/chatroom/ChatMain.vue:590]: We can create a new issue(#1538) for this update on the color palette and do in another PR later.

**Review by taoeffect — APPROVED** [review]
Approved! Excellent work @Silver-IT!
