### PR TITLE
#2512 - Fix a couple of chat regressions

### LINKED ISSUE #2512: Chat regressions on master related to list spacing and emoji span
### Problem

Testing loading the GIG group locally over localhost:3000 in Firefox (EDIT: and Safari too!) on `master`, I see this:

Image
Image

Multiple issues:

1. The spacing on lists, both ordered and unordered, is completely wrong.
2. For some reason numbers are now wrapped in `<span class="chat-emoji">`, wherever they are, even in URLs

### Solution

Restore previous behavior.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #2512 

**[ screenshot for the fix ]**

image

### CODE REVIEW

File: frontend/views/utils/markdown-utils.js [hunk 1]
```diff
@@ -40,25 +40,23 @@ export function renderMarkdown (str: string): any {
...
+      // So we need to manually add <br/> tags here before passing it to markedjs.
+      // (Reference: https://github.com/markedjs/marked/issues/190#issuecomment-865303317)
+      entryText = entryText.replace(/\n(?=\n)/g, '\n\n<br/>\n')
       entry.text = entryText
     }
   })
 
   str = combineMarkdownSegmentListIntoString(strSplitByCodeMarkdown)
-  str = str.replace(/(\d+\.|-)(\s.+)\n<br>/g, '$1$2\n\n')
-    .replace(/(>)(\s.+)\n<br>/gs, '$1$2\n\n') // Check for [2], [3] above once more to resolve edge-cases (reference: https://github.com/okTurtles/group-income/issues/2356)
```
Comment (SebinSong) [inline frontend/views/utils/markdown-utils.js:54]: To give a context here, these multiple lines of regExp logics to manually add `<br>` here had been added over time to resolve issues related to multiple line-breaks in the chat. (`markedjs` with 'gfm' option does not support the behavior we want. eg. we would want `\n\n\n` to become `<br><br><br>` but it collapses them all and convert to a single `<br>` or sometimes even removes them all)

I re-assessed these part and enhanced/simplified as much as I could because it had been growing in complexity over time, which made it hard to maintain. I made sure this change doesn't break the previous issues we fixed before:

**[Complex markdown structure 1 - nested lists]**

image

**[Complex markdown structure 2 - blockquotes]**

image

**Review by taoeffect — CHANGES_REQUESTED** [review]
Fantastic work @SebinSong!

I think you got almost everything!

I did some tests and it seems there may still be an issue in how newlines are handled in blockquotes.

Have a look at this:

```md
Hello https://asdf.com https://okturtles.org

> This is a test
> Of the https://asdf.com https://okturtles.org system
> 
> Does it work?
> () => Does it actually work? <>
> <adsf>asdf</asdf>
> 
> ```js
> hello
> ```
> 1. asdf
> 2. sadfasdf https://asdf.com https://okturtles.org/1111 😜👍
> 3. https://asdf.com https://okturtles.org
>    1. Is this really 1234 working? #general you tell me @u1!
>        ```
>        does it?
>        ```

- It seems not always
- Another test
```

Which renders on GH like this:

--------

Hello https://asdf.com https://okturtles.org

> This is a test
> Of the https://asdf.com https://okturtles.org system
> 
> Does it work?
> () => Does it actually work? <>
> <adsf>asdf</asdf>
> 
> ```js
> hello
> ```
> 1. asdf
> 2. sadfasdf https://asdf.com https://okturtles.org/1111 😜👍
> 3. https://asdf.com https://okturtles.org
>    1. Is this really 1234 working? #general you tell me @u1!
>        ```
>        does it?
>        ```

- It seems not always
- Another test

------------


And in GI like this:

Screenshot 2025-01-18 at 10 40 10 AM

I am actually OK with `#general` or `@u1` not rendering deep within blockquotes. It's not the end of the world.

However, the fact that this section is rendered incorrectly is a serious issue:

```
> Does it work?
> () => Does it actually work? <>
> <adsf>asdf</asdf>
```

It should be broken up across 3 lines, but GI breaks it up across 2 lines.

**Comment by SebinSong** [comment]
@taoeffect 
Fixed both issues you pointed out:

image

---
One thing I noticed in your comment was that GI comment also seems to have the rendering issue too (Or, could be an expected behavior for their markdown convertor):

**[ Input ]**


<br><br>

**[ Output - Some texts disappear ]**
Apparently `<asdf>asdf</asdf>` is interpreted as an illegal html and sanitized.


<br><br>

And below is the **raw** conversion output from `markedjs`. (check out [this markedjs playground](https://marked.js.org/demo/?text=Hello%20https%3A%2F%2Fasdf.com%20https%3A%2F%2Fokturtles.org%0A%0A%3E%20This%20is%20a%20test%0A%3E%20Of%20the%20https%3A%2F%2Fasdf.com%20https%3A%2F%2Fokturtles.org%20system%0A%3E%20%0A%3E%20Does%20it%20work%3F%0A%3E%20()%20%3D%3E%20Does%20it%20actually%20work%3F%20%3C%3E%0A%3E%20%3Cadsf%3Easdf%3C%2Fasdf%3E%0A%3E%20%0A%3E%20%60%60%60js%0A%3E%20hello%0A%3E%20%60%60%60%0A%3E%201.%20asdf%0A%3E%202.%20sadfasdf%20https%3A%2F%2Fasdf.com%20https%3A%2F%2Fokturtles.org%2F1111%20%F0%9F%98%9C%F0%9F%91%8D%0A%3E%203.%20https%3A%2F%2Fasdf.com%20https%3A%2F%2Fokturtles.org%0A%3E%20%20%20%201.%20Is%20this%20really%201234%20working%3F%20%23general%20you%20tell%20me%20%40u1!%0A%3E%20%20%20%20%20%20%20%20%60%60%60%0A%3E%20%20%20%20%20%20%20%20does%20it%3F%0A%3E%20%20%20%20%20%20%20%20%60%60%60%0A%0A-%20It%20seems%20not%20always%0A-%20Another%20test%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=15.0.6))



<br><br>

which is where you can see the same issues happening too. It does not even support multiple line-breaks **in a row**, as mentioned before.

--- 

What I want to mention here is, The amount of custom logics to override/fix these default behaviors created by `markedjs` are quite large at this point so it feels quite hard and tricky to maintain these area now.
(Eg. Trying to fix one issue introduces regressions for previous fixes etc.)
So, I'm worried if we would try to add more custom behaviors in the future, that might make the code harder to manage. Just something I felt while working on the updates. Thanks.

**Review by taoeffect — APPROVED** [review]
Amazing work @SebinSong!

> What I want to mention here is, The amount of custom logics to override/fix these default behaviors created by markedjs are quite large at this point so it feels quite hard and tricky to maintain these area now.
(Eg. Trying to fix one issue introduces regressions for previous fixes etc.)
So, I'm worried if we would try to add more custom behaviors in the future, that might make the code harder to manage. Just something I felt while working on the updates. Thanks.

Indeed. If you think of a better way to solve this, e.g. maybe switching to a different library, or maybe diving more into markedjs' capabilities (if any such capabilities exist), feel free to open an issue.
